from .sympy_imports import *

basic = [
    (r"0", 0),
    (r"1", 1),
    (r"-3.14", Mul(-1, 3.14)),
    (r"(-7.13)(1.5)", Mul(Mul(-1, 7.13), 1.5)),
    (r"x", x),
    (r"2x", 2 * x),
    (r"x^2", x ** 2),
    (r"x^{3 + 1}", x ** Add(3, 1)),
    (r"-c", -c),
    (r"a \cdot b", a * b),
    (r"a / b", a / b),
    (r"a \div b", a / b),
    (r"a + b", a + b),
    (r"a + b - a", Add(a + b, -a)),
    (r"a^2 + b^2 = c^2", Eq(a ** 2 + b ** 2, c ** 2)),
    (r"(x + y) z", Mul(Add(x, y), z)),
    (r"\left(x + y\right) z", Mul(Add(x, y), z)),
    (r"\left( x + y\right ) z", Mul(Add(x, y), z)),
    (r"\left(  x + y\right ) z", Mul(Add(x, y), z)),
    (r"\left[x + y\right] z", Mul(Add(x, y), z)),
    (r"\left\{x + y\right\} z", Mul(Add(x, y), z)),
    (r"1+1", Add(1, 1)),
    (r"0+1", Add(0, 1)),
    (r"1*2", Mul(1, 2)),
    (r"0*1", Mul(0, 1)),
    (r"x = y", Eq(x, y)),
    (r"x \neq y", Ne(x, y)),
    (r"x < y", Lt(x, y)),
    (r"x > y", Gt(x, y)),
    (r"x \leq y", Le(x, y)),
    (r"x \geq y", Ge(x, y)),
    (r"x \le y", Le(x, y)),
    (r"x \ge y", Ge(x, y)),
    (r"\lfloor x \rfloor", floor(x)),
    (r"\lceil x \rceil", ceiling(x)),
    (r"\langle x |", Bra("x")),
    (r"| x \rangle", Ket("x")),
    (r"\sin \theta", sin(theta)),
    (r"\sin(\theta)", sin(theta)),
    (r"\sin^{-1} a", asin(a)),
    (r"\sin a \cos b", Mul(sin(a), cos(b))),
    (r"\sin \cos \theta", sin(cos(theta))),
    (r"\sin(\cos \theta)", sin(cos(theta))),
    (r"\frac{a}{b}", a / b),
    (r"\frac{a + b}{c}", Mul(a + b, Pow(c, -1))),
    (r"\frac{7}{3}", Mul(7, Pow(3, -1))),
    (r"(\csc x)(\sec y)", csc(x) * sec(y)),
    (r"\lim_{x \to 3} a", Limit(a, x, 3)),
    (r"\lim_{x \rightarrow 3} a", Limit(a, x, 3)),
    (r"\lim_{x \Rightarrow 3} a", Limit(a, x, 3)),
    (r"\lim_{x \longrightarrow 3} a", Limit(a, x, 3)),
    (r"\lim_{x \Longrightarrow 3} a", Limit(a, x, 3)),
    (r"\lim_{x \to 3^{+}} a", Limit(a, x, 3, dir="+")),
    (r"\lim_{x \to 3^{-}} a", Limit(a, x, 3, dir="-")),
    (r"\infty", oo),
    (r"\lim_{x \to \infty} \frac{1}{x}", Limit(Pow(x, -1), x, oo)),
    (r"\frac{d}{dx} x", Derivative(x, x)),
    (r"\frac{d}{dt} x", Derivative(x, t)),
    (r"f(x)", f(x)),
    (r"f(x, y)", f(x, y)),
    (r"f(x, y, z)", f(x, y, z)),
    (r"\frac{d f(x)}{dx}", Derivative(f(x), x)),
    (r"\frac{d\theta(x)}{dx}", Derivative(Function("theta")(x), x)),
    (r"x \neq y", Unequality(x, y)),
    (r"|x|", Abs(x)),
    (r"||x||", Abs(Abs(x))),
    (r"|x||y|", Abs(x) * Abs(y)),
    (r"||x||y||", Abs(Abs(x) * Abs(y))),
    (r"z^{|xy|}", z ** Abs(x * y)),
    (r"\int x dx", Integral(x, x)),
    (r"\int x d\theta", Integral(x, theta)),
    (r"\int (x^2 - y)dx", Integral(x ** 2 - y, x)),
    (r"\int x + a dx", Integral(Add(x, a), x)),
    (r"\int da", Integral(1, a)),
    (r"\int_0^7 dx", Integral(1, (x, 0, 7))),
    (r"\int_a^b x dx", Integral(x, (x, a, b))),
    (r"\int^b_a x dx", Integral(x, (x, a, b))),
    (r"\int_{a}^b x dx", Integral(x, (x, a, b))),
    (r"\int^{b}_a x dx", Integral(x, (x, a, b))),
    (r"\int_{a}^{b} x dx", Integral(x, (x, a, b))),
    (r"\int^{b}_{a} x dx", Integral(x, (x, a, b))),
    (r"\int_{f(a)}^{f(b)} f(z) dz", Integral(f(z), (z, f(a), f(b)))),
    (r"\int (x+a)", Integral(Add(x, a), x)),
    (r"\int a + b + c dx", Integral(Add(Add(a, b), c), x)),
    (r"\int \frac{dz}{z}", Integral(Pow(z, -1), z)),
    (r"\int \frac{3 dz}{z}", Integral(3 * Pow(z, -1), z)),
    (r"\int \frac{1}{x} dx", Integral(Pow(x, -1), x)),
    (
        r"\int \frac{1}{a} + \frac{1}{b} dx",
        Integral(Add(Pow(a, -1), Pow(b, -1)), x),
    ),
    (
        r"\int \frac{3 \cdot d\theta}{\theta}",
        Integral(3 * Pow(theta, -1), theta),
    ),
    (r"\int \frac{1}{x} + 1 dx", Integral(Add(Pow(x, -1), 1), x)),
    (r"x_0", Symbol("x_{0}")),
    (r"x_{1}", Symbol("x_{1}")),
    (r"x_a", Symbol("x_{a}")),
    (r"x_{b}", Symbol("x_{b}")),
    (r"h_\theta", Symbol("h_{theta}")),
    (r"h_{\theta}", Symbol("h_{theta}")),
    (
        r"h_{\theta}(x_0, x_1)",
        Function("h_{theta}")(Symbol("x_{0}"), Symbol("x_{1}")),
    ),
    (r"x!", factorial(x)),
    (r"100!", factorial(100)),
    (r"\theta!", factorial(theta)),
    (r"(x + 1)!", factorial(Add(x, 1))),
    (r"(x!)!", factorial(factorial(x))),
    (r"x!!!", factorial(factorial(factorial(x)))),
    (r"5!7!", Mul(factorial(5), factorial(7))),
    (r"\sqrt{x}", sqrt(x)),
    (r"\sqrt{x + b}", sqrt(Add(x, b))),
    (r"\sqrt[3]{\sin x}", root(sin(x), 3)),
    (r"\sqrt[y]{\sin x}", root(sin(x), y)),
    (r"\sqrt[\theta]{\sin x}", root(sin(x), theta)),
    (r"\sqrt{\frac{12}{6}}", sqrt(Mul(12, Pow(6, -1)))),
    (r"\overline{z}", conjugate(z)),
    (r"\overline{\overline{z}}", conjugate(conjugate(z))),
    (r"\overline{x + y}", conjugate(Add(x, y))),
    (r"\overline{x} + \overline{y}", conjugate(x) + conjugate(y)),
    (r"x < y", StrictLessThan(x, y)),
    (r"x \leq y", LessThan(x, y)),
    (r"x > y", StrictGreaterThan(x, y)),
    (r"x \geq y", GreaterThan(x, y)),
    (r"\mathit{x}", Symbol("x")),
    (r"\mathit{test}", Symbol("test")),
    (r"\mathit{TEST}", Symbol("TEST")),
    (r"\mathit{HELLO world}", Symbol("HELLO world")),
    (r"\sum_{k = 1}^{3} c", Sum(c, (k, 1, 3))),
    (r"\sum_{k = 1}^3 c", Sum(c, (k, 1, 3))),
    (r"\sum^{3}_{k = 1} c", Sum(c, (k, 1, 3))),
    (r"\sum^3_{k = 1} c", Sum(c, (k, 1, 3))),
    (r"\sum_{k = 1}^{10} k^2", Sum(k ** 2, (k, 1, 10))),
    (
        r"\sum_{n = 0}^{\infty} \frac{1}{n!}",
        Sum(Pow(factorial(n), -1), (n, 0, oo)),
    ),
    (r"\prod_{a = b}^{c} x", Product(x, (a, b, c))),
    (r"\prod_{a = b}^c x", Product(x, (a, b, c))),
    (r"\prod^{c}_{a = b} x", Product(x, (a, b, c))),
    (r"\prod^c_{a = b} x", Product(x, (a, b, c))),
    (r"\exp x", exp(x)),
    (r"\exp(x)", exp(x)),
    (r"\ln x", log(x, E)),
    (r"\ln xy", log(x * y, E)),
    (r"\log x", log(x, 10)),
    (r"\log xy", log(x * y, 10)),
    (r"\log_{2} x", log(x, 2)),
    (r"\log_{a} x", log(x, a)),
    (r"\log_{11} x", log(x, 11)),
    (r"\log_{a^2} x", log(x, Pow(a, 2))),
    (r"[x]", x),
    (r"[a + b]", Add(a, b)),
    (r"\frac{d}{dx} [ \tan x ]", Derivative(tan(x), x)),
    (r"\binom{n}{k}", binomial(n, k)),
    (r"\tbinom{n}{k}", binomial(n, k)),
    (r"\dbinom{n}{k}", binomial(n, k)),
    (r"\binom{n}{0}", binomial(n, 0)),
    (r"a \, b", Mul(a, b)),
    (r"a \thinspace b", Mul(a, b)),
    (r"a \: b", Mul(a, b)),
    (r"a \medspace b", Mul(a, b)),
    (r"a \; b", Mul(a, b)),
    (r"a \thickspace b", Mul(a, b)),
    (r"a \quad b", Mul(a, b)),
    (r"a \qquad b", Mul(a, b)),
    (r"a \! b", Mul(a, b)),
    (r"a \negthinspace b", Mul(a, b)),
    (r"a \negmedspace b", Mul(a, b)),
    (r"a \negthickspace b", Mul(a, b)),
    (r"\int x \, dx", Integral(x, x)),
    (r"\log_2 x", log(x, 2)),
    (r"\log_a x", log(x, a)),
    (r"\big(x + 1\big)^2", Add(x, 1) ** 2),
]
