from .sympy_imports import *
import pytest

invalid = [
    (r"(", None),
    (r")", None),
    (r"\frac{d}{dx}", None),
    (r"(\frac{d}{dx})", None),
    (r"\sqrt{}", None),
    (r"\sqrt", None),
    (r"\overline{}", None),
    (r"\overline", None),
    (r"{", None),
    (r"}", None),
    (r"\mathit{x + y}", None),
    (r"\mathit{21}", None),
    (r"\frac{2}{}", None),
    (r"\frac{}{2}", None),
    (r"\int", None),
    (r"!", None),
    (r"!0", None),
    (r"_", None),
    (r"^", None),
    (r"|", None),
    (r"||x|", None),
    (r"()", None),
    (r"((((((((((((((((()))))))))))))))))", None),
    (r"-", None),
    (r"\frac{d}{dx} + \frac{d}{dt}", None),
    (r"f(x,,y)", None),
    (r"f(x,y,", None),
    (r"\sin^x", None),
    (r"\cos^2", None),
    (r"@", None),
    (r"#", None),
    (r"$", None),
    (r"%", None),
    (r"&", None),
    (r"*", None),
    (r"" "\\", None),
    (r"~", None),
    (r"\frac{(2 + x}{1 - x)}", None),
    (r"\cos 1 \cos", None),
    (r"f(,", None),
    (r"f()", None),
    (r"a \div \div b", None),
    (r"a \cdot \cdot b", None),
    (r"a // b", None),
    (r"a +", None),
    (r"1 +", None),
    (r"a / b /", None),
    pytest.param(
        r"1.1.1", None, marks=pytest.mark.xfail()
    ),  # known issue: evaluates to 1.1 * 0.1
]
