# encoding: utf-8

# *** GENERATED BY `setup.py antlr`, DO NOT EDIT BY HAND ***
#
# Generated from ../LaTeX.g4, derived from sympy and latex2sympy
#     latex2sympy is licensed under the MIT license
#     https://github.com/augustt198/latex2sympy/blob/master/LICENSE.txt
#
#     sympy is licensed under the BSD license
#     https://github.com/sympy/sympy/blob/master/LICENSE
#
# Generated with antlr4
#    antlr4 is licensed under the BSD-3-Clause License
#    https://github.com/antlr/antlr4/blob/master/LICENSE.txt

from antlr4 import *
from io import StringIO
from typing.io import TextIO
import sys


def serializedATN():
    with StringIO() as buf:
        buf.write("\3\u608b\ua72a\u8133\ub9ed\u417c\u3be7\u7786\u5964\2[")
        buf.write("\u03ab\b\1\4\2\t\2\4\3\t\3\4\4\t\4\4\5\t\5\4\6\t\6\4\7")
        buf.write("\t\7\4\b\t\b\4\t\t\t\4\n\t\n\4\13\t\13\4\f\t\f\4\r\t\r")
        buf.write("\4\16\t\16\4\17\t\17\4\20\t\20\4\21\t\21\4\22\t\22\4\23")
        buf.write("\t\23\4\24\t\24\4\25\t\25\4\26\t\26\4\27\t\27\4\30\t\30")
        buf.write("\4\31\t\31\4\32\t\32\4\33\t\33\4\34\t\34\4\35\t\35\4\36")
        buf.write('\t\36\4\37\t\37\4 \t \4!\t!\4"\t"\4#\t#\4$\t$\4%\t%')
        buf.write("\4&\t&\4'\t'\4(\t(\4)\t)\4*\t*\4+\t+\4,\t,\4-\t-\4.")
        buf.write("\t.\4/\t/\4\60\t\60\4\61\t\61\4\62\t\62\4\63\t\63\4\64")
        buf.write("\t\64\4\65\t\65\4\66\t\66\4\67\t\67\48\t8\49\t9\4:\t:")
        buf.write("\4;\t;\4<\t<\4=\t=\4>\t>\4?\t?\4@\t@\4A\tA\4B\tB\4C\t")
        buf.write("C\4D\tD\4E\tE\4F\tF\4G\tG\4H\tH\4I\tI\4J\tJ\4K\tK\4L\t")
        buf.write("L\4M\tM\4N\tN\4O\tO\4P\tP\4Q\tQ\4R\tR\4S\tS\4T\tT\4U\t")
        buf.write("U\4V\tV\4W\tW\4X\tX\4Y\tY\4Z\tZ\4[\t[\4\\\t\\\3\2\6\2")
        buf.write("\u00bb\n\2\r\2\16\2\u00bc\3\2\3\2\3\3\3\3\3\3\3\3\3\3")
        buf.write("\3\3\3\3\3\3\3\3\3\3\3\3\3\3\5\3\u00cd\n\3\3\3\3\3\3\4")
        buf.write("\3\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\5\4\u00dc\n\4")
        buf.write("\3\4\3\4\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3")
        buf.write("\5\3\5\5\5\u00ed\n\5\3\5\3\5\3\6\3\6\3\6\3\6\3\6\3\6\3")
        buf.write("\6\3\6\3\7\3\7\3\7\3\7\3\7\3\7\3\7\3\7\3\7\3\b\3\b\3\b")
        buf.write("\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b\5\b\u0111")
        buf.write("\n\b\3\b\3\b\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3")
        buf.write("\t\3\t\3\t\3\t\3\t\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n")
        buf.write("\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\13\3\13\3\13\3\13\3")
        buf.write("\13\3\13\3\13\3\13\3\f\3\f\3\f\3\f\3\f\3\f\3\f\3\f\3\f")
        buf.write("\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3")
        buf.write("\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r")
        buf.write("\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3")
        buf.write("\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r")
        buf.write("\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3")
        buf.write("\r\3\r\5\r\u018b\n\r\3\r\3\r\3\16\3\16\3\17\3\17\3\20")
        buf.write("\3\20\3\21\3\21\3\22\3\22\3\23\3\23\3\24\3\24\3\25\3\25")
        buf.write("\3\26\3\26\3\26\3\27\3\27\3\27\3\30\3\30\3\31\3\31\3\32")
        buf.write("\3\32\3\33\3\33\3\34\3\34\3\35\3\35\3\35\3\35\3\35\3\35")
        buf.write("\3\35\3\35\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\37\3\37")
        buf.write("\3\37\3\37\3\37\3\37\3\37\3\37\3 \3 \3 \3 \3 \3 \3 \3")
        buf.write(' \3!\3!\3!\3!\3!\3"\3"\3"\3"\3"\3"\3"\3"\3"\3')
        buf.write('"\3"\3"\3"\3"\3"\3"\3"\3"\3"\3"\3"\3"\3"')
        buf.write('\3"\3"\3"\3"\3"\3"\3"\3"\3"\3"\3"\3"\3"\3')
        buf.write('"\3"\3"\3"\3"\3"\3"\3"\3"\3"\3"\3"\3"\3"')
        buf.write('\3"\3"\3"\3"\3"\5"\u020a\n"\3#\3#\3#\3#\3#\3$\3')
        buf.write("$\3$\3$\3$\3%\3%\3%\3%\3%\3%\3&\3&\3&\3&\3&\3'\3'\3")
        buf.write("'\3'\3'\3(\3(\3(\3(\3)\3)\3)\3)\3)\3*\3*\3*\3*\3*\3")
        buf.write("+\3+\3+\3+\3+\3,\3,\3,\3,\3,\3-\3-\3-\3-\3-\3.\3.\3.\3")
        buf.write(".\3.\3/\3/\3/\3/\3/\3/\3/\3/\3\60\3\60\3\60\3\60\3\60")
        buf.write("\3\60\3\60\3\60\3\61\3\61\3\61\3\61\3\61\3\61\3\61\3\61")
        buf.write("\3\62\3\62\3\62\3\62\3\62\3\62\3\62\3\62\3\63\3\63\3\63")
        buf.write("\3\63\3\63\3\63\3\63\3\63\3\64\3\64\3\64\3\64\3\64\3\64")
        buf.write("\3\64\3\64\3\65\3\65\3\65\3\65\3\65\3\65\3\66\3\66\3\66")
        buf.write("\3\66\3\66\3\66\3\67\3\67\3\67\3\67\3\67\3\67\38\38\3")
        buf.write("8\38\38\38\38\38\39\39\39\39\39\39\39\39\3:\3:\3:\3:\3")
        buf.write(":\3:\3:\3:\3;\3;\3;\3;\3;\3;\3;\3;\3<\3<\3<\3<\3<\3<\3")
        buf.write("<\3<\3=\3=\3=\3=\3=\3=\3=\3>\3>\3>\3>\3>\3>\3>\3?\3?\3")
        buf.write("?\3?\3?\3?\3@\3@\3@\3@\3@\3@\3@\3@\3@\3@\3A\3A\3A\3A\3")
        buf.write("A\3A\3A\3B\3B\3B\3B\3B\3B\3C\3C\3C\3C\3C\3D\3D\3D\3D\3")
        buf.write("D\3D\3E\3E\3E\3E\3E\3E\3E\3F\3F\3F\3F\3F\3F\3F\3F\3G\3")
        buf.write("G\3G\3G\3G\3G\3G\3G\3H\3H\3H\3H\3H\3H\3H\3H\3I\3I\3J\3")
        buf.write("J\3K\3K\3L\3L\3M\3M\3M\3M\5M\u0313\nM\3M\7M\u0316\nM\f")
        buf.write("M\16M\u0319\13M\3M\3M\3M\6M\u031e\nM\rM\16M\u031f\5M\u0322")
        buf.write("\nM\3N\3N\3O\3O\3P\6P\u0329\nP\rP\16P\u032a\3P\3P\3P\3")
        buf.write("P\3P\7P\u0332\nP\fP\16P\u0335\13P\3P\7P\u0338\nP\fP\16")
        buf.write("P\u033b\13P\3P\3P\3P\3P\3P\7P\u0342\nP\fP\16P\u0345\13")
        buf.write("P\3P\3P\6P\u0349\nP\rP\16P\u034a\5P\u034d\nP\3Q\3Q\7Q")
        buf.write("\u0351\nQ\fQ\16Q\u0354\13Q\5Q\u0356\nQ\3Q\3Q\3Q\7Q\u035b")
        buf.write("\nQ\fQ\16Q\u035e\13Q\3Q\5Q\u0361\nQ\5Q\u0363\nQ\3R\3R")
        buf.write("\3R\3R\3R\3S\3S\3T\3T\3T\3T\3T\3T\3T\3T\3T\5T\u0375\n")
        buf.write("T\3U\3U\3U\3U\3U\3U\3V\3V\3V\3V\3V\3V\3V\3V\3V\3V\3W\3")
        buf.write("W\3X\3X\3X\3X\3X\3X\3X\3X\3X\5X\u0392\nX\3Y\3Y\3Y\3Y\3")
        buf.write("Y\3Y\3Z\3Z\3Z\3Z\3Z\3Z\3Z\3Z\3Z\3Z\3[\3[\3\\\3\\\6\\\u03a8")
        buf.write("\n\\\r\\\16\\\u03a9\5\u0317\u0352\u035c\2]\3\3\5\4\7\5")
        buf.write("\t\6\13\7\r\b\17\t\21\n\23\13\25\f\27\r\31\16\33\17\35")
        buf.write("\20\37\21!\22#\23%\24'\25)\26+\27-\30/\31\61\32\63\33")
        buf.write("\65\34\67\359\36;\37= ?!A\"C#E$G%I&K'M(O)Q*S+U,W-Y.[")
        buf.write("/]\60_\61a\62c\63e\64g\65i\66k\67m8o9q:s;u<w=y>{?}@\177")
        buf.write("A\u0081B\u0083C\u0085D\u0087E\u0089F\u008bG\u008dH\u008f")
        buf.write("I\u0091J\u0093K\u0095L\u0097\2\u0099M\u009bN\u009d\2\u009f")
        buf.write("O\u00a1P\u00a3Q\u00a5R\u00a7S\u00a9T\u00abU\u00adV\u00af")
        buf.write('W\u00b1X\u00b3Y\u00b5Z\u00b7[\3\2\5\5\2\13\f\17\17""')
        buf.write("\4\2C\\c|\3\2\62;\2\u03d7\2\3\3\2\2\2\2\5\3\2\2\2\2\7")
        buf.write("\3\2\2\2\2\t\3\2\2\2\2\13\3\2\2\2\2\r\3\2\2\2\2\17\3\2")
        buf.write("\2\2\2\21\3\2\2\2\2\23\3\2\2\2\2\25\3\2\2\2\2\27\3\2\2")
        buf.write("\2\2\31\3\2\2\2\2\33\3\2\2\2\2\35\3\2\2\2\2\37\3\2\2\2")
        buf.write("\2!\3\2\2\2\2#\3\2\2\2\2%\3\2\2\2\2'\3\2\2\2\2)\3\2\2")
        buf.write("\2\2+\3\2\2\2\2-\3\2\2\2\2/\3\2\2\2\2\61\3\2\2\2\2\63")
        buf.write("\3\2\2\2\2\65\3\2\2\2\2\67\3\2\2\2\29\3\2\2\2\2;\3\2\2")
        buf.write("\2\2=\3\2\2\2\2?\3\2\2\2\2A\3\2\2\2\2C\3\2\2\2\2E\3\2")
        buf.write("\2\2\2G\3\2\2\2\2I\3\2\2\2\2K\3\2\2\2\2M\3\2\2\2\2O\3")
        buf.write("\2\2\2\2Q\3\2\2\2\2S\3\2\2\2\2U\3\2\2\2\2W\3\2\2\2\2Y")
        buf.write("\3\2\2\2\2[\3\2\2\2\2]\3\2\2\2\2_\3\2\2\2\2a\3\2\2\2\2")
        buf.write("c\3\2\2\2\2e\3\2\2\2\2g\3\2\2\2\2i\3\2\2\2\2k\3\2\2\2")
        buf.write("\2m\3\2\2\2\2o\3\2\2\2\2q\3\2\2\2\2s\3\2\2\2\2u\3\2\2")
        buf.write("\2\2w\3\2\2\2\2y\3\2\2\2\2{\3\2\2\2\2}\3\2\2\2\2\177\3")
        buf.write("\2\2\2\2\u0081\3\2\2\2\2\u0083\3\2\2\2\2\u0085\3\2\2\2")
        buf.write("\2\u0087\3\2\2\2\2\u0089\3\2\2\2\2\u008b\3\2\2\2\2\u008d")
        buf.write("\3\2\2\2\2\u008f\3\2\2\2\2\u0091\3\2\2\2\2\u0093\3\2\2")
        buf.write("\2\2\u0095\3\2\2\2\2\u0099\3\2\2\2\2\u009b\3\2\2\2\2\u009f")
        buf.write("\3\2\2\2\2\u00a1\3\2\2\2\2\u00a3\3\2\2\2\2\u00a5\3\2\2")
        buf.write("\2\2\u00a7\3\2\2\2\2\u00a9\3\2\2\2\2\u00ab\3\2\2\2\2\u00ad")
        buf.write("\3\2\2\2\2\u00af\3\2\2\2\2\u00b1\3\2\2\2\2\u00b3\3\2\2")
        buf.write("\2\2\u00b5\3\2\2\2\2\u00b7\3\2\2\2\3\u00ba\3\2\2\2\5\u00cc")
        buf.write("\3\2\2\2\7\u00db\3\2\2\2\t\u00ec\3\2\2\2\13\u00f0\3\2")
        buf.write("\2\2\r\u00f8\3\2\2\2\17\u0110\3\2\2\2\21\u0114\3\2\2\2")
        buf.write("\23\u0123\3\2\2\2\25\u0134\3\2\2\2\27\u013c\3\2\2\2\31")
        buf.write("\u018a\3\2\2\2\33\u018e\3\2\2\2\35\u0190\3\2\2\2\37\u0192")
        buf.write("\3\2\2\2!\u0194\3\2\2\2#\u0196\3\2\2\2%\u0198\3\2\2\2")
        buf.write("'\u019a\3\2\2\2)\u019c\3\2\2\2+\u019e\3\2\2\2-\u01a1")
        buf.write("\3\2\2\2/\u01a4\3\2\2\2\61\u01a6\3\2\2\2\63\u01a8\3\2")
        buf.write("\2\2\65\u01aa\3\2\2\2\67\u01ac\3\2\2\29\u01ae\3\2\2\2")
        buf.write(";\u01b6\3\2\2\2=\u01bd\3\2\2\2?\u01c5\3\2\2\2A\u01cd\3")
        buf.write("\2\2\2C\u0209\3\2\2\2E\u020b\3\2\2\2G\u0210\3\2\2\2I\u0215")
        buf.write("\3\2\2\2K\u021b\3\2\2\2M\u0220\3\2\2\2O\u0225\3\2\2\2")
        buf.write("Q\u0229\3\2\2\2S\u022e\3\2\2\2U\u0233\3\2\2\2W\u0238\3")
        buf.write("\2\2\2Y\u023d\3\2\2\2[\u0242\3\2\2\2]\u0247\3\2\2\2_\u024f")
        buf.write("\3\2\2\2a\u0257\3\2\2\2c\u025f\3\2\2\2e\u0267\3\2\2\2")
        buf.write("g\u026f\3\2\2\2i\u0277\3\2\2\2k\u027d\3\2\2\2m\u0283\3")
        buf.write("\2\2\2o\u0289\3\2\2\2q\u0291\3\2\2\2s\u0299\3\2\2\2u\u02a1")
        buf.write("\3\2\2\2w\u02a9\3\2\2\2y\u02b1\3\2\2\2{\u02b8\3\2\2\2")
        buf.write("}\u02bf\3\2\2\2\177\u02c5\3\2\2\2\u0081\u02cf\3\2\2\2")
        buf.write("\u0083\u02d6\3\2\2\2\u0085\u02dc\3\2\2\2\u0087\u02e1\3")
        buf.write("\2\2\2\u0089\u02e7\3\2\2\2\u008b\u02ee\3\2\2\2\u008d\u02f6")
        buf.write("\3\2\2\2\u008f\u02fe\3\2\2\2\u0091\u0306\3\2\2\2\u0093")
        buf.write("\u0308\3\2\2\2\u0095\u030a\3\2\2\2\u0097\u030c\3\2\2\2")
        buf.write("\u0099\u0312\3\2\2\2\u009b\u0323\3\2\2\2\u009d\u0325\3")
        buf.write("\2\2\2\u009f\u034c\3\2\2\2\u00a1\u0362\3\2\2\2\u00a3\u0364")
        buf.write("\3\2\2\2\u00a5\u0369\3\2\2\2\u00a7\u0374\3\2\2\2\u00a9")
        buf.write("\u0376\3\2\2\2\u00ab\u037c\3\2\2\2\u00ad\u0386\3\2\2\2")
        buf.write("\u00af\u0391\3\2\2\2\u00b1\u0393\3\2\2\2\u00b3\u0399\3")
        buf.write("\2\2\2\u00b5\u03a3\3\2\2\2\u00b7\u03a5\3\2\2\2\u00b9\u00bb")
        buf.write("\t\2\2\2\u00ba\u00b9\3\2\2\2\u00bb\u00bc\3\2\2\2\u00bc")
        buf.write("\u00ba\3\2\2\2\u00bc\u00bd\3\2\2\2\u00bd\u00be\3\2\2\2")
        buf.write("\u00be\u00bf\b\2\2\2\u00bf\4\3\2\2\2\u00c0\u00c1\7^\2")
        buf.write("\2\u00c1\u00cd\7.\2\2\u00c2\u00c3\7^\2\2\u00c3\u00c4\7")
        buf.write("v\2\2\u00c4\u00c5\7j\2\2\u00c5\u00c6\7k\2\2\u00c6\u00c7")
        buf.write("\7p\2\2\u00c7\u00c8\7u\2\2\u00c8\u00c9\7r\2\2\u00c9\u00ca")
        buf.write("\7c\2\2\u00ca\u00cb\7e\2\2\u00cb\u00cd\7g\2\2\u00cc\u00c0")
        buf.write("\3\2\2\2\u00cc\u00c2\3\2\2\2\u00cd\u00ce\3\2\2\2\u00ce")
        buf.write("\u00cf\b\3\2\2\u00cf\6\3\2\2\2\u00d0\u00d1\7^\2\2\u00d1")
        buf.write("\u00dc\7<\2\2\u00d2\u00d3\7^\2\2\u00d3\u00d4\7o\2\2\u00d4")
        buf.write("\u00d5\7g\2\2\u00d5\u00d6\7f\2\2\u00d6\u00d7\7u\2\2\u00d7")
        buf.write("\u00d8\7r\2\2\u00d8\u00d9\7c\2\2\u00d9\u00da\7e\2\2\u00da")
        buf.write("\u00dc\7g\2\2\u00db\u00d0\3\2\2\2\u00db\u00d2\3\2\2\2")
        buf.write("\u00dc\u00dd\3\2\2\2\u00dd\u00de\b\4\2\2\u00de\b\3\2\2")
        buf.write("\2\u00df\u00e0\7^\2\2\u00e0\u00ed\7=\2\2\u00e1\u00e2\7")
        buf.write("^\2\2\u00e2\u00e3\7v\2\2\u00e3\u00e4\7j\2\2\u00e4\u00e5")
        buf.write("\7k\2\2\u00e5\u00e6\7e\2\2\u00e6\u00e7\7m\2\2\u00e7\u00e8")
        buf.write("\7u\2\2\u00e8\u00e9\7r\2\2\u00e9\u00ea\7c\2\2\u00ea\u00eb")
        buf.write("\7e\2\2\u00eb\u00ed\7g\2\2\u00ec\u00df\3\2\2\2\u00ec\u00e1")
        buf.write("\3\2\2\2\u00ed\u00ee\3\2\2\2\u00ee\u00ef\b\5\2\2\u00ef")
        buf.write("\n\3\2\2\2\u00f0\u00f1\7^\2\2\u00f1\u00f2\7s\2\2\u00f2")
        buf.write("\u00f3\7w\2\2\u00f3\u00f4\7c\2\2\u00f4\u00f5\7f\2\2\u00f5")
        buf.write("\u00f6\3\2\2\2\u00f6\u00f7\b\6\2\2\u00f7\f\3\2\2\2\u00f8")
        buf.write("\u00f9\7^\2\2\u00f9\u00fa\7s\2\2\u00fa\u00fb\7s\2\2\u00fb")
        buf.write("\u00fc\7w\2\2\u00fc\u00fd\7c\2\2\u00fd\u00fe\7f\2\2\u00fe")
        buf.write("\u00ff\3\2\2\2\u00ff\u0100\b\7\2\2\u0100\16\3\2\2\2\u0101")
        buf.write("\u0102\7^\2\2\u0102\u0111\7#\2\2\u0103\u0104\7^\2\2\u0104")
        buf.write("\u0105\7p\2\2\u0105\u0106\7g\2\2\u0106\u0107\7i\2\2\u0107")
        buf.write("\u0108\7v\2\2\u0108\u0109\7j\2\2\u0109\u010a\7k\2\2\u010a")
        buf.write("\u010b\7p\2\2\u010b\u010c\7u\2\2\u010c\u010d\7r\2\2\u010d")
        buf.write("\u010e\7c\2\2\u010e\u010f\7e\2\2\u010f\u0111\7g\2\2\u0110")
        buf.write("\u0101\3\2\2\2\u0110\u0103\3\2\2\2\u0111\u0112\3\2\2\2")
        buf.write("\u0112\u0113\b\b\2\2\u0113\20\3\2\2\2\u0114\u0115\7^\2")
        buf.write("\2\u0115\u0116\7p\2\2\u0116\u0117\7g\2\2\u0117\u0118\7")
        buf.write("i\2\2\u0118\u0119\7o\2\2\u0119\u011a\7g\2\2\u011a\u011b")
        buf.write("\7f\2\2\u011b\u011c\7u\2\2\u011c\u011d\7r\2\2\u011d\u011e")
        buf.write("\7c\2\2\u011e\u011f\7e\2\2\u011f\u0120\7g\2\2\u0120\u0121")
        buf.write("\3\2\2\2\u0121\u0122\b\t\2\2\u0122\22\3\2\2\2\u0123\u0124")
        buf.write("\7^\2\2\u0124\u0125\7p\2\2\u0125\u0126\7g\2\2\u0126\u0127")
        buf.write("\7i\2\2\u0127\u0128\7v\2\2\u0128\u0129\7j\2\2\u0129\u012a")
        buf.write("\7k\2\2\u012a\u012b\7e\2\2\u012b\u012c\7m\2\2\u012c\u012d")
        buf.write("\7u\2\2\u012d\u012e\7r\2\2\u012e\u012f\7c\2\2\u012f\u0130")
        buf.write("\7e\2\2\u0130\u0131\7g\2\2\u0131\u0132\3\2\2\2\u0132\u0133")
        buf.write("\b\n\2\2\u0133\24\3\2\2\2\u0134\u0135\7^\2\2\u0135\u0136")
        buf.write("\7n\2\2\u0136\u0137\7g\2\2\u0137\u0138\7h\2\2\u0138\u0139")
        buf.write("\7v\2\2\u0139\u013a\3\2\2\2\u013a\u013b\b\13\2\2\u013b")
        buf.write("\26\3\2\2\2\u013c\u013d\7^\2\2\u013d\u013e\7t\2\2\u013e")
        buf.write("\u013f\7k\2\2\u013f\u0140\7i\2\2\u0140\u0141\7j\2\2\u0141")
        buf.write("\u0142\7v\2\2\u0142\u0143\3\2\2\2\u0143\u0144\b\f\2\2")
        buf.write("\u0144\30\3\2\2\2\u0145\u0146\7^\2\2\u0146\u0147\7x\2")
        buf.write("\2\u0147\u0148\7t\2\2\u0148\u0149\7w\2\2\u0149\u014a\7")
        buf.write("n\2\2\u014a\u018b\7g\2\2\u014b\u014c\7^\2\2\u014c\u014d")
        buf.write("\7x\2\2\u014d\u014e\7e\2\2\u014e\u014f\7g\2\2\u014f\u0150")
        buf.write("\7p\2\2\u0150\u0151\7v\2\2\u0151\u0152\7g\2\2\u0152\u018b")
        buf.write("\7t\2\2\u0153\u0154\7^\2\2\u0154\u0155\7x\2\2\u0155\u0156")
        buf.write("\7d\2\2\u0156\u0157\7q\2\2\u0157\u018b\7z\2\2\u0158\u0159")
        buf.write("\7^\2\2\u0159\u015a\7x\2\2\u015a\u015b\7u\2\2\u015b\u015c")
        buf.write("\7m\2\2\u015c\u015d\7k\2\2\u015d\u018b\7r\2\2\u015e\u015f")
        buf.write("\7^\2\2\u015f\u0160\7x\2\2\u0160\u0161\7u\2\2\u0161\u0162")
        buf.write("\7r\2\2\u0162\u0163\7c\2\2\u0163\u0164\7e\2\2\u0164\u018b")
        buf.write("\7g\2\2\u0165\u0166\7^\2\2\u0166\u0167\7j\2\2\u0167\u0168")
        buf.write("\7h\2\2\u0168\u0169\7k\2\2\u0169\u018b\7n\2\2\u016a\u016b")
        buf.write("\7^\2\2\u016b\u018b\7,\2\2\u016c\u016d\7^\2\2\u016d\u018b")
        buf.write("\7/\2\2\u016e\u016f\7^\2\2\u016f\u018b\7\60\2\2\u0170")
        buf.write("\u0171\7^\2\2\u0171\u018b\7\61\2\2\u0172\u0173\7^\2\2")
        buf.write("\u0173\u018b\7$\2\2\u0174\u0175\7^\2\2\u0175\u018b\7*")
        buf.write("\2\2\u0176\u0177\7^\2\2\u0177\u018b\7?\2\2\u0178\u0179")
        buf.write("\7^\2\2\u0179\u017a\7d\2\2\u017a\u017b\7k\2\2\u017b\u018b")
        buf.write("\7i\2\2\u017c\u017d\7^\2\2\u017d\u017e\7d\2\2\u017e\u017f")
        buf.write("\7k\2\2\u017f\u0180\7i\2\2\u0180\u018b\7i\2\2\u0181\u0182")
        buf.write("\7^\2\2\u0182\u0183\7D\2\2\u0183\u0184\7k\2\2\u0184\u018b")
        buf.write("\7i\2\2\u0185\u0186\7^\2\2\u0186\u0187\7D\2\2\u0187\u0188")
        buf.write("\7k\2\2\u0188\u0189\7i\2\2\u0189\u018b\7i\2\2\u018a\u0145")
        buf.write("\3\2\2\2\u018a\u014b\3\2\2\2\u018a\u0153\3\2\2\2\u018a")
        buf.write("\u0158\3\2\2\2\u018a\u015e\3\2\2\2\u018a\u0165\3\2\2\2")
        buf.write("\u018a\u016a\3\2\2\2\u018a\u016c\3\2\2\2\u018a\u016e\3")
        buf.write("\2\2\2\u018a\u0170\3\2\2\2\u018a\u0172\3\2\2\2\u018a\u0174")
        buf.write("\3\2\2\2\u018a\u0176\3\2\2\2\u018a\u0178\3\2\2\2\u018a")
        buf.write("\u017c\3\2\2\2\u018a\u0181\3\2\2\2\u018a\u0185\3\2\2\2")
        buf.write("\u018b\u018c\3\2\2\2\u018c\u018d\b\r\2\2\u018d\32\3\2")
        buf.write("\2\2\u018e\u018f\7-\2\2\u018f\34\3\2\2\2\u0190\u0191\7")
        buf.write("/\2\2\u0191\36\3\2\2\2\u0192\u0193\7,\2\2\u0193 \3\2\2")
        buf.write('\2\u0194\u0195\7\61\2\2\u0195"\3\2\2\2\u0196\u0197\7')
        buf.write("*\2\2\u0197$\3\2\2\2\u0198\u0199\7+\2\2\u0199&\3\2\2\2")
        buf.write("\u019a\u019b\7}\2\2\u019b(\3\2\2\2\u019c\u019d\7\177\2")
        buf.write("\2\u019d*\3\2\2\2\u019e\u019f\7^\2\2\u019f\u01a0\7}\2")
        buf.write("\2\u01a0,\3\2\2\2\u01a1\u01a2\7^\2\2\u01a2\u01a3\7\177")
        buf.write("\2\2\u01a3.\3\2\2\2\u01a4\u01a5\7]\2\2\u01a5\60\3\2\2")
        buf.write("\2\u01a6\u01a7\7_\2\2\u01a7\62\3\2\2\2\u01a8\u01a9\7~")
        buf.write("\2\2\u01a9\64\3\2\2\2\u01aa\u01ab\7.\2\2\u01ab\66\3\2")
        buf.write("\2\2\u01ac\u01ad\7=\2\2\u01ad8\3\2\2\2\u01ae\u01af\7^")
        buf.write("\2\2\u01af\u01b0\7t\2\2\u01b0\u01b1\7k\2\2\u01b1\u01b2")
        buf.write("\7i\2\2\u01b2\u01b3\7j\2\2\u01b3\u01b4\7v\2\2\u01b4\u01b5")
        buf.write("\7~\2\2\u01b5:\3\2\2\2\u01b6\u01b7\7^\2\2\u01b7\u01b8")
        buf.write("\7n\2\2\u01b8\u01b9\7g\2\2\u01b9\u01ba\7h\2\2\u01ba\u01bb")
        buf.write("\7v\2\2\u01bb\u01bc\7~\2\2\u01bc<\3\2\2\2\u01bd\u01be")
        buf.write("\7^\2\2\u01be\u01bf\7n\2\2\u01bf\u01c0\7c\2\2\u01c0\u01c1")
        buf.write("\7p\2\2\u01c1\u01c2\7i\2\2\u01c2\u01c3\7n\2\2\u01c3\u01c4")
        buf.write("\7g\2\2\u01c4>\3\2\2\2\u01c5\u01c6\7^\2\2\u01c6\u01c7")
        buf.write("\7t\2\2\u01c7\u01c8\7c\2\2\u01c8\u01c9\7p\2\2\u01c9\u01ca")
        buf.write("\7i\2\2\u01ca\u01cb\7n\2\2\u01cb\u01cc\7g\2\2\u01cc@\3")
        buf.write("\2\2\2\u01cd\u01ce\7^\2\2\u01ce\u01cf\7n\2\2\u01cf\u01d0")
        buf.write("\7k\2\2\u01d0\u01d1\7o\2\2\u01d1B\3\2\2\2\u01d2\u01d3")
        buf.write("\7^\2\2\u01d3\u01d4\7v\2\2\u01d4\u020a\7q\2\2\u01d5\u01d6")
        buf.write("\7^\2\2\u01d6\u01d7\7t\2\2\u01d7\u01d8\7k\2\2\u01d8\u01d9")
        buf.write("\7i\2\2\u01d9\u01da\7j\2\2\u01da\u01db\7v\2\2\u01db\u01dc")
        buf.write("\7c\2\2\u01dc\u01dd\7t\2\2\u01dd\u01de\7t\2\2\u01de\u01df")
        buf.write("\7q\2\2\u01df\u020a\7y\2\2\u01e0\u01e1\7^\2\2\u01e1\u01e2")
        buf.write("\7T\2\2\u01e2\u01e3\7k\2\2\u01e3\u01e4\7i\2\2\u01e4\u01e5")
        buf.write("\7j\2\2\u01e5\u01e6\7v\2\2\u01e6\u01e7\7c\2\2\u01e7\u01e8")
        buf.write("\7t\2\2\u01e8\u01e9\7t\2\2\u01e9\u01ea\7q\2\2\u01ea\u020a")
        buf.write("\7y\2\2\u01eb\u01ec\7^\2\2\u01ec\u01ed\7n\2\2\u01ed\u01ee")
        buf.write("\7q\2\2\u01ee\u01ef\7p\2\2\u01ef\u01f0\7i\2\2\u01f0\u01f1")
        buf.write("\7t\2\2\u01f1\u01f2\7k\2\2\u01f2\u01f3\7i\2\2\u01f3\u01f4")
        buf.write("\7j\2\2\u01f4\u01f5\7v\2\2\u01f5\u01f6\7c\2\2\u01f6\u01f7")
        buf.write("\7t\2\2\u01f7\u01f8\7t\2\2\u01f8\u01f9\7q\2\2\u01f9\u020a")
        buf.write("\7y\2\2\u01fa\u01fb\7^\2\2\u01fb\u01fc\7N\2\2\u01fc\u01fd")
        buf.write("\7q\2\2\u01fd\u01fe\7p\2\2\u01fe\u01ff\7i\2\2\u01ff\u0200")
        buf.write("\7t\2\2\u0200\u0201\7k\2\2\u0201\u0202\7i\2\2\u0202\u0203")
        buf.write("\7j\2\2\u0203\u0204\7v\2\2\u0204\u0205\7c\2\2\u0205\u0206")
        buf.write("\7t\2\2\u0206\u0207\7t\2\2\u0207\u0208\7q\2\2\u0208\u020a")
        buf.write("\7y\2\2\u0209\u01d2\3\2\2\2\u0209\u01d5\3\2\2\2\u0209")
        buf.write("\u01e0\3\2\2\2\u0209\u01eb\3\2\2\2\u0209\u01fa\3\2\2\2")
        buf.write("\u020aD\3\2\2\2\u020b\u020c\7^\2\2\u020c\u020d\7k\2\2")
        buf.write("\u020d\u020e\7p\2\2\u020e\u020f\7v\2\2\u020fF\3\2\2\2")
        buf.write("\u0210\u0211\7^\2\2\u0211\u0212\7u\2\2\u0212\u0213\7w")
        buf.write("\2\2\u0213\u0214\7o\2\2\u0214H\3\2\2\2\u0215\u0216\7^")
        buf.write("\2\2\u0216\u0217\7r\2\2\u0217\u0218\7t\2\2\u0218\u0219")
        buf.write("\7q\2\2\u0219\u021a\7f\2\2\u021aJ\3\2\2\2\u021b\u021c")
        buf.write("\7^\2\2\u021c\u021d\7g\2\2\u021d\u021e\7z\2\2\u021e\u021f")
        buf.write("\7r\2\2\u021fL\3\2\2\2\u0220\u0221\7^\2\2\u0221\u0222")
        buf.write("\7n\2\2\u0222\u0223\7q\2\2\u0223\u0224\7i\2\2\u0224N\3")
        buf.write("\2\2\2\u0225\u0226\7^\2\2\u0226\u0227\7n\2\2\u0227\u0228")
        buf.write("\7p\2\2\u0228P\3\2\2\2\u0229\u022a\7^\2\2\u022a\u022b")
        buf.write("\7u\2\2\u022b\u022c\7k\2\2\u022c\u022d\7p\2\2\u022dR\3")
        buf.write("\2\2\2\u022e\u022f\7^\2\2\u022f\u0230\7e\2\2\u0230\u0231")
        buf.write("\7q\2\2\u0231\u0232\7u\2\2\u0232T\3\2\2\2\u0233\u0234")
        buf.write("\7^\2\2\u0234\u0235\7v\2\2\u0235\u0236\7c\2\2\u0236\u0237")
        buf.write("\7p\2\2\u0237V\3\2\2\2\u0238\u0239\7^\2\2\u0239\u023a")
        buf.write("\7e\2\2\u023a\u023b\7u\2\2\u023b\u023c\7e\2\2\u023cX\3")
        buf.write("\2\2\2\u023d\u023e\7^\2\2\u023e\u023f\7u\2\2\u023f\u0240")
        buf.write("\7g\2\2\u0240\u0241\7e\2\2\u0241Z\3\2\2\2\u0242\u0243")
        buf.write("\7^\2\2\u0243\u0244\7e\2\2\u0244\u0245\7q\2\2\u0245\u0246")
        buf.write("\7v\2\2\u0246\\\3\2\2\2\u0247\u0248\7^\2\2\u0248\u0249")
        buf.write("\7c\2\2\u0249\u024a\7t\2\2\u024a\u024b\7e\2\2\u024b\u024c")
        buf.write("\7u\2\2\u024c\u024d\7k\2\2\u024d\u024e\7p\2\2\u024e^\3")
        buf.write("\2\2\2\u024f\u0250\7^\2\2\u0250\u0251\7c\2\2\u0251\u0252")
        buf.write("\7t\2\2\u0252\u0253\7e\2\2\u0253\u0254\7e\2\2\u0254\u0255")
        buf.write("\7q\2\2\u0255\u0256\7u\2\2\u0256`\3\2\2\2\u0257\u0258")
        buf.write("\7^\2\2\u0258\u0259\7c\2\2\u0259\u025a\7t\2\2\u025a\u025b")
        buf.write("\7e\2\2\u025b\u025c\7v\2\2\u025c\u025d\7c\2\2\u025d\u025e")
        buf.write("\7p\2\2\u025eb\3\2\2\2\u025f\u0260\7^\2\2\u0260\u0261")
        buf.write("\7c\2\2\u0261\u0262\7t\2\2\u0262\u0263\7e\2\2\u0263\u0264")
        buf.write("\7e\2\2\u0264\u0265\7u\2\2\u0265\u0266\7e\2\2\u0266d\3")
        buf.write("\2\2\2\u0267\u0268\7^\2\2\u0268\u0269\7c\2\2\u0269\u026a")
        buf.write("\7t\2\2\u026a\u026b\7e\2\2\u026b\u026c\7u\2\2\u026c\u026d")
        buf.write("\7g\2\2\u026d\u026e\7e\2\2\u026ef\3\2\2\2\u026f\u0270")
        buf.write("\7^\2\2\u0270\u0271\7c\2\2\u0271\u0272\7t\2\2\u0272\u0273")
        buf.write("\7e\2\2\u0273\u0274\7e\2\2\u0274\u0275\7q\2\2\u0275\u0276")
        buf.write("\7v\2\2\u0276h\3\2\2\2\u0277\u0278\7^\2\2\u0278\u0279")
        buf.write("\7u\2\2\u0279\u027a\7k\2\2\u027a\u027b\7p\2\2\u027b\u027c")
        buf.write("\7j\2\2\u027cj\3\2\2\2\u027d\u027e\7^\2\2\u027e\u027f")
        buf.write("\7e\2\2\u027f\u0280\7q\2\2\u0280\u0281\7u\2\2\u0281\u0282")
        buf.write("\7j\2\2\u0282l\3\2\2\2\u0283\u0284\7^\2\2\u0284\u0285")
        buf.write("\7v\2\2\u0285\u0286\7c\2\2\u0286\u0287\7p\2\2\u0287\u0288")
        buf.write("\7j\2\2\u0288n\3\2\2\2\u0289\u028a\7^\2\2\u028a\u028b")
        buf.write("\7c\2\2\u028b\u028c\7t\2\2\u028c\u028d\7u\2\2\u028d\u028e")
        buf.write("\7k\2\2\u028e\u028f\7p\2\2\u028f\u0290\7j\2\2\u0290p\3")
        buf.write("\2\2\2\u0291\u0292\7^\2\2\u0292\u0293\7c\2\2\u0293\u0294")
        buf.write("\7t\2\2\u0294\u0295\7e\2\2\u0295\u0296\7q\2\2\u0296\u0297")
        buf.write("\7u\2\2\u0297\u0298\7j\2\2\u0298r\3\2\2\2\u0299\u029a")
        buf.write("\7^\2\2\u029a\u029b\7c\2\2\u029b\u029c\7t\2\2\u029c\u029d")
        buf.write("\7v\2\2\u029d\u029e\7c\2\2\u029e\u029f\7p\2\2\u029f\u02a0")
        buf.write("\7j\2\2\u02a0t\3\2\2\2\u02a1\u02a2\7^\2\2\u02a2\u02a3")
        buf.write("\7n\2\2\u02a3\u02a4\7h\2\2\u02a4\u02a5\7n\2\2\u02a5\u02a6")
        buf.write("\7q\2\2\u02a6\u02a7\7q\2\2\u02a7\u02a8\7t\2\2\u02a8v\3")
        buf.write("\2\2\2\u02a9\u02aa\7^\2\2\u02aa\u02ab\7t\2\2\u02ab\u02ac")
        buf.write("\7h\2\2\u02ac\u02ad\7n\2\2\u02ad\u02ae\7q\2\2\u02ae\u02af")
        buf.write("\7q\2\2\u02af\u02b0\7t\2\2\u02b0x\3\2\2\2\u02b1\u02b2")
        buf.write("\7^\2\2\u02b2\u02b3\7n\2\2\u02b3\u02b4\7e\2\2\u02b4\u02b5")
        buf.write("\7g\2\2\u02b5\u02b6\7k\2\2\u02b6\u02b7\7n\2\2\u02b7z\3")
        buf.write("\2\2\2\u02b8\u02b9\7^\2\2\u02b9\u02ba\7t\2\2\u02ba\u02bb")
        buf.write("\7e\2\2\u02bb\u02bc\7g\2\2\u02bc\u02bd\7k\2\2\u02bd\u02be")
        buf.write("\7n\2\2\u02be|\3\2\2\2\u02bf\u02c0\7^\2\2\u02c0\u02c1")
        buf.write("\7u\2\2\u02c1\u02c2\7s\2\2\u02c2\u02c3\7t\2\2\u02c3\u02c4")
        buf.write("\7v\2\2\u02c4~\3\2\2\2\u02c5\u02c6\7^\2\2\u02c6\u02c7")
        buf.write("\7q\2\2\u02c7\u02c8\7x\2\2\u02c8\u02c9\7g\2\2\u02c9\u02ca")
        buf.write("\7t\2\2\u02ca\u02cb\7n\2\2\u02cb\u02cc\7k\2\2\u02cc\u02cd")
        buf.write("\7p\2\2\u02cd\u02ce\7g\2\2\u02ce\u0080\3\2\2\2\u02cf\u02d0")
        buf.write("\7^\2\2\u02d0\u02d1\7v\2\2\u02d1\u02d2\7k\2\2\u02d2\u02d3")
        buf.write("\7o\2\2\u02d3\u02d4\7g\2\2\u02d4\u02d5\7u\2\2\u02d5\u0082")
        buf.write("\3\2\2\2\u02d6\u02d7\7^\2\2\u02d7\u02d8\7e\2\2\u02d8\u02d9")
        buf.write("\7f\2\2\u02d9\u02da\7q\2\2\u02da\u02db\7v\2\2\u02db\u0084")
        buf.write("\3\2\2\2\u02dc\u02dd\7^\2\2\u02dd\u02de\7f\2\2\u02de\u02df")
        buf.write("\7k\2\2\u02df\u02e0\7x\2\2\u02e0\u0086\3\2\2\2\u02e1\u02e2")
        buf.write("\7^\2\2\u02e2\u02e3\7h\2\2\u02e3\u02e4\7t\2\2\u02e4\u02e5")
        buf.write("\7c\2\2\u02e5\u02e6\7e\2\2\u02e6\u0088\3\2\2\2\u02e7\u02e8")
        buf.write("\7^\2\2\u02e8\u02e9\7d\2\2\u02e9\u02ea\7k\2\2\u02ea\u02eb")
        buf.write("\7p\2\2\u02eb\u02ec\7q\2\2\u02ec\u02ed\7o\2\2\u02ed\u008a")
        buf.write("\3\2\2\2\u02ee\u02ef\7^\2\2\u02ef\u02f0\7f\2\2\u02f0\u02f1")
        buf.write("\7d\2\2\u02f1\u02f2\7k\2\2\u02f2\u02f3\7p\2\2\u02f3\u02f4")
        buf.write("\7q\2\2\u02f4\u02f5\7o\2\2\u02f5\u008c\3\2\2\2\u02f6\u02f7")
        buf.write("\7^\2\2\u02f7\u02f8\7v\2\2\u02f8\u02f9\7d\2\2\u02f9\u02fa")
        buf.write("\7k\2\2\u02fa\u02fb\7p\2\2\u02fb\u02fc\7q\2\2\u02fc\u02fd")
        buf.write("\7o\2\2\u02fd\u008e\3\2\2\2\u02fe\u02ff\7^\2\2\u02ff\u0300")
        buf.write("\7o\2\2\u0300\u0301\7c\2\2\u0301\u0302\7v\2\2\u0302\u0303")
        buf.write("\7j\2\2\u0303\u0304\7k\2\2\u0304\u0305\7v\2\2\u0305\u0090")
        buf.write("\3\2\2\2\u0306\u0307\7a\2\2\u0307\u0092\3\2\2\2\u0308")
        buf.write("\u0309\7`\2\2\u0309\u0094\3\2\2\2\u030a\u030b\7<\2\2\u030b")
        buf.write("\u0096\3\2\2\2\u030c\u030d\t\2\2\2\u030d\u0098\3\2\2\2")
        buf.write("\u030e\u0313\7f\2\2\u030f\u0310\7^\2\2\u0310\u0311\7f")
        buf.write("\2\2\u0311\u0313\7f\2\2\u0312\u030e\3\2\2\2\u0312\u030f")
        buf.write("\3\2\2\2\u0313\u0317\3\2\2\2\u0314\u0316\5\u0097L\2\u0315")
        buf.write("\u0314\3\2\2\2\u0316\u0319\3\2\2\2\u0317\u0318\3\2\2\2")
        buf.write("\u0317\u0315\3\2\2\2\u0318\u0321\3\2\2\2\u0319\u0317\3")
        buf.write("\2\2\2\u031a\u0322\t\3\2\2\u031b\u031d\7^\2\2\u031c\u031e")
        buf.write("\t\3\2\2\u031d\u031c\3\2\2\2\u031e\u031f\3\2\2\2\u031f")
        buf.write("\u031d\3\2\2\2\u031f\u0320\3\2\2\2\u0320\u0322\3\2\2\2")
        buf.write("\u0321\u031a\3\2\2\2\u0321\u031b\3\2\2\2\u0322\u009a\3")
        buf.write("\2\2\2\u0323\u0324\t\3\2\2\u0324\u009c\3\2\2\2\u0325\u0326")
        buf.write("\t\4\2\2\u0326\u009e\3\2\2\2\u0327\u0329\5\u009dO\2\u0328")
        buf.write("\u0327\3\2\2\2\u0329\u032a\3\2\2\2\u032a\u0328\3\2\2\2")
        buf.write("\u032a\u032b\3\2\2\2\u032b\u0333\3\2\2\2\u032c\u032d\7")
        buf.write(".\2\2\u032d\u032e\5\u009dO\2\u032e\u032f\5\u009dO\2\u032f")
        buf.write("\u0330\5\u009dO\2\u0330\u0332\3\2\2\2\u0331\u032c\3\2")
        buf.write("\2\2\u0332\u0335\3\2\2\2\u0333\u0331\3\2\2\2\u0333\u0334")
        buf.write("\3\2\2\2\u0334\u034d\3\2\2\2\u0335\u0333\3\2\2\2\u0336")
        buf.write("\u0338\5\u009dO\2\u0337\u0336\3\2\2\2\u0338\u033b\3\2")
        buf.write("\2\2\u0339\u0337\3\2\2\2\u0339\u033a\3\2\2\2\u033a\u0343")
        buf.write("\3\2\2\2\u033b\u0339\3\2\2\2\u033c\u033d\7.\2\2\u033d")
        buf.write("\u033e\5\u009dO\2\u033e\u033f\5\u009dO\2\u033f\u0340\5")
        buf.write("\u009dO\2\u0340\u0342\3\2\2\2\u0341\u033c\3\2\2\2\u0342")
        buf.write("\u0345\3\2\2\2\u0343\u0341\3\2\2\2\u0343\u0344\3\2\2\2")
        buf.write("\u0344\u0346\3\2\2\2\u0345\u0343\3\2\2\2\u0346\u0348\7")
        buf.write("\60\2\2\u0347\u0349\5\u009dO\2\u0348\u0347\3\2\2\2\u0349")
        buf.write("\u034a\3\2\2\2\u034a\u0348\3\2\2\2\u034a\u034b\3\2\2\2")
        buf.write("\u034b\u034d\3\2\2\2\u034c\u0328\3\2\2\2\u034c\u0339\3")
        buf.write("\2\2\2\u034d\u00a0\3\2\2\2\u034e\u0352\7(\2\2\u034f\u0351")
        buf.write("\5\u0097L\2\u0350\u034f\3\2\2\2\u0351\u0354\3\2\2\2\u0352")
        buf.write("\u0353\3\2\2\2\u0352\u0350\3\2\2\2\u0353\u0356\3\2\2\2")
        buf.write("\u0354\u0352\3\2\2\2\u0355\u034e\3\2\2\2\u0355\u0356\3")
        buf.write("\2\2\2\u0356\u0357\3\2\2\2\u0357\u0363\7?\2\2\u0358\u0360")
        buf.write("\7?\2\2\u0359\u035b\5\u0097L\2\u035a\u0359\3\2\2\2\u035b")
        buf.write("\u035e\3\2\2\2\u035c\u035d\3\2\2\2\u035c\u035a\3\2\2\2")
        buf.write("\u035d\u035f\3\2\2\2\u035e\u035c\3\2\2\2\u035f\u0361\7")
        buf.write("(\2\2\u0360\u035c\3\2\2\2\u0360\u0361\3\2\2\2\u0361\u0363")
        buf.write("\3\2\2\2\u0362\u0355\3\2\2\2\u0362\u0358\3\2\2\2\u0363")
        buf.write("\u00a2\3\2\2\2\u0364\u0365\7^\2\2\u0365\u0366\7p\2\2\u0366")
        buf.write("\u0367\7g\2\2\u0367\u0368\7s\2\2\u0368\u00a4\3\2\2\2\u0369")
        buf.write("\u036a\7>\2\2\u036a\u00a6\3\2\2\2\u036b\u036c\7^\2\2\u036c")
        buf.write("\u036d\7n\2\2\u036d\u036e\7g\2\2\u036e\u0375\7s\2\2\u036f")
        buf.write("\u0370\7^\2\2\u0370\u0371\7n\2\2\u0371\u0375\7g\2\2\u0372")
        buf.write("\u0375\5\u00a9U\2\u0373\u0375\5\u00abV\2\u0374\u036b\3")
        buf.write("\2\2\2\u0374\u036f\3\2\2\2\u0374\u0372\3\2\2\2\u0374\u0373")
        buf.write("\3\2\2\2\u0375\u00a8\3\2\2\2\u0376\u0377\7^\2\2\u0377")
        buf.write("\u0378\7n\2\2\u0378\u0379\7g\2\2\u0379\u037a\7s\2\2\u037a")
        buf.write("\u037b\7s\2\2\u037b\u00aa\3\2\2\2\u037c\u037d\7^\2\2\u037d")
        buf.write("\u037e\7n\2\2\u037e\u037f\7g\2\2\u037f\u0380\7s\2\2\u0380")
        buf.write("\u0381\7u\2\2\u0381\u0382\7n\2\2\u0382\u0383\7c\2\2\u0383")
        buf.write("\u0384\7p\2\2\u0384\u0385\7v\2\2\u0385\u00ac\3\2\2\2\u0386")
        buf.write("\u0387\7@\2\2\u0387\u00ae\3\2\2\2\u0388\u0389\7^\2\2\u0389")
        buf.write("\u038a\7i\2\2\u038a\u038b\7g\2\2\u038b\u0392\7s\2\2\u038c")
        buf.write("\u038d\7^\2\2\u038d\u038e\7i\2\2\u038e\u0392\7g\2\2\u038f")
        buf.write("\u0392\5\u00b1Y\2\u0390\u0392\5\u00b3Z\2\u0391\u0388\3")
        buf.write("\2\2\2\u0391\u038c\3\2\2\2\u0391\u038f\3\2\2\2\u0391\u0390")
        buf.write("\3\2\2\2\u0392\u00b0\3\2\2\2\u0393\u0394\7^\2\2\u0394")
        buf.write("\u0395\7i\2\2\u0395\u0396\7g\2\2\u0396\u0397\7s\2\2\u0397")
        buf.write("\u0398\7s\2\2\u0398\u00b2\3\2\2\2\u0399\u039a\7^\2\2\u039a")
        buf.write("\u039b\7i\2\2\u039b\u039c\7g\2\2\u039c\u039d\7s\2\2\u039d")
        buf.write("\u039e\7u\2\2\u039e\u039f\7n\2\2\u039f\u03a0\7c\2\2\u03a0")
        buf.write("\u03a1\7p\2\2\u03a1\u03a2\7v\2\2\u03a2\u00b4\3\2\2\2\u03a3")
        buf.write("\u03a4\7#\2\2\u03a4\u00b6\3\2\2\2\u03a5\u03a7\7^\2\2\u03a6")
        buf.write("\u03a8\t\3\2\2\u03a7\u03a6\3\2\2\2\u03a8\u03a9\3\2\2\2")
        buf.write("\u03a9\u03a7\3\2\2\2\u03a9\u03aa\3\2\2\2\u03aa\u00b8\3")
        buf.write("\2\2\2\34\2\u00bc\u00cc\u00db\u00ec\u0110\u018a\u0209")
        buf.write("\u0312\u0317\u031f\u0321\u032a\u0333\u0339\u0343\u034a")
        buf.write("\u034c\u0352\u0355\u035c\u0360\u0362\u0374\u0391\u03a9")
        buf.write("\3\b\2\2")
        return buf.getvalue()


class LaTeXLexer(Lexer):

    atn = ATNDeserializer().deserialize(serializedATN())

    decisionsToDFA = [DFA(ds, i) for i, ds in enumerate(atn.decisionToState)]

    WS = 1
    THINSPACE = 2
    MEDSPACE = 3
    THICKSPACE = 4
    QUAD = 5
    QQUAD = 6
    NEGTHINSPACE = 7
    NEGMEDSPACE = 8
    NEGTHICKSPACE = 9
    CMD_LEFT = 10
    CMD_RIGHT = 11
    IGNORE = 12
    ADD = 13
    SUB = 14
    MUL = 15
    DIV = 16
    L_PAREN = 17
    R_PAREN = 18
    L_BRACE = 19
    R_BRACE = 20
    L_BRACE_LITERAL = 21
    R_BRACE_LITERAL = 22
    L_BRACKET = 23
    R_BRACKET = 24
    BAR = 25
    COMMA = 26
    SEMICOLON = 27
    R_BAR = 28
    L_BAR = 29
    L_ANGLE = 30
    R_ANGLE = 31
    FUNC_LIM = 32
    LIM_APPROACH_SYM = 33
    FUNC_INT = 34
    FUNC_SUM = 35
    FUNC_PROD = 36
    FUNC_EXP = 37
    FUNC_LOG = 38
    FUNC_LN = 39
    FUNC_SIN = 40
    FUNC_COS = 41
    FUNC_TAN = 42
    FUNC_CSC = 43
    FUNC_SEC = 44
    FUNC_COT = 45
    FUNC_ARCSIN = 46
    FUNC_ARCCOS = 47
    FUNC_ARCTAN = 48
    FUNC_ARCCSC = 49
    FUNC_ARCSEC = 50
    FUNC_ARCCOT = 51
    FUNC_SINH = 52
    FUNC_COSH = 53
    FUNC_TANH = 54
    FUNC_ARSINH = 55
    FUNC_ARCOSH = 56
    FUNC_ARTANH = 57
    L_FLOOR = 58
    R_FLOOR = 59
    L_CEIL = 60
    R_CEIL = 61
    FUNC_SQRT = 62
    FUNC_OVERLINE = 63
    CMD_TIMES = 64
    CMD_CDOT = 65
    CMD_DIV = 66
    CMD_FRAC = 67
    CMD_BINOM = 68
    CMD_DBINOM = 69
    CMD_TBINOM = 70
    CMD_MATHIT = 71
    UNDERSCORE = 72
    CARET = 73
    COLON = 74
    DIFFERENTIAL = 75
    LETTER = 76
    NUMBER = 77
    EQUAL = 78
    NEQ = 79
    LT = 80
    LTE = 81
    LTE_Q = 82
    LTE_S = 83
    GT = 84
    GTE = 85
    GTE_Q = 86
    GTE_S = 87
    BANG = 88
    SYMBOL = 89

    channelNames = [u"DEFAULT_TOKEN_CHANNEL", u"HIDDEN"]

    modeNames = ["DEFAULT_MODE"]

    literalNames = [
        "<INVALID>",
        "'\\quad'",
        "'\\qquad'",
        "'\\negmedspace'",
        "'\\negthickspace'",
        "'\\left'",
        "'\\right'",
        "'+'",
        "'-'",
        "'*'",
        "'/'",
        "'('",
        "')'",
        "'{'",
        "'}'",
        "'\\{'",
        "'\\}'",
        "'['",
        "']'",
        "'|'",
        "','",
        "';'",
        "'\\right|'",
        "'\\left|'",
        "'\\langle'",
        "'\\rangle'",
        "'\\lim'",
        "'\\int'",
        "'\\sum'",
        "'\\prod'",
        "'\\exp'",
        "'\\log'",
        "'\\ln'",
        "'\\sin'",
        "'\\cos'",
        "'\\tan'",
        "'\\csc'",
        "'\\sec'",
        "'\\cot'",
        "'\\arcsin'",
        "'\\arccos'",
        "'\\arctan'",
        "'\\arccsc'",
        "'\\arcsec'",
        "'\\arccot'",
        "'\\sinh'",
        "'\\cosh'",
        "'\\tanh'",
        "'\\arsinh'",
        "'\\arcosh'",
        "'\\artanh'",
        "'\\lfloor'",
        "'\\rfloor'",
        "'\\lceil'",
        "'\\rceil'",
        "'\\sqrt'",
        "'\\overline'",
        "'\\times'",
        "'\\cdot'",
        "'\\div'",
        "'\\frac'",
        "'\\binom'",
        "'\\dbinom'",
        "'\\tbinom'",
        "'\\mathit'",
        "'_'",
        "'^'",
        "':'",
        "'\\neq'",
        "'<'",
        "'\\leqq'",
        "'\\leqslant'",
        "'>'",
        "'\\geqq'",
        "'\\geqslant'",
        "'!'",
    ]

    symbolicNames = [
        "<INVALID>",
        "WS",
        "THINSPACE",
        "MEDSPACE",
        "THICKSPACE",
        "QUAD",
        "QQUAD",
        "NEGTHINSPACE",
        "NEGMEDSPACE",
        "NEGTHICKSPACE",
        "CMD_LEFT",
        "CMD_RIGHT",
        "IGNORE",
        "ADD",
        "SUB",
        "MUL",
        "DIV",
        "L_PAREN",
        "R_PAREN",
        "L_BRACE",
        "R_BRACE",
        "L_BRACE_LITERAL",
        "R_BRACE_LITERAL",
        "L_BRACKET",
        "R_BRACKET",
        "BAR",
        "COMMA",
        "SEMICOLON",
        "R_BAR",
        "L_BAR",
        "L_ANGLE",
        "R_ANGLE",
        "FUNC_LIM",
        "LIM_APPROACH_SYM",
        "FUNC_INT",
        "FUNC_SUM",
        "FUNC_PROD",
        "FUNC_EXP",
        "FUNC_LOG",
        "FUNC_LN",
        "FUNC_SIN",
        "FUNC_COS",
        "FUNC_TAN",
        "FUNC_CSC",
        "FUNC_SEC",
        "FUNC_COT",
        "FUNC_ARCSIN",
        "FUNC_ARCCOS",
        "FUNC_ARCTAN",
        "FUNC_ARCCSC",
        "FUNC_ARCSEC",
        "FUNC_ARCCOT",
        "FUNC_SINH",
        "FUNC_COSH",
        "FUNC_TANH",
        "FUNC_ARSINH",
        "FUNC_ARCOSH",
        "FUNC_ARTANH",
        "L_FLOOR",
        "R_FLOOR",
        "L_CEIL",
        "R_CEIL",
        "FUNC_SQRT",
        "FUNC_OVERLINE",
        "CMD_TIMES",
        "CMD_CDOT",
        "CMD_DIV",
        "CMD_FRAC",
        "CMD_BINOM",
        "CMD_DBINOM",
        "CMD_TBINOM",
        "CMD_MATHIT",
        "UNDERSCORE",
        "CARET",
        "COLON",
        "DIFFERENTIAL",
        "LETTER",
        "NUMBER",
        "EQUAL",
        "NEQ",
        "LT",
        "LTE",
        "LTE_Q",
        "LTE_S",
        "GT",
        "GTE",
        "GTE_Q",
        "GTE_S",
        "BANG",
        "SYMBOL",
    ]

    ruleNames = [
        "WS",
        "THINSPACE",
        "MEDSPACE",
        "THICKSPACE",
        "QUAD",
        "QQUAD",
        "NEGTHINSPACE",
        "NEGMEDSPACE",
        "NEGTHICKSPACE",
        "CMD_LEFT",
        "CMD_RIGHT",
        "IGNORE",
        "ADD",
        "SUB",
        "MUL",
        "DIV",
        "L_PAREN",
        "R_PAREN",
        "L_BRACE",
        "R_BRACE",
        "L_BRACE_LITERAL",
        "R_BRACE_LITERAL",
        "L_BRACKET",
        "R_BRACKET",
        "BAR",
        "COMMA",
        "SEMICOLON",
        "R_BAR",
        "L_BAR",
        "L_ANGLE",
        "R_ANGLE",
        "FUNC_LIM",
        "LIM_APPROACH_SYM",
        "FUNC_INT",
        "FUNC_SUM",
        "FUNC_PROD",
        "FUNC_EXP",
        "FUNC_LOG",
        "FUNC_LN",
        "FUNC_SIN",
        "FUNC_COS",
        "FUNC_TAN",
        "FUNC_CSC",
        "FUNC_SEC",
        "FUNC_COT",
        "FUNC_ARCSIN",
        "FUNC_ARCCOS",
        "FUNC_ARCTAN",
        "FUNC_ARCCSC",
        "FUNC_ARCSEC",
        "FUNC_ARCCOT",
        "FUNC_SINH",
        "FUNC_COSH",
        "FUNC_TANH",
        "FUNC_ARSINH",
        "FUNC_ARCOSH",
        "FUNC_ARTANH",
        "L_FLOOR",
        "R_FLOOR",
        "L_CEIL",
        "R_CEIL",
        "FUNC_SQRT",
        "FUNC_OVERLINE",
        "CMD_TIMES",
        "CMD_CDOT",
        "CMD_DIV",
        "CMD_FRAC",
        "CMD_BINOM",
        "CMD_DBINOM",
        "CMD_TBINOM",
        "CMD_MATHIT",
        "UNDERSCORE",
        "CARET",
        "COLON",
        "WS_CHAR",
        "DIFFERENTIAL",
        "LETTER",
        "DIGIT",
        "NUMBER",
        "EQUAL",
        "NEQ",
        "LT",
        "LTE",
        "LTE_Q",
        "LTE_S",
        "GT",
        "GTE",
        "GTE_Q",
        "GTE_S",
        "BANG",
        "SYMBOL",
    ]

    grammarFileName = "LaTeX.g4"

    def __init__(self, input=None, output: TextIO = sys.stdout):
        super().__init__(input, output)
        self.checkVersion("4.7.2")
        self._interp = LexerATNSimulator(
            self, self.atn, self.decisionsToDFA, PredictionContextCache()
        )
        self._actions = None
        self._predicates = None
