# encoding: utf-8

# *** GENERATED BY `setup.py antlr`, DO NOT EDIT BY HAND ***
#
# Generated from ../LaTeX.g4, derived from sympy and latex2sympy
#     latex2sympy is licensed under the MIT license
#     https://github.com/augustt198/latex2sympy/blob/master/LICENSE.txt
#
#     sympy is licensed under the BSD license
#     https://github.com/sympy/sympy/blob/master/LICENSE
#
# Generated with antlr4
#    antlr4 is licensed under the BSD-3-Clause License
#    https://github.com/antlr/antlr4/blob/master/LICENSE.txt
from __future__ import print_function
from antlr4 import *
from io import StringIO
import sys


def serializedATN():
    with StringIO() as buf:
        buf.write(u"\3\u608b\ua72a\u8133\ub9ed\u417c\u3be7\u7786\u5964\2")
        buf.write(u"[\u03b1\b\1\4\2\t\2\4\3\t\3\4\4\t\4\4\5\t\5\4\6\t\6\4")
        buf.write(u"\7\t\7\4\b\t\b\4\t\t\t\4\n\t\n\4\13\t\13\4\f\t\f\4\r")
        buf.write(u"\t\r\4\16\t\16\4\17\t\17\4\20\t\20\4\21\t\21\4\22\t\22")
        buf.write(u"\4\23\t\23\4\24\t\24\4\25\t\25\4\26\t\26\4\27\t\27\4")
        buf.write(u"\30\t\30\4\31\t\31\4\32\t\32\4\33\t\33\4\34\t\34\4\35")
        buf.write(u'\t\35\4\36\t\36\4\37\t\37\4 \t \4!\t!\4"\t"\4#\t#\4')
        buf.write(u"$\t$\4%\t%\4&\t&\4'\t'\4(\t(\4)\t)\4*\t*\4+\t+\4,\t")
        buf.write(u",\4-\t-\4.\t.\4/\t/\4\60\t\60\4\61\t\61\4\62\t\62\4\63")
        buf.write(u"\t\63\4\64\t\64\4\65\t\65\4\66\t\66\4\67\t\67\48\t8\4")
        buf.write(u"9\t9\4:\t:\4;\t;\4<\t<\4=\t=\4>\t>\4?\t?\4@\t@\4A\tA")
        buf.write(u"\4B\tB\4C\tC\4D\tD\4E\tE\4F\tF\4G\tG\4H\tH\4I\tI\4J\t")
        buf.write(u"J\4K\tK\4L\tL\4M\tM\4N\tN\4O\tO\4P\tP\4Q\tQ\4R\tR\4S")
        buf.write(u"\tS\4T\tT\4U\tU\4V\tV\4W\tW\4X\tX\4Y\tY\4Z\tZ\4[\t[\4")
        buf.write(u"\\\t\\\3\2\3\2\3\3\6\3\u00bd\n\3\r\3\16\3\u00be\3\3\3")
        buf.write(u"\3\3\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\5")
        buf.write(u"\4\u00cf\n\4\3\4\3\4\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5")
        buf.write(u"\3\5\3\5\3\5\5\5\u00de\n\5\3\5\3\5\3\6\3\6\3\6\3\6\3")
        buf.write(u"\6\3\6\3\6\3\6\3\6\3\6\3\6\3\6\3\6\5\6\u00ef\n\6\3\6")
        buf.write(u"\3\6\3\7\3\7\3\7\3\7\3\7\3\7\3\7\3\7\3\b\3\b\3\b\3\b")
        buf.write(u"\3\b\3\b\3\b\3\b\3\b\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t")
        buf.write(u"\3\t\3\t\3\t\3\t\3\t\3\t\3\t\5\t\u0113\n\t\3\t\3\t\3")
        buf.write(u"\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3")
        buf.write(u"\n\3\n\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3")
        buf.write(u"\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\f\3\f\3\f\3")
        buf.write(u"\f\3\f\3\f\3\f\3\f\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3")
        buf.write(u"\r\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16")
        buf.write(u"\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3")
        buf.write(u"\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16")
        buf.write(u"\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3")
        buf.write(u"\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16")
        buf.write(u"\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3")
        buf.write(u"\16\3\16\3\16\3\16\3\16\3\16\3\16\5\16\u018d\n\16\3\16")
        buf.write(u"\3\16\3\17\3\17\3\20\3\20\3\21\3\21\3\22\3\22\3\23\3")
        buf.write(u"\23\3\24\3\24\3\25\3\25\3\26\3\26\3\27\3\27\3\27\3\30")
        buf.write(u"\3\30\3\30\3\31\3\31\3\32\3\32\3\33\3\33\3\34\3\34\3")
        buf.write(u"\34\3\34\3\34\3\34\3\34\3\34\3\35\3\35\3\35\3\35\3\35")
        buf.write(u"\3\35\3\35\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3")
        buf.write(u"\37\3\37\3\37\3\37\3\37\3\37\3\37\3\37\3 \3 \3 \3 \3")
        buf.write(u" \3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!")
        buf.write(u"\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3")
        buf.write(u"!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!")
        buf.write(u'\3!\3!\3!\5!\u0208\n!\3"\3"\3"\3"\3"\3#\3#\3#\3')
        buf.write(u"#\3#\3$\3$\3$\3$\3$\3$\3%\3%\3%\3%\3%\3&\3&\3&\3&\3&")
        buf.write(u"\3'\3'\3'\3'\3(\3(\3(\3(\3(\3)\3)\3)\3)\3)\3*\3*")
        buf.write(u"\3*\3*\3*\3+\3+\3+\3+\3+\3,\3,\3,\3,\3,\3-\3-\3-\3-\3")
        buf.write(u"-\3.\3.\3.\3.\3.\3.\3.\3.\3/\3/\3/\3/\3/\3/\3/\3/\3\60")
        buf.write(u"\3\60\3\60\3\60\3\60\3\60\3\60\3\60\3\61\3\61\3\61\3")
        buf.write(u"\61\3\61\3\61\3\61\3\61\3\62\3\62\3\62\3\62\3\62\3\62")
        buf.write(u"\3\62\3\62\3\63\3\63\3\63\3\63\3\63\3\63\3\63\3\63\3")
        buf.write(u"\64\3\64\3\64\3\64\3\64\3\64\3\65\3\65\3\65\3\65\3\65")
        buf.write(u"\3\65\3\66\3\66\3\66\3\66\3\66\3\66\3\67\3\67\3\67\3")
        buf.write(u"\67\3\67\3\67\3\67\3\67\38\38\38\38\38\38\38\38\39\3")
        buf.write(u"9\39\39\39\39\39\39\3:\3:\3:\3:\3:\3:\3:\3:\3;\3;\3;")
        buf.write(u"\3;\3;\3;\3;\3;\3<\3<\3<\3<\3<\3<\3<\3<\3=\3=\3=\3=\3")
        buf.write(u"=\3=\3=\3>\3>\3>\3>\3>\3>\3>\3?\3?\3?\3?\3?\3?\3@\3@")
        buf.write(u"\3@\3@\3@\3@\3@\3@\3@\3@\3A\3A\3A\3A\3A\3A\3A\3B\3B\3")
        buf.write(u"B\3B\3B\3B\3C\3C\3C\3C\3C\3D\3D\3D\3D\3D\3D\3E\3E\3E")
        buf.write(u"\3E\3E\3E\3E\3F\3F\3F\3F\3F\3F\3F\3F\3G\3G\3G\3G\3G\3")
        buf.write(u"G\3G\3G\3H\3H\3H\3H\3H\3H\3H\3H\3I\3I\3J\3J\3K\3K\3L")
        buf.write(u"\3L\3M\3M\3M\3M\5M\u0319\nM\3M\7M\u031c\nM\fM\16M\u031f")
        buf.write(u"\13M\3M\3M\3M\6M\u0324\nM\rM\16M\u0325\5M\u0328\nM\3")
        buf.write(u"N\3N\3O\3O\3P\6P\u032f\nP\rP\16P\u0330\3P\3P\3P\3P\3")
        buf.write(u"P\7P\u0338\nP\fP\16P\u033b\13P\3P\7P\u033e\nP\fP\16P")
        buf.write(u"\u0341\13P\3P\3P\3P\3P\3P\7P\u0348\nP\fP\16P\u034b\13")
        buf.write(u"P\3P\3P\6P\u034f\nP\rP\16P\u0350\5P\u0353\nP\3Q\3Q\7")
        buf.write(u"Q\u0357\nQ\fQ\16Q\u035a\13Q\5Q\u035c\nQ\3Q\3Q\3Q\7Q\u0361")
        buf.write(u"\nQ\fQ\16Q\u0364\13Q\3Q\5Q\u0367\nQ\5Q\u0369\nQ\3R\3")
        buf.write(u"R\3R\3R\3R\3S\3S\3T\3T\3T\3T\3T\3T\3T\3T\3T\5T\u037b")
        buf.write(u"\nT\3U\3U\3U\3U\3U\3U\3V\3V\3V\3V\3V\3V\3V\3V\3V\3V\3")
        buf.write(u"W\3W\3X\3X\3X\3X\3X\3X\3X\3X\3X\5X\u0398\nX\3Y\3Y\3Y")
        buf.write(u"\3Y\3Y\3Y\3Z\3Z\3Z\3Z\3Z\3Z\3Z\3Z\3Z\3Z\3[\3[\3\\\3\\")
        buf.write(u"\6\\\u03ae\n\\\r\\\16\\\u03af\5\u031d\u0358\u0362\2]")
        buf.write(u"\3\3\5\4\7\5\t\6\13\7\r\b\17\t\21\n\23\13\25\f\27\r\31")
        buf.write(u"\16\33\17\35\20\37\21!\22#\23%\24'\25)\26+\27-\30/\31")
        buf.write(u"\61\32\63\33\65\34\67\359\36;\37= ?!A\"C#E$G%I&K'M(")
        buf.write(u"O)Q*S+U,W-Y.[/]\60_\61a\62c\63e\64g\65i\66k\67m8o9q:")
        buf.write(u"s;u<w=y>{?}@\177A\u0081B\u0083C\u0085D\u0087E\u0089F")
        buf.write(u"\u008bG\u008dH\u008fI\u0091J\u0093K\u0095L\u0097\2\u0099")
        buf.write(u"M\u009bN\u009d\2\u009fO\u00a1P\u00a3Q\u00a5R\u00a7S\u00a9")
        buf.write(u"T\u00abU\u00adV\u00afW\u00b1X\u00b3Y\u00b5Z\u00b7[\3")
        buf.write(u'\2\5\5\2\13\f\17\17""\4\2C\\c|\3\2\62;\2\u03dd\2\3')
        buf.write(u"\3\2\2\2\2\5\3\2\2\2\2\7\3\2\2\2\2\t\3\2\2\2\2\13\3\2")
        buf.write(u"\2\2\2\r\3\2\2\2\2\17\3\2\2\2\2\21\3\2\2\2\2\23\3\2\2")
        buf.write(u"\2\2\25\3\2\2\2\2\27\3\2\2\2\2\31\3\2\2\2\2\33\3\2\2")
        buf.write(u"\2\2\35\3\2\2\2\2\37\3\2\2\2\2!\3\2\2\2\2#\3\2\2\2\2")
        buf.write(u"%\3\2\2\2\2'\3\2\2\2\2)\3\2\2\2\2+\3\2\2\2\2-\3\2\2")
        buf.write(u"\2\2/\3\2\2\2\2\61\3\2\2\2\2\63\3\2\2\2\2\65\3\2\2\2")
        buf.write(u"\2\67\3\2\2\2\29\3\2\2\2\2;\3\2\2\2\2=\3\2\2\2\2?\3\2")
        buf.write(u"\2\2\2A\3\2\2\2\2C\3\2\2\2\2E\3\2\2\2\2G\3\2\2\2\2I\3")
        buf.write(u"\2\2\2\2K\3\2\2\2\2M\3\2\2\2\2O\3\2\2\2\2Q\3\2\2\2\2")
        buf.write(u"S\3\2\2\2\2U\3\2\2\2\2W\3\2\2\2\2Y\3\2\2\2\2[\3\2\2\2")
        buf.write(u"\2]\3\2\2\2\2_\3\2\2\2\2a\3\2\2\2\2c\3\2\2\2\2e\3\2\2")
        buf.write(u"\2\2g\3\2\2\2\2i\3\2\2\2\2k\3\2\2\2\2m\3\2\2\2\2o\3\2")
        buf.write(u"\2\2\2q\3\2\2\2\2s\3\2\2\2\2u\3\2\2\2\2w\3\2\2\2\2y\3")
        buf.write(u"\2\2\2\2{\3\2\2\2\2}\3\2\2\2\2\177\3\2\2\2\2\u0081\3")
        buf.write(u"\2\2\2\2\u0083\3\2\2\2\2\u0085\3\2\2\2\2\u0087\3\2\2")
        buf.write(u"\2\2\u0089\3\2\2\2\2\u008b\3\2\2\2\2\u008d\3\2\2\2\2")
        buf.write(u"\u008f\3\2\2\2\2\u0091\3\2\2\2\2\u0093\3\2\2\2\2\u0095")
        buf.write(u"\3\2\2\2\2\u0099\3\2\2\2\2\u009b\3\2\2\2\2\u009f\3\2")
        buf.write(u"\2\2\2\u00a1\3\2\2\2\2\u00a3\3\2\2\2\2\u00a5\3\2\2\2")
        buf.write(u"\2\u00a7\3\2\2\2\2\u00a9\3\2\2\2\2\u00ab\3\2\2\2\2\u00ad")
        buf.write(u"\3\2\2\2\2\u00af\3\2\2\2\2\u00b1\3\2\2\2\2\u00b3\3\2")
        buf.write(u"\2\2\2\u00b5\3\2\2\2\2\u00b7\3\2\2\2\3\u00b9\3\2\2\2")
        buf.write(u"\5\u00bc\3\2\2\2\7\u00ce\3\2\2\2\t\u00dd\3\2\2\2\13\u00ee")
        buf.write(u"\3\2\2\2\r\u00f2\3\2\2\2\17\u00fa\3\2\2\2\21\u0112\3")
        buf.write(u"\2\2\2\23\u0116\3\2\2\2\25\u0125\3\2\2\2\27\u0136\3\2")
        buf.write(u"\2\2\31\u013e\3\2\2\2\33\u018c\3\2\2\2\35\u0190\3\2\2")
        buf.write(u"\2\37\u0192\3\2\2\2!\u0194\3\2\2\2#\u0196\3\2\2\2%\u0198")
        buf.write(u"\3\2\2\2'\u019a\3\2\2\2)\u019c\3\2\2\2+\u019e\3\2\2")
        buf.write(u"\2-\u01a0\3\2\2\2/\u01a3\3\2\2\2\61\u01a6\3\2\2\2\63")
        buf.write(u"\u01a8\3\2\2\2\65\u01aa\3\2\2\2\67\u01ac\3\2\2\29\u01b4")
        buf.write(u"\3\2\2\2;\u01bb\3\2\2\2=\u01c3\3\2\2\2?\u01cb\3\2\2\2")
        buf.write(u"A\u0207\3\2\2\2C\u0209\3\2\2\2E\u020e\3\2\2\2G\u0213")
        buf.write(u"\3\2\2\2I\u0219\3\2\2\2K\u021e\3\2\2\2M\u0223\3\2\2\2")
        buf.write(u"O\u0227\3\2\2\2Q\u022c\3\2\2\2S\u0231\3\2\2\2U\u0236")
        buf.write(u"\3\2\2\2W\u023b\3\2\2\2Y\u0240\3\2\2\2[\u0245\3\2\2\2")
        buf.write(u"]\u024d\3\2\2\2_\u0255\3\2\2\2a\u025d\3\2\2\2c\u0265")
        buf.write(u"\3\2\2\2e\u026d\3\2\2\2g\u0275\3\2\2\2i\u027b\3\2\2\2")
        buf.write(u"k\u0281\3\2\2\2m\u0287\3\2\2\2o\u028f\3\2\2\2q\u0297")
        buf.write(u"\3\2\2\2s\u029f\3\2\2\2u\u02a7\3\2\2\2w\u02af\3\2\2\2")
        buf.write(u"y\u02b7\3\2\2\2{\u02be\3\2\2\2}\u02c5\3\2\2\2\177\u02cb")
        buf.write(u"\3\2\2\2\u0081\u02d5\3\2\2\2\u0083\u02dc\3\2\2\2\u0085")
        buf.write(u"\u02e2\3\2\2\2\u0087\u02e7\3\2\2\2\u0089\u02ed\3\2\2")
        buf.write(u"\2\u008b\u02f4\3\2\2\2\u008d\u02fc\3\2\2\2\u008f\u0304")
        buf.write(u"\3\2\2\2\u0091\u030c\3\2\2\2\u0093\u030e\3\2\2\2\u0095")
        buf.write(u"\u0310\3\2\2\2\u0097\u0312\3\2\2\2\u0099\u0318\3\2\2")
        buf.write(u"\2\u009b\u0329\3\2\2\2\u009d\u032b\3\2\2\2\u009f\u0352")
        buf.write(u"\3\2\2\2\u00a1\u0368\3\2\2\2\u00a3\u036a\3\2\2\2\u00a5")
        buf.write(u"\u036f\3\2\2\2\u00a7\u037a\3\2\2\2\u00a9\u037c\3\2\2")
        buf.write(u"\2\u00ab\u0382\3\2\2\2\u00ad\u038c\3\2\2\2\u00af\u0397")
        buf.write(u"\3\2\2\2\u00b1\u0399\3\2\2\2\u00b3\u039f\3\2\2\2\u00b5")
        buf.write(u"\u03a9\3\2\2\2\u00b7\u03ab\3\2\2\2\u00b9\u00ba\7.\2\2")
        buf.write(u"\u00ba\4\3\2\2\2\u00bb\u00bd\t\2\2\2\u00bc\u00bb\3\2")
        buf.write(u"\2\2\u00bd\u00be\3\2\2\2\u00be\u00bc\3\2\2\2\u00be\u00bf")
        buf.write(u"\3\2\2\2\u00bf\u00c0\3\2\2\2\u00c0\u00c1\b\3\2\2\u00c1")
        buf.write(u"\6\3\2\2\2\u00c2\u00c3\7^\2\2\u00c3\u00cf\7.\2\2\u00c4")
        buf.write(u"\u00c5\7^\2\2\u00c5\u00c6\7v\2\2\u00c6\u00c7\7j\2\2\u00c7")
        buf.write(u"\u00c8\7k\2\2\u00c8\u00c9\7p\2\2\u00c9\u00ca\7u\2\2\u00ca")
        buf.write(u"\u00cb\7r\2\2\u00cb\u00cc\7c\2\2\u00cc\u00cd\7e\2\2\u00cd")
        buf.write(u"\u00cf\7g\2\2\u00ce\u00c2\3\2\2\2\u00ce\u00c4\3\2\2\2")
        buf.write(u"\u00cf\u00d0\3\2\2\2\u00d0\u00d1\b\4\2\2\u00d1\b\3\2")
        buf.write(u"\2\2\u00d2\u00d3\7^\2\2\u00d3\u00de\7<\2\2\u00d4\u00d5")
        buf.write(u"\7^\2\2\u00d5\u00d6\7o\2\2\u00d6\u00d7\7g\2\2\u00d7\u00d8")
        buf.write(u"\7f\2\2\u00d8\u00d9\7u\2\2\u00d9\u00da\7r\2\2\u00da\u00db")
        buf.write(u"\7c\2\2\u00db\u00dc\7e\2\2\u00dc\u00de\7g\2\2\u00dd\u00d2")
        buf.write(u"\3\2\2\2\u00dd\u00d4\3\2\2\2\u00de\u00df\3\2\2\2\u00df")
        buf.write(u"\u00e0\b\5\2\2\u00e0\n\3\2\2\2\u00e1\u00e2\7^\2\2\u00e2")
        buf.write(u"\u00ef\7=\2\2\u00e3\u00e4\7^\2\2\u00e4\u00e5\7v\2\2\u00e5")
        buf.write(u"\u00e6\7j\2\2\u00e6\u00e7\7k\2\2\u00e7\u00e8\7e\2\2\u00e8")
        buf.write(u"\u00e9\7m\2\2\u00e9\u00ea\7u\2\2\u00ea\u00eb\7r\2\2\u00eb")
        buf.write(u"\u00ec\7c\2\2\u00ec\u00ed\7e\2\2\u00ed\u00ef\7g\2\2\u00ee")
        buf.write(u"\u00e1\3\2\2\2\u00ee\u00e3\3\2\2\2\u00ef\u00f0\3\2\2")
        buf.write(u"\2\u00f0\u00f1\b\6\2\2\u00f1\f\3\2\2\2\u00f2\u00f3\7")
        buf.write(u"^\2\2\u00f3\u00f4\7s\2\2\u00f4\u00f5\7w\2\2\u00f5\u00f6")
        buf.write(u"\7c\2\2\u00f6\u00f7\7f\2\2\u00f7\u00f8\3\2\2\2\u00f8")
        buf.write(u"\u00f9\b\7\2\2\u00f9\16\3\2\2\2\u00fa\u00fb\7^\2\2\u00fb")
        buf.write(u"\u00fc\7s\2\2\u00fc\u00fd\7s\2\2\u00fd\u00fe\7w\2\2\u00fe")
        buf.write(u"\u00ff\7c\2\2\u00ff\u0100\7f\2\2\u0100\u0101\3\2\2\2")
        buf.write(u"\u0101\u0102\b\b\2\2\u0102\20\3\2\2\2\u0103\u0104\7^")
        buf.write(u"\2\2\u0104\u0113\7#\2\2\u0105\u0106\7^\2\2\u0106\u0107")
        buf.write(u"\7p\2\2\u0107\u0108\7g\2\2\u0108\u0109\7i\2\2\u0109\u010a")
        buf.write(u"\7v\2\2\u010a\u010b\7j\2\2\u010b\u010c\7k\2\2\u010c\u010d")
        buf.write(u"\7p\2\2\u010d\u010e\7u\2\2\u010e\u010f\7r\2\2\u010f\u0110")
        buf.write(u"\7c\2\2\u0110\u0111\7e\2\2\u0111\u0113\7g\2\2\u0112\u0103")
        buf.write(u"\3\2\2\2\u0112\u0105\3\2\2\2\u0113\u0114\3\2\2\2\u0114")
        buf.write(u"\u0115\b\t\2\2\u0115\22\3\2\2\2\u0116\u0117\7^\2\2\u0117")
        buf.write(u"\u0118\7p\2\2\u0118\u0119\7g\2\2\u0119\u011a\7i\2\2\u011a")
        buf.write(u"\u011b\7o\2\2\u011b\u011c\7g\2\2\u011c\u011d\7f\2\2\u011d")
        buf.write(u"\u011e\7u\2\2\u011e\u011f\7r\2\2\u011f\u0120\7c\2\2\u0120")
        buf.write(u"\u0121\7e\2\2\u0121\u0122\7g\2\2\u0122\u0123\3\2\2\2")
        buf.write(u"\u0123\u0124\b\n\2\2\u0124\24\3\2\2\2\u0125\u0126\7^")
        buf.write(u"\2\2\u0126\u0127\7p\2\2\u0127\u0128\7g\2\2\u0128\u0129")
        buf.write(u"\7i\2\2\u0129\u012a\7v\2\2\u012a\u012b\7j\2\2\u012b\u012c")
        buf.write(u"\7k\2\2\u012c\u012d\7e\2\2\u012d\u012e\7m\2\2\u012e\u012f")
        buf.write(u"\7u\2\2\u012f\u0130\7r\2\2\u0130\u0131\7c\2\2\u0131\u0132")
        buf.write(u"\7e\2\2\u0132\u0133\7g\2\2\u0133\u0134\3\2\2\2\u0134")
        buf.write(u"\u0135\b\13\2\2\u0135\26\3\2\2\2\u0136\u0137\7^\2\2\u0137")
        buf.write(u"\u0138\7n\2\2\u0138\u0139\7g\2\2\u0139\u013a\7h\2\2\u013a")
        buf.write(u"\u013b\7v\2\2\u013b\u013c\3\2\2\2\u013c\u013d\b\f\2\2")
        buf.write(u"\u013d\30\3\2\2\2\u013e\u013f\7^\2\2\u013f\u0140\7t\2")
        buf.write(u"\2\u0140\u0141\7k\2\2\u0141\u0142\7i\2\2\u0142\u0143")
        buf.write(u"\7j\2\2\u0143\u0144\7v\2\2\u0144\u0145\3\2\2\2\u0145")
        buf.write(u"\u0146\b\r\2\2\u0146\32\3\2\2\2\u0147\u0148\7^\2\2\u0148")
        buf.write(u"\u0149\7x\2\2\u0149\u014a\7t\2\2\u014a\u014b\7w\2\2\u014b")
        buf.write(u"\u014c\7n\2\2\u014c\u018d\7g\2\2\u014d\u014e\7^\2\2\u014e")
        buf.write(u"\u014f\7x\2\2\u014f\u0150\7e\2\2\u0150\u0151\7g\2\2\u0151")
        buf.write(u"\u0152\7p\2\2\u0152\u0153\7v\2\2\u0153\u0154\7g\2\2\u0154")
        buf.write(u"\u018d\7t\2\2\u0155\u0156\7^\2\2\u0156\u0157\7x\2\2\u0157")
        buf.write(u"\u0158\7d\2\2\u0158\u0159\7q\2\2\u0159\u018d\7z\2\2\u015a")
        buf.write(u"\u015b\7^\2\2\u015b\u015c\7x\2\2\u015c\u015d\7u\2\2\u015d")
        buf.write(u"\u015e\7m\2\2\u015e\u015f\7k\2\2\u015f\u018d\7r\2\2\u0160")
        buf.write(u"\u0161\7^\2\2\u0161\u0162\7x\2\2\u0162\u0163\7u\2\2\u0163")
        buf.write(u"\u0164\7r\2\2\u0164\u0165\7c\2\2\u0165\u0166\7e\2\2\u0166")
        buf.write(u"\u018d\7g\2\2\u0167\u0168\7^\2\2\u0168\u0169\7j\2\2\u0169")
        buf.write(u"\u016a\7h\2\2\u016a\u016b\7k\2\2\u016b\u018d\7n\2\2\u016c")
        buf.write(u"\u016d\7^\2\2\u016d\u018d\7,\2\2\u016e\u016f\7^\2\2\u016f")
        buf.write(u"\u018d\7/\2\2\u0170\u0171\7^\2\2\u0171\u018d\7\60\2\2")
        buf.write(u"\u0172\u0173\7^\2\2\u0173\u018d\7\61\2\2\u0174\u0175")
        buf.write(u"\7^\2\2\u0175\u018d\7$\2\2\u0176\u0177\7^\2\2\u0177\u018d")
        buf.write(u"\7*\2\2\u0178\u0179\7^\2\2\u0179\u018d\7?\2\2\u017a\u017b")
        buf.write(u"\7^\2\2\u017b\u017c\7d\2\2\u017c\u017d\7k\2\2\u017d\u018d")
        buf.write(u"\7i\2\2\u017e\u017f\7^\2\2\u017f\u0180\7d\2\2\u0180\u0181")
        buf.write(u"\7k\2\2\u0181\u0182\7i\2\2\u0182\u018d\7i\2\2\u0183\u0184")
        buf.write(u"\7^\2\2\u0184\u0185\7D\2\2\u0185\u0186\7k\2\2\u0186\u018d")
        buf.write(u"\7i\2\2\u0187\u0188\7^\2\2\u0188\u0189\7D\2\2\u0189\u018a")
        buf.write(u"\7k\2\2\u018a\u018b\7i\2\2\u018b\u018d\7i\2\2\u018c\u0147")
        buf.write(u"\3\2\2\2\u018c\u014d\3\2\2\2\u018c\u0155\3\2\2\2\u018c")
        buf.write(u"\u015a\3\2\2\2\u018c\u0160\3\2\2\2\u018c\u0167\3\2\2")
        buf.write(u"\2\u018c\u016c\3\2\2\2\u018c\u016e\3\2\2\2\u018c\u0170")
        buf.write(u"\3\2\2\2\u018c\u0172\3\2\2\2\u018c\u0174\3\2\2\2\u018c")
        buf.write(u"\u0176\3\2\2\2\u018c\u0178\3\2\2\2\u018c\u017a\3\2\2")
        buf.write(u"\2\u018c\u017e\3\2\2\2\u018c\u0183\3\2\2\2\u018c\u0187")
        buf.write(u"\3\2\2\2\u018d\u018e\3\2\2\2\u018e\u018f\b\16\2\2\u018f")
        buf.write(u"\34\3\2\2\2\u0190\u0191\7-\2\2\u0191\36\3\2\2\2\u0192")
        buf.write(u"\u0193\7/\2\2\u0193 \3\2\2\2\u0194\u0195\7,\2\2\u0195")
        buf.write(u'"\3\2\2\2\u0196\u0197\7\61\2\2\u0197$\3\2\2\2\u0198')
        buf.write(u"\u0199\7*\2\2\u0199&\3\2\2\2\u019a\u019b\7+\2\2\u019b")
        buf.write(u"(\3\2\2\2\u019c\u019d\7}\2\2\u019d*\3\2\2\2\u019e\u019f")
        buf.write(u"\7\177\2\2\u019f,\3\2\2\2\u01a0\u01a1\7^\2\2\u01a1\u01a2")
        buf.write(u"\7}\2\2\u01a2.\3\2\2\2\u01a3\u01a4\7^\2\2\u01a4\u01a5")
        buf.write(u"\7\177\2\2\u01a5\60\3\2\2\2\u01a6\u01a7\7]\2\2\u01a7")
        buf.write(u"\62\3\2\2\2\u01a8\u01a9\7_\2\2\u01a9\64\3\2\2\2\u01aa")
        buf.write(u"\u01ab\7~\2\2\u01ab\66\3\2\2\2\u01ac\u01ad\7^\2\2\u01ad")
        buf.write(u"\u01ae\7t\2\2\u01ae\u01af\7k\2\2\u01af\u01b0\7i\2\2\u01b0")
        buf.write(u"\u01b1\7j\2\2\u01b1\u01b2\7v\2\2\u01b2\u01b3\7~\2\2\u01b3")
        buf.write(u"8\3\2\2\2\u01b4\u01b5\7^\2\2\u01b5\u01b6\7n\2\2\u01b6")
        buf.write(u"\u01b7\7g\2\2\u01b7\u01b8\7h\2\2\u01b8\u01b9\7v\2\2\u01b9")
        buf.write(u"\u01ba\7~\2\2\u01ba:\3\2\2\2\u01bb\u01bc\7^\2\2\u01bc")
        buf.write(u"\u01bd\7n\2\2\u01bd\u01be\7c\2\2\u01be\u01bf\7p\2\2\u01bf")
        buf.write(u"\u01c0\7i\2\2\u01c0\u01c1\7n\2\2\u01c1\u01c2\7g\2\2\u01c2")
        buf.write(u"<\3\2\2\2\u01c3\u01c4\7^\2\2\u01c4\u01c5\7t\2\2\u01c5")
        buf.write(u"\u01c6\7c\2\2\u01c6\u01c7\7p\2\2\u01c7\u01c8\7i\2\2\u01c8")
        buf.write(u"\u01c9\7n\2\2\u01c9\u01ca\7g\2\2\u01ca>\3\2\2\2\u01cb")
        buf.write(u"\u01cc\7^\2\2\u01cc\u01cd\7n\2\2\u01cd\u01ce\7k\2\2\u01ce")
        buf.write(u"\u01cf\7o\2\2\u01cf@\3\2\2\2\u01d0\u01d1\7^\2\2\u01d1")
        buf.write(u"\u01d2\7v\2\2\u01d2\u0208\7q\2\2\u01d3\u01d4\7^\2\2\u01d4")
        buf.write(u"\u01d5\7t\2\2\u01d5\u01d6\7k\2\2\u01d6\u01d7\7i\2\2\u01d7")
        buf.write(u"\u01d8\7j\2\2\u01d8\u01d9\7v\2\2\u01d9\u01da\7c\2\2\u01da")
        buf.write(u"\u01db\7t\2\2\u01db\u01dc\7t\2\2\u01dc\u01dd\7q\2\2\u01dd")
        buf.write(u"\u0208\7y\2\2\u01de\u01df\7^\2\2\u01df\u01e0\7T\2\2\u01e0")
        buf.write(u"\u01e1\7k\2\2\u01e1\u01e2\7i\2\2\u01e2\u01e3\7j\2\2\u01e3")
        buf.write(u"\u01e4\7v\2\2\u01e4\u01e5\7c\2\2\u01e5\u01e6\7t\2\2\u01e6")
        buf.write(u"\u01e7\7t\2\2\u01e7\u01e8\7q\2\2\u01e8\u0208\7y\2\2\u01e9")
        buf.write(u"\u01ea\7^\2\2\u01ea\u01eb\7n\2\2\u01eb\u01ec\7q\2\2\u01ec")
        buf.write(u"\u01ed\7p\2\2\u01ed\u01ee\7i\2\2\u01ee\u01ef\7t\2\2\u01ef")
        buf.write(u"\u01f0\7k\2\2\u01f0\u01f1\7i\2\2\u01f1\u01f2\7j\2\2\u01f2")
        buf.write(u"\u01f3\7v\2\2\u01f3\u01f4\7c\2\2\u01f4\u01f5\7t\2\2\u01f5")
        buf.write(u"\u01f6\7t\2\2\u01f6\u01f7\7q\2\2\u01f7\u0208\7y\2\2\u01f8")
        buf.write(u"\u01f9\7^\2\2\u01f9\u01fa\7N\2\2\u01fa\u01fb\7q\2\2\u01fb")
        buf.write(u"\u01fc\7p\2\2\u01fc\u01fd\7i\2\2\u01fd\u01fe\7t\2\2\u01fe")
        buf.write(u"\u01ff\7k\2\2\u01ff\u0200\7i\2\2\u0200\u0201\7j\2\2\u0201")
        buf.write(u"\u0202\7v\2\2\u0202\u0203\7c\2\2\u0203\u0204\7t\2\2\u0204")
        buf.write(u"\u0205\7t\2\2\u0205\u0206\7q\2\2\u0206\u0208\7y\2\2\u0207")
        buf.write(u"\u01d0\3\2\2\2\u0207\u01d3\3\2\2\2\u0207\u01de\3\2\2")
        buf.write(u"\2\u0207\u01e9\3\2\2\2\u0207\u01f8\3\2\2\2\u0208B\3\2")
        buf.write(u"\2\2\u0209\u020a\7^\2\2\u020a\u020b\7k\2\2\u020b\u020c")
        buf.write(u"\7p\2\2\u020c\u020d\7v\2\2\u020dD\3\2\2\2\u020e\u020f")
        buf.write(u"\7^\2\2\u020f\u0210\7u\2\2\u0210\u0211\7w\2\2\u0211\u0212")
        buf.write(u"\7o\2\2\u0212F\3\2\2\2\u0213\u0214\7^\2\2\u0214\u0215")
        buf.write(u"\7r\2\2\u0215\u0216\7t\2\2\u0216\u0217\7q\2\2\u0217\u0218")
        buf.write(u"\7f\2\2\u0218H\3\2\2\2\u0219\u021a\7^\2\2\u021a\u021b")
        buf.write(u"\7g\2\2\u021b\u021c\7z\2\2\u021c\u021d\7r\2\2\u021dJ")
        buf.write(u"\3\2\2\2\u021e\u021f\7^\2\2\u021f\u0220\7n\2\2\u0220")
        buf.write(u"\u0221\7q\2\2\u0221\u0222\7i\2\2\u0222L\3\2\2\2\u0223")
        buf.write(u"\u0224\7^\2\2\u0224\u0225\7n\2\2\u0225\u0226\7p\2\2\u0226")
        buf.write(u"N\3\2\2\2\u0227\u0228\7^\2\2\u0228\u0229\7u\2\2\u0229")
        buf.write(u"\u022a\7k\2\2\u022a\u022b\7p\2\2\u022bP\3\2\2\2\u022c")
        buf.write(u"\u022d\7^\2\2\u022d\u022e\7e\2\2\u022e\u022f\7q\2\2\u022f")
        buf.write(u"\u0230\7u\2\2\u0230R\3\2\2\2\u0231\u0232\7^\2\2\u0232")
        buf.write(u"\u0233\7v\2\2\u0233\u0234\7c\2\2\u0234\u0235\7p\2\2\u0235")
        buf.write(u"T\3\2\2\2\u0236\u0237\7^\2\2\u0237\u0238\7e\2\2\u0238")
        buf.write(u"\u0239\7u\2\2\u0239\u023a\7e\2\2\u023aV\3\2\2\2\u023b")
        buf.write(u"\u023c\7^\2\2\u023c\u023d\7u\2\2\u023d\u023e\7g\2\2\u023e")
        buf.write(u"\u023f\7e\2\2\u023fX\3\2\2\2\u0240\u0241\7^\2\2\u0241")
        buf.write(u"\u0242\7e\2\2\u0242\u0243\7q\2\2\u0243\u0244\7v\2\2\u0244")
        buf.write(u"Z\3\2\2\2\u0245\u0246\7^\2\2\u0246\u0247\7c\2\2\u0247")
        buf.write(u"\u0248\7t\2\2\u0248\u0249\7e\2\2\u0249\u024a\7u\2\2\u024a")
        buf.write(u"\u024b\7k\2\2\u024b\u024c\7p\2\2\u024c\\\3\2\2\2\u024d")
        buf.write(u"\u024e\7^\2\2\u024e\u024f\7c\2\2\u024f\u0250\7t\2\2\u0250")
        buf.write(u"\u0251\7e\2\2\u0251\u0252\7e\2\2\u0252\u0253\7q\2\2\u0253")
        buf.write(u"\u0254\7u\2\2\u0254^\3\2\2\2\u0255\u0256\7^\2\2\u0256")
        buf.write(u"\u0257\7c\2\2\u0257\u0258\7t\2\2\u0258\u0259\7e\2\2\u0259")
        buf.write(u"\u025a\7v\2\2\u025a\u025b\7c\2\2\u025b\u025c\7p\2\2\u025c")
        buf.write(u"`\3\2\2\2\u025d\u025e\7^\2\2\u025e\u025f\7c\2\2\u025f")
        buf.write(u"\u0260\7t\2\2\u0260\u0261\7e\2\2\u0261\u0262\7e\2\2\u0262")
        buf.write(u"\u0263\7u\2\2\u0263\u0264\7e\2\2\u0264b\3\2\2\2\u0265")
        buf.write(u"\u0266\7^\2\2\u0266\u0267\7c\2\2\u0267\u0268\7t\2\2\u0268")
        buf.write(u"\u0269\7e\2\2\u0269\u026a\7u\2\2\u026a\u026b\7g\2\2\u026b")
        buf.write(u"\u026c\7e\2\2\u026cd\3\2\2\2\u026d\u026e\7^\2\2\u026e")
        buf.write(u"\u026f\7c\2\2\u026f\u0270\7t\2\2\u0270\u0271\7e\2\2\u0271")
        buf.write(u"\u0272\7e\2\2\u0272\u0273\7q\2\2\u0273\u0274\7v\2\2\u0274")
        buf.write(u"f\3\2\2\2\u0275\u0276\7^\2\2\u0276\u0277\7u\2\2\u0277")
        buf.write(u"\u0278\7k\2\2\u0278\u0279\7p\2\2\u0279\u027a\7j\2\2\u027a")
        buf.write(u"h\3\2\2\2\u027b\u027c\7^\2\2\u027c\u027d\7e\2\2\u027d")
        buf.write(u"\u027e\7q\2\2\u027e\u027f\7u\2\2\u027f\u0280\7j\2\2\u0280")
        buf.write(u"j\3\2\2\2\u0281\u0282\7^\2\2\u0282\u0283\7v\2\2\u0283")
        buf.write(u"\u0284\7c\2\2\u0284\u0285\7p\2\2\u0285\u0286\7j\2\2\u0286")
        buf.write(u"l\3\2\2\2\u0287\u0288\7^\2\2\u0288\u0289\7c\2\2\u0289")
        buf.write(u"\u028a\7t\2\2\u028a\u028b\7u\2\2\u028b\u028c\7k\2\2\u028c")
        buf.write(u"\u028d\7p\2\2\u028d\u028e\7j\2\2\u028en\3\2\2\2\u028f")
        buf.write(u"\u0290\7^\2\2\u0290\u0291\7c\2\2\u0291\u0292\7t\2\2\u0292")
        buf.write(u"\u0293\7e\2\2\u0293\u0294\7q\2\2\u0294\u0295\7u\2\2\u0295")
        buf.write(u"\u0296\7j\2\2\u0296p\3\2\2\2\u0297\u0298\7^\2\2\u0298")
        buf.write(u"\u0299\7c\2\2\u0299\u029a\7t\2\2\u029a\u029b\7v\2\2\u029b")
        buf.write(u"\u029c\7c\2\2\u029c\u029d\7p\2\2\u029d\u029e\7j\2\2\u029e")
        buf.write(u"r\3\2\2\2\u029f\u02a0\7^\2\2\u02a0\u02a1\7g\2\2\u02a1")
        buf.write(u"\u02a2\7n\2\2\u02a2\u02a3\7n\2\2\u02a3\u02a4\7k\2\2\u02a4")
        buf.write(u"\u02a5\7r\2\2\u02a5\u02a6\7g\2\2\u02a6t\3\2\2\2\u02a7")
        buf.write(u"\u02a8\7^\2\2\u02a8\u02a9\7n\2\2\u02a9\u02aa\7h\2\2\u02aa")
        buf.write(u"\u02ab\7n\2\2\u02ab\u02ac\7q\2\2\u02ac\u02ad\7q\2\2\u02ad")
        buf.write(u"\u02ae\7t\2\2\u02aev\3\2\2\2\u02af\u02b0\7^\2\2\u02b0")
        buf.write(u"\u02b1\7t\2\2\u02b1\u02b2\7h\2\2\u02b2\u02b3\7n\2\2\u02b3")
        buf.write(u"\u02b4\7q\2\2\u02b4\u02b5\7q\2\2\u02b5\u02b6\7t\2\2\u02b6")
        buf.write(u"x\3\2\2\2\u02b7\u02b8\7^\2\2\u02b8\u02b9\7n\2\2\u02b9")
        buf.write(u"\u02ba\7e\2\2\u02ba\u02bb\7g\2\2\u02bb\u02bc\7k\2\2\u02bc")
        buf.write(u"\u02bd\7n\2\2\u02bdz\3\2\2\2\u02be\u02bf\7^\2\2\u02bf")
        buf.write(u"\u02c0\7t\2\2\u02c0\u02c1\7e\2\2\u02c1\u02c2\7g\2\2\u02c2")
        buf.write(u"\u02c3\7k\2\2\u02c3\u02c4\7n\2\2\u02c4|\3\2\2\2\u02c5")
        buf.write(u"\u02c6\7^\2\2\u02c6\u02c7\7u\2\2\u02c7\u02c8\7s\2\2\u02c8")
        buf.write(u"\u02c9\7t\2\2\u02c9\u02ca\7v\2\2\u02ca~\3\2\2\2\u02cb")
        buf.write(u"\u02cc\7^\2\2\u02cc\u02cd\7q\2\2\u02cd\u02ce\7x\2\2\u02ce")
        buf.write(u"\u02cf\7g\2\2\u02cf\u02d0\7t\2\2\u02d0\u02d1\7n\2\2\u02d1")
        buf.write(u"\u02d2\7k\2\2\u02d2\u02d3\7p\2\2\u02d3\u02d4\7g\2\2\u02d4")
        buf.write(u"\u0080\3\2\2\2\u02d5\u02d6\7^\2\2\u02d6\u02d7\7v\2\2")
        buf.write(u"\u02d7\u02d8\7k\2\2\u02d8\u02d9\7o\2\2\u02d9\u02da\7")
        buf.write(u"g\2\2\u02da\u02db\7u\2\2\u02db\u0082\3\2\2\2\u02dc\u02dd")
        buf.write(u"\7^\2\2\u02dd\u02de\7e\2\2\u02de\u02df\7f\2\2\u02df\u02e0")
        buf.write(u"\7q\2\2\u02e0\u02e1\7v\2\2\u02e1\u0084\3\2\2\2\u02e2")
        buf.write(u"\u02e3\7^\2\2\u02e3\u02e4\7f\2\2\u02e4\u02e5\7k\2\2\u02e5")
        buf.write(u"\u02e6\7x\2\2\u02e6\u0086\3\2\2\2\u02e7\u02e8\7^\2\2")
        buf.write(u"\u02e8\u02e9\7h\2\2\u02e9\u02ea\7t\2\2\u02ea\u02eb\7")
        buf.write(u"c\2\2\u02eb\u02ec\7e\2\2\u02ec\u0088\3\2\2\2\u02ed\u02ee")
        buf.write(u"\7^\2\2\u02ee\u02ef\7d\2\2\u02ef\u02f0\7k\2\2\u02f0\u02f1")
        buf.write(u"\7p\2\2\u02f1\u02f2\7q\2\2\u02f2\u02f3\7o\2\2\u02f3\u008a")
        buf.write(u"\3\2\2\2\u02f4\u02f5\7^\2\2\u02f5\u02f6\7f\2\2\u02f6")
        buf.write(u"\u02f7\7d\2\2\u02f7\u02f8\7k\2\2\u02f8\u02f9\7p\2\2\u02f9")
        buf.write(u"\u02fa\7q\2\2\u02fa\u02fb\7o\2\2\u02fb\u008c\3\2\2\2")
        buf.write(u"\u02fc\u02fd\7^\2\2\u02fd\u02fe\7v\2\2\u02fe\u02ff\7")
        buf.write(u"d\2\2\u02ff\u0300\7k\2\2\u0300\u0301\7p\2\2\u0301\u0302")
        buf.write(u"\7q\2\2\u0302\u0303\7o\2\2\u0303\u008e\3\2\2\2\u0304")
        buf.write(u"\u0305\7^\2\2\u0305\u0306\7o\2\2\u0306\u0307\7c\2\2\u0307")
        buf.write(u"\u0308\7v\2\2\u0308\u0309\7j\2\2\u0309\u030a\7k\2\2\u030a")
        buf.write(u"\u030b\7v\2\2\u030b\u0090\3\2\2\2\u030c\u030d\7a\2\2")
        buf.write(u"\u030d\u0092\3\2\2\2\u030e\u030f\7`\2\2\u030f\u0094\3")
        buf.write(u"\2\2\2\u0310\u0311\7<\2\2\u0311\u0096\3\2\2\2\u0312\u0313")
        buf.write(u"\t\2\2\2\u0313\u0098\3\2\2\2\u0314\u0319\7f\2\2\u0315")
        buf.write(u"\u0316\7^\2\2\u0316\u0317\7f\2\2\u0317\u0319\7f\2\2\u0318")
        buf.write(u"\u0314\3\2\2\2\u0318\u0315\3\2\2\2\u0319\u031d\3\2\2")
        buf.write(u"\2\u031a\u031c\5\u0097L\2\u031b\u031a\3\2\2\2\u031c\u031f")
        buf.write(u"\3\2\2\2\u031d\u031e\3\2\2\2\u031d\u031b\3\2\2\2\u031e")
        buf.write(u"\u0327\3\2\2\2\u031f\u031d\3\2\2\2\u0320\u0328\t\3\2")
        buf.write(u"\2\u0321\u0323\7^\2\2\u0322\u0324\t\3\2\2\u0323\u0322")
        buf.write(u"\3\2\2\2\u0324\u0325\3\2\2\2\u0325\u0323\3\2\2\2\u0325")
        buf.write(u"\u0326\3\2\2\2\u0326\u0328\3\2\2\2\u0327\u0320\3\2\2")
        buf.write(u"\2\u0327\u0321\3\2\2\2\u0328\u009a\3\2\2\2\u0329\u032a")
        buf.write(u"\t\3\2\2\u032a\u009c\3\2\2\2\u032b\u032c\t\4\2\2\u032c")
        buf.write(u"\u009e\3\2\2\2\u032d\u032f\5\u009dO\2\u032e\u032d\3\2")
        buf.write(u"\2\2\u032f\u0330\3\2\2\2\u0330\u032e\3\2\2\2\u0330\u0331")
        buf.write(u"\3\2\2\2\u0331\u0339\3\2\2\2\u0332\u0333\7.\2\2\u0333")
        buf.write(u"\u0334\5\u009dO\2\u0334\u0335\5\u009dO\2\u0335\u0336")
        buf.write(u"\5\u009dO\2\u0336\u0338\3\2\2\2\u0337\u0332\3\2\2\2\u0338")
        buf.write(u"\u033b\3\2\2\2\u0339\u0337\3\2\2\2\u0339\u033a\3\2\2")
        buf.write(u"\2\u033a\u0353\3\2\2\2\u033b\u0339\3\2\2\2\u033c\u033e")
        buf.write(u"\5\u009dO\2\u033d\u033c\3\2\2\2\u033e\u0341\3\2\2\2\u033f")
        buf.write(u"\u033d\3\2\2\2\u033f\u0340\3\2\2\2\u0340\u0349\3\2\2")
        buf.write(u"\2\u0341\u033f\3\2\2\2\u0342\u0343\7.\2\2\u0343\u0344")
        buf.write(u"\5\u009dO\2\u0344\u0345\5\u009dO\2\u0345\u0346\5\u009d")
        buf.write(u"O\2\u0346\u0348\3\2\2\2\u0347\u0342\3\2\2\2\u0348\u034b")
        buf.write(u"\3\2\2\2\u0349\u0347\3\2\2\2\u0349\u034a\3\2\2\2\u034a")
        buf.write(u"\u034c\3\2\2\2\u034b\u0349\3\2\2\2\u034c\u034e\7\60\2")
        buf.write(u"\2\u034d\u034f\5\u009dO\2\u034e\u034d\3\2\2\2\u034f\u0350")
        buf.write(u"\3\2\2\2\u0350\u034e\3\2\2\2\u0350\u0351\3\2\2\2\u0351")
        buf.write(u"\u0353\3\2\2\2\u0352\u032e\3\2\2\2\u0352\u033f\3\2\2")
        buf.write(u"\2\u0353\u00a0\3\2\2\2\u0354\u0358\7(\2\2\u0355\u0357")
        buf.write(u"\5\u0097L\2\u0356\u0355\3\2\2\2\u0357\u035a\3\2\2\2\u0358")
        buf.write(u"\u0359\3\2\2\2\u0358\u0356\3\2\2\2\u0359\u035c\3\2\2")
        buf.write(u"\2\u035a\u0358\3\2\2\2\u035b\u0354\3\2\2\2\u035b\u035c")
        buf.write(u"\3\2\2\2\u035c\u035d\3\2\2\2\u035d\u0369\7?\2\2\u035e")
        buf.write(u"\u0366\7?\2\2\u035f\u0361\5\u0097L\2\u0360\u035f\3\2")
        buf.write(u"\2\2\u0361\u0364\3\2\2\2\u0362\u0363\3\2\2\2\u0362\u0360")
        buf.write(u"\3\2\2\2\u0363\u0365\3\2\2\2\u0364\u0362\3\2\2\2\u0365")
        buf.write(u"\u0367\7(\2\2\u0366\u0362\3\2\2\2\u0366\u0367\3\2\2\2")
        buf.write(u"\u0367\u0369\3\2\2\2\u0368\u035b\3\2\2\2\u0368\u035e")
        buf.write(u"\3\2\2\2\u0369\u00a2\3\2\2\2\u036a\u036b\7^\2\2\u036b")
        buf.write(u"\u036c\7p\2\2\u036c\u036d\7g\2\2\u036d\u036e\7s\2\2\u036e")
        buf.write(u"\u00a4\3\2\2\2\u036f\u0370\7>\2\2\u0370\u00a6\3\2\2\2")
        buf.write(u"\u0371\u0372\7^\2\2\u0372\u0373\7n\2\2\u0373\u0374\7")
        buf.write(u"g\2\2\u0374\u037b\7s\2\2\u0375\u0376\7^\2\2\u0376\u0377")
        buf.write(u"\7n\2\2\u0377\u037b\7g\2\2\u0378\u037b\5\u00a9U\2\u0379")
        buf.write(u"\u037b\5\u00abV\2\u037a\u0371\3\2\2\2\u037a\u0375\3\2")
        buf.write(u"\2\2\u037a\u0378\3\2\2\2\u037a\u0379\3\2\2\2\u037b\u00a8")
        buf.write(u"\3\2\2\2\u037c\u037d\7^\2\2\u037d\u037e\7n\2\2\u037e")
        buf.write(u"\u037f\7g\2\2\u037f\u0380\7s\2\2\u0380\u0381\7s\2\2\u0381")
        buf.write(u"\u00aa\3\2\2\2\u0382\u0383\7^\2\2\u0383\u0384\7n\2\2")
        buf.write(u"\u0384\u0385\7g\2\2\u0385\u0386\7s\2\2\u0386\u0387\7")
        buf.write(u"u\2\2\u0387\u0388\7n\2\2\u0388\u0389\7c\2\2\u0389\u038a")
        buf.write(u"\7p\2\2\u038a\u038b\7v\2\2\u038b\u00ac\3\2\2\2\u038c")
        buf.write(u"\u038d\7@\2\2\u038d\u00ae\3\2\2\2\u038e\u038f\7^\2\2")
        buf.write(u"\u038f\u0390\7i\2\2\u0390\u0391\7g\2\2\u0391\u0398\7")
        buf.write(u"s\2\2\u0392\u0393\7^\2\2\u0393\u0394\7i\2\2\u0394\u0398")
        buf.write(u"\7g\2\2\u0395\u0398\5\u00b1Y\2\u0396\u0398\5\u00b3Z\2")
        buf.write(u"\u0397\u038e\3\2\2\2\u0397\u0392\3\2\2\2\u0397\u0395")
        buf.write(u"\3\2\2\2\u0397\u0396\3\2\2\2\u0398\u00b0\3\2\2\2\u0399")
        buf.write(u"\u039a\7^\2\2\u039a\u039b\7i\2\2\u039b\u039c\7g\2\2\u039c")
        buf.write(u"\u039d\7s\2\2\u039d\u039e\7s\2\2\u039e\u00b2\3\2\2\2")
        buf.write(u"\u039f\u03a0\7^\2\2\u03a0\u03a1\7i\2\2\u03a1\u03a2\7")
        buf.write(u"g\2\2\u03a2\u03a3\7s\2\2\u03a3\u03a4\7u\2\2\u03a4\u03a5")
        buf.write(u"\7n\2\2\u03a5\u03a6\7c\2\2\u03a6\u03a7\7p\2\2\u03a7\u03a8")
        buf.write(u"\7v\2\2\u03a8\u00b4\3\2\2\2\u03a9\u03aa\7#\2\2\u03aa")
        buf.write(u"\u00b6\3\2\2\2\u03ab\u03ad\7^\2\2\u03ac\u03ae\t\3\2\2")
        buf.write(u"\u03ad\u03ac\3\2\2\2\u03ae\u03af\3\2\2\2\u03af\u03ad")
        buf.write(u"\3\2\2\2\u03af\u03b0\3\2\2\2\u03b0\u00b8\3\2\2\2\34\2")
        buf.write(u"\u00be\u00ce\u00dd\u00ee\u0112\u018c\u0207\u0318\u031d")
        buf.write(u"\u0325\u0327\u0330\u0339\u033f\u0349\u0350\u0352\u0358")
        buf.write(u"\u035b\u0362\u0366\u0368\u037a\u0397\u03af\3\b\2\2")
        return buf.getvalue()


class LaTeXLexer(Lexer):

    atn = ATNDeserializer().deserialize(serializedATN())

    decisionsToDFA = [DFA(ds, i) for i, ds in enumerate(atn.decisionToState)]

    T__0 = 1
    WS = 2
    THINSPACE = 3
    MEDSPACE = 4
    THICKSPACE = 5
    QUAD = 6
    QQUAD = 7
    NEGTHINSPACE = 8
    NEGMEDSPACE = 9
    NEGTHICKSPACE = 10
    CMD_LEFT = 11
    CMD_RIGHT = 12
    IGNORE = 13
    ADD = 14
    SUB = 15
    MUL = 16
    DIV = 17
    L_PAREN = 18
    R_PAREN = 19
    L_BRACE = 20
    R_BRACE = 21
    L_BRACE_LITERAL = 22
    R_BRACE_LITERAL = 23
    L_BRACKET = 24
    R_BRACKET = 25
    BAR = 26
    R_BAR = 27
    L_BAR = 28
    L_ANGLE = 29
    R_ANGLE = 30
    FUNC_LIM = 31
    LIM_APPROACH_SYM = 32
    FUNC_INT = 33
    FUNC_SUM = 34
    FUNC_PROD = 35
    FUNC_EXP = 36
    FUNC_LOG = 37
    FUNC_LN = 38
    FUNC_SIN = 39
    FUNC_COS = 40
    FUNC_TAN = 41
    FUNC_CSC = 42
    FUNC_SEC = 43
    FUNC_COT = 44
    FUNC_ARCSIN = 45
    FUNC_ARCCOS = 46
    FUNC_ARCTAN = 47
    FUNC_ARCCSC = 48
    FUNC_ARCSEC = 49
    FUNC_ARCCOT = 50
    FUNC_SINH = 51
    FUNC_COSH = 52
    FUNC_TANH = 53
    FUNC_ARSINH = 54
    FUNC_ARCOSH = 55
    FUNC_ARTANH = 56
    FUNC_ELLIPE = 57
    L_FLOOR = 58
    R_FLOOR = 59
    L_CEIL = 60
    R_CEIL = 61
    FUNC_SQRT = 62
    FUNC_OVERLINE = 63
    CMD_TIMES = 64
    CMD_CDOT = 65
    CMD_DIV = 66
    CMD_FRAC = 67
    CMD_BINOM = 68
    CMD_DBINOM = 69
    CMD_TBINOM = 70
    CMD_MATHIT = 71
    UNDERSCORE = 72
    CARET = 73
    COLON = 74
    DIFFERENTIAL = 75
    LETTER = 76
    NUMBER = 77
    EQUAL = 78
    NEQ = 79
    LT = 80
    LTE = 81
    LTE_Q = 82
    LTE_S = 83
    GT = 84
    GTE = 85
    GTE_Q = 86
    GTE_S = 87
    BANG = 88
    SYMBOL = 89

    channelNames = [u"DEFAULT_TOKEN_CHANNEL", u"HIDDEN"]

    modeNames = [u"DEFAULT_MODE"]

    literalNames = [
        u"<INVALID>",
        u"','",
        u"'\\quad'",
        u"'\\qquad'",
        u"'\\negmedspace'",
        u"'\\negthickspace'",
        u"'\\left'",
        u"'\\right'",
        u"'+'",
        u"'-'",
        u"'*'",
        u"'/'",
        u"'('",
        u"')'",
        u"'{'",
        u"'}'",
        u"'\\{'",
        u"'\\}'",
        u"'['",
        u"']'",
        u"'|'",
        u"'\\right|'",
        u"'\\left|'",
        u"'\\langle'",
        u"'\\rangle'",
        u"'\\lim'",
        u"'\\int'",
        u"'\\sum'",
        u"'\\prod'",
        u"'\\exp'",
        u"'\\log'",
        u"'\\ln'",
        u"'\\sin'",
        u"'\\cos'",
        u"'\\tan'",
        u"'\\csc'",
        u"'\\sec'",
        u"'\\cot'",
        u"'\\arcsin'",
        u"'\\arccos'",
        u"'\\arctan'",
        u"'\\arccsc'",
        u"'\\arcsec'",
        u"'\\arccot'",
        u"'\\sinh'",
        u"'\\cosh'",
        u"'\\tanh'",
        u"'\\arsinh'",
        u"'\\arcosh'",
        u"'\\artanh'",
        u"'\\ellipe'",
        u"'\\lfloor'",
        u"'\\rfloor'",
        u"'\\lceil'",
        u"'\\rceil'",
        u"'\\sqrt'",
        u"'\\overline'",
        u"'\\times'",
        u"'\\cdot'",
        u"'\\div'",
        u"'\\frac'",
        u"'\\binom'",
        u"'\\dbinom'",
        u"'\\tbinom'",
        u"'\\mathit'",
        u"'_'",
        u"'^'",
        u"':'",
        u"'\\neq'",
        u"'<'",
        u"'\\leqq'",
        u"'\\leqslant'",
        u"'>'",
        u"'\\geqq'",
        u"'\\geqslant'",
        u"'!'",
    ]

    symbolicNames = [
        u"<INVALID>",
        u"WS",
        u"THINSPACE",
        u"MEDSPACE",
        u"THICKSPACE",
        u"QUAD",
        u"QQUAD",
        u"NEGTHINSPACE",
        u"NEGMEDSPACE",
        u"NEGTHICKSPACE",
        u"CMD_LEFT",
        u"CMD_RIGHT",
        u"IGNORE",
        u"ADD",
        u"SUB",
        u"MUL",
        u"DIV",
        u"L_PAREN",
        u"R_PAREN",
        u"L_BRACE",
        u"R_BRACE",
        u"L_BRACE_LITERAL",
        u"R_BRACE_LITERAL",
        u"L_BRACKET",
        u"R_BRACKET",
        u"BAR",
        u"R_BAR",
        u"L_BAR",
        u"L_ANGLE",
        u"R_ANGLE",
        u"FUNC_LIM",
        u"LIM_APPROACH_SYM",
        u"FUNC_INT",
        u"FUNC_SUM",
        u"FUNC_PROD",
        u"FUNC_EXP",
        u"FUNC_LOG",
        u"FUNC_LN",
        u"FUNC_SIN",
        u"FUNC_COS",
        u"FUNC_TAN",
        u"FUNC_CSC",
        u"FUNC_SEC",
        u"FUNC_COT",
        u"FUNC_ARCSIN",
        u"FUNC_ARCCOS",
        u"FUNC_ARCTAN",
        u"FUNC_ARCCSC",
        u"FUNC_ARCSEC",
        u"FUNC_ARCCOT",
        u"FUNC_SINH",
        u"FUNC_COSH",
        u"FUNC_TANH",
        u"FUNC_ARSINH",
        u"FUNC_ARCOSH",
        u"FUNC_ARTANH",
        u"FUNC_ELLIPE",
        u"L_FLOOR",
        u"R_FLOOR",
        u"L_CEIL",
        u"R_CEIL",
        u"FUNC_SQRT",
        u"FUNC_OVERLINE",
        u"CMD_TIMES",
        u"CMD_CDOT",
        u"CMD_DIV",
        u"CMD_FRAC",
        u"CMD_BINOM",
        u"CMD_DBINOM",
        u"CMD_TBINOM",
        u"CMD_MATHIT",
        u"UNDERSCORE",
        u"CARET",
        u"COLON",
        u"DIFFERENTIAL",
        u"LETTER",
        u"NUMBER",
        u"EQUAL",
        u"NEQ",
        u"LT",
        u"LTE",
        u"LTE_Q",
        u"LTE_S",
        u"GT",
        u"GTE",
        u"GTE_Q",
        u"GTE_S",
        u"BANG",
        u"SYMBOL",
    ]

    ruleNames = [
        u"T__0",
        u"WS",
        u"THINSPACE",
        u"MEDSPACE",
        u"THICKSPACE",
        u"QUAD",
        u"QQUAD",
        u"NEGTHINSPACE",
        u"NEGMEDSPACE",
        u"NEGTHICKSPACE",
        u"CMD_LEFT",
        u"CMD_RIGHT",
        u"IGNORE",
        u"ADD",
        u"SUB",
        u"MUL",
        u"DIV",
        u"L_PAREN",
        u"R_PAREN",
        u"L_BRACE",
        u"R_BRACE",
        u"L_BRACE_LITERAL",
        u"R_BRACE_LITERAL",
        u"L_BRACKET",
        u"R_BRACKET",
        u"BAR",
        u"R_BAR",
        u"L_BAR",
        u"L_ANGLE",
        u"R_ANGLE",
        u"FUNC_LIM",
        u"LIM_APPROACH_SYM",
        u"FUNC_INT",
        u"FUNC_SUM",
        u"FUNC_PROD",
        u"FUNC_EXP",
        u"FUNC_LOG",
        u"FUNC_LN",
        u"FUNC_SIN",
        u"FUNC_COS",
        u"FUNC_TAN",
        u"FUNC_CSC",
        u"FUNC_SEC",
        u"FUNC_COT",
        u"FUNC_ARCSIN",
        u"FUNC_ARCCOS",
        u"FUNC_ARCTAN",
        u"FUNC_ARCCSC",
        u"FUNC_ARCSEC",
        u"FUNC_ARCCOT",
        u"FUNC_SINH",
        u"FUNC_COSH",
        u"FUNC_TANH",
        u"FUNC_ARSINH",
        u"FUNC_ARCOSH",
        u"FUNC_ARTANH",
        u"FUNC_ELLIPE",
        u"L_FLOOR",
        u"R_FLOOR",
        u"L_CEIL",
        u"R_CEIL",
        u"FUNC_SQRT",
        u"FUNC_OVERLINE",
        u"CMD_TIMES",
        u"CMD_CDOT",
        u"CMD_DIV",
        u"CMD_FRAC",
        u"CMD_BINOM",
        u"CMD_DBINOM",
        u"CMD_TBINOM",
        u"CMD_MATHIT",
        u"UNDERSCORE",
        u"CARET",
        u"COLON",
        u"WS_CHAR",
        u"DIFFERENTIAL",
        u"LETTER",
        u"DIGIT",
        u"NUMBER",
        u"EQUAL",
        u"NEQ",
        u"LT",
        u"LTE",
        u"LTE_Q",
        u"LTE_S",
        u"GT",
        u"GTE",
        u"GTE_Q",
        u"GTE_S",
        u"BANG",
        u"SYMBOL",
    ]

    grammarFileName = u"LaTeX.g4"

    def __init__(self, input=None, output=sys.stdout):
        super(LaTeXLexer, self).__init__(input, output=output)
        self.checkVersion("4.7.2")
        self._interp = LexerATNSimulator(
            self, self.atn, self.decisionsToDFA, PredictionContextCache()
        )
        self._actions = None
        self._predicates = None
