# encoding: utf-8

# *** GENERATED BY `setup.py antlr`, DO NOT EDIT BY HAND ***
#
# Generated from ../LaTeX.g4, derived from sympy and latex2sympy
#     latex2sympy is licensed under the MIT license
#     https://github.com/augustt198/latex2sympy/blob/master/LICENSE.txt
#
#     sympy is licensed under the BSD license
#     https://github.com/sympy/sympy/blob/master/LICENSE
#
# Generated with antlr4
#    antlr4 is licensed under the BSD-3-Clause License
#    https://github.com/antlr/antlr4/blob/master/LICENSE.txt
from __future__ import print_function
from antlr4 import *
from io import StringIO
import sys


def serializedATN():
    with StringIO() as buf:
        buf.write(u"\3\u608b\ua72a\u8133\ub9ed\u417c\u3be7\u7786\u5964\2")
        buf.write(u"Z\u03a2\b\1\4\2\t\2\4\3\t\3\4\4\t\4\4\5\t\5\4\6\t\6\4")
        buf.write(u"\7\t\7\4\b\t\b\4\t\t\t\4\n\t\n\4\13\t\13\4\f\t\f\4\r")
        buf.write(u"\t\r\4\16\t\16\4\17\t\17\4\20\t\20\4\21\t\21\4\22\t\22")
        buf.write(u"\4\23\t\23\4\24\t\24\4\25\t\25\4\26\t\26\4\27\t\27\4")
        buf.write(u"\30\t\30\4\31\t\31\4\32\t\32\4\33\t\33\4\34\t\34\4\35")
        buf.write(u'\t\35\4\36\t\36\4\37\t\37\4 \t \4!\t!\4"\t"\4#\t#\4')
        buf.write(u"$\t$\4%\t%\4&\t&\4'\t'\4(\t(\4)\t)\4*\t*\4+\t+\4,\t")
        buf.write(u",\4-\t-\4.\t.\4/\t/\4\60\t\60\4\61\t\61\4\62\t\62\4\63")
        buf.write(u"\t\63\4\64\t\64\4\65\t\65\4\66\t\66\4\67\t\67\48\t8\4")
        buf.write(u"9\t9\4:\t:\4;\t;\4<\t<\4=\t=\4>\t>\4?\t?\4@\t@\4A\tA")
        buf.write(u"\4B\tB\4C\tC\4D\tD\4E\tE\4F\tF\4G\tG\4H\tH\4I\tI\4J\t")
        buf.write(u"J\4K\tK\4L\tL\4M\tM\4N\tN\4O\tO\4P\tP\4Q\tQ\4R\tR\4S")
        buf.write(u"\tS\4T\tT\4U\tU\4V\tV\4W\tW\4X\tX\4Y\tY\4Z\tZ\4[\t[\3")
        buf.write(u"\2\3\2\3\3\6\3\u00bb\n\3\r\3\16\3\u00bc\3\3\3\3\3\4\3")
        buf.write(u"\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\5\4\u00cd")
        buf.write(u"\n\4\3\4\3\4\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5")
        buf.write(u"\3\5\5\5\u00dc\n\5\3\5\3\5\3\6\3\6\3\6\3\6\3\6\3\6\3")
        buf.write(u"\6\3\6\3\6\3\6\3\6\3\6\3\6\5\6\u00ed\n\6\3\6\3\6\3\7")
        buf.write(u"\3\7\3\7\3\7\3\7\3\7\3\7\3\7\3\b\3\b\3\b\3\b\3\b\3\b")
        buf.write(u"\3\b\3\b\3\b\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t")
        buf.write(u"\3\t\3\t\3\t\3\t\3\t\5\t\u0111\n\t\3\t\3\t\3\n\3\n\3")
        buf.write(u"\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3")
        buf.write(u"\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13")
        buf.write(u"\3\13\3\13\3\13\3\13\3\13\3\13\3\f\3\f\3\f\3\f\3\f\3")
        buf.write(u"\f\3\f\3\f\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\16\3")
        buf.write(u"\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16")
        buf.write(u"\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3")
        buf.write(u"\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16")
        buf.write(u"\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3")
        buf.write(u"\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16")
        buf.write(u"\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3")
        buf.write(u"\16\3\16\3\16\3\16\3\16\5\16\u018b\n\16\3\16\3\16\3\17")
        buf.write(u"\3\17\3\20\3\20\3\21\3\21\3\22\3\22\3\23\3\23\3\24\3")
        buf.write(u"\24\3\25\3\25\3\26\3\26\3\27\3\27\3\27\3\30\3\30\3\30")
        buf.write(u"\3\31\3\31\3\32\3\32\3\33\3\33\3\34\3\34\3\34\3\34\3")
        buf.write(u"\34\3\34\3\34\3\34\3\35\3\35\3\35\3\35\3\35\3\35\3\35")
        buf.write(u"\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\37\3\37\3")
        buf.write(u"\37\3\37\3\37\3\37\3\37\3\37\3 \3 \3 \3 \3 \3!\3!\3!")
        buf.write(u"\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3")
        buf.write(u"!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!")
        buf.write(u"\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\5")
        buf.write(u'!\u0206\n!\3"\3"\3"\3"\3"\3#\3#\3#\3#\3#\3$\3$\3')
        buf.write(u"$\3$\3$\3$\3%\3%\3%\3%\3%\3&\3&\3&\3&\3&\3'\3'\3'")
        buf.write(u"\3'\3(\3(\3(\3(\3(\3)\3)\3)\3)\3)\3*\3*\3*\3*\3*\3+")
        buf.write(u"\3+\3+\3+\3+\3,\3,\3,\3,\3,\3-\3-\3-\3-\3-\3.\3.\3.\3")
        buf.write(u".\3.\3.\3.\3.\3/\3/\3/\3/\3/\3/\3/\3/\3\60\3\60\3\60")
        buf.write(u"\3\60\3\60\3\60\3\60\3\60\3\61\3\61\3\61\3\61\3\61\3")
        buf.write(u"\61\3\61\3\61\3\62\3\62\3\62\3\62\3\62\3\62\3\62\3\62")
        buf.write(u"\3\63\3\63\3\63\3\63\3\63\3\63\3\63\3\63\3\64\3\64\3")
        buf.write(u"\64\3\64\3\64\3\64\3\65\3\65\3\65\3\65\3\65\3\65\3\66")
        buf.write(u"\3\66\3\66\3\66\3\66\3\66\3\67\3\67\3\67\3\67\3\67\3")
        buf.write(u"\67\3\67\3\67\38\38\38\38\38\38\38\38\39\39\39\39\39")
        buf.write(u"\39\39\39\3:\3:\3:\3:\3:\3:\3:\3:\3;\3;\3;\3;\3;\3;\3")
        buf.write(u";\3;\3<\3<\3<\3<\3<\3<\3<\3=\3=\3=\3=\3=\3=\3=\3>\3>")
        buf.write(u"\3>\3>\3>\3>\3?\3?\3?\3?\3?\3?\3?\3?\3?\3?\3@\3@\3@\3")
        buf.write(u"@\3@\3@\3@\3A\3A\3A\3A\3A\3A\3B\3B\3B\3B\3B\3C\3C\3C")
        buf.write(u"\3C\3C\3C\3D\3D\3D\3D\3D\3D\3D\3E\3E\3E\3E\3E\3E\3E\3")
        buf.write(u"E\3F\3F\3F\3F\3F\3F\3F\3F\3G\3G\3G\3G\3G\3G\3G\3G\3H")
        buf.write(u"\3H\3I\3I\3J\3J\3K\3K\3L\3L\7L\u030d\nL\fL\16L\u0310")
        buf.write(u"\13L\3L\3L\3L\6L\u0315\nL\rL\16L\u0316\5L\u0319\nL\3")
        buf.write(u"M\3M\3N\3N\3O\6O\u0320\nO\rO\16O\u0321\3O\3O\3O\3O\3")
        buf.write(u"O\7O\u0329\nO\fO\16O\u032c\13O\3O\7O\u032f\nO\fO\16O")
        buf.write(u"\u0332\13O\3O\3O\3O\3O\3O\7O\u0339\nO\fO\16O\u033c\13")
        buf.write(u"O\3O\3O\6O\u0340\nO\rO\16O\u0341\5O\u0344\nO\3P\3P\7")
        buf.write(u"P\u0348\nP\fP\16P\u034b\13P\5P\u034d\nP\3P\3P\3P\7P\u0352")
        buf.write(u"\nP\fP\16P\u0355\13P\3P\5P\u0358\nP\5P\u035a\nP\3Q\3")
        buf.write(u"Q\3Q\3Q\3Q\3R\3R\3S\3S\3S\3S\3S\3S\3S\3S\3S\5S\u036c")
        buf.write(u"\nS\3T\3T\3T\3T\3T\3T\3U\3U\3U\3U\3U\3U\3U\3U\3U\3U\3")
        buf.write(u"V\3V\3W\3W\3W\3W\3W\3W\3W\3W\3W\5W\u0389\nW\3X\3X\3X")
        buf.write(u"\3X\3X\3X\3Y\3Y\3Y\3Y\3Y\3Y\3Y\3Y\3Y\3Y\3Z\3Z\3[\3[\6")
        buf.write(u"[\u039f\n[\r[\16[\u03a0\5\u030e\u0349\u0353\2\\\3\3\5")
        buf.write(u"\4\7\5\t\6\13\7\r\b\17\t\21\n\23\13\25\f\27\r\31\16\33")
        buf.write(u"\17\35\20\37\21!\22#\23%\24'\25)\26+\27-\30/\31\61\32")
        buf.write(u"\63\33\65\34\67\359\36;\37= ?!A\"C#E$G%I&K'M(O)Q*S+")
        buf.write(u"U,W-Y.[/]\60_\61a\62c\63e\64g\65i\66k\67m8o9q:s;u<w=")
        buf.write(u"y>{?}@\177A\u0081B\u0083C\u0085D\u0087E\u0089F\u008b")
        buf.write(u"G\u008dH\u008fI\u0091J\u0093K\u0095\2\u0097L\u0099M\u009b")
        buf.write(u"\2\u009dN\u009fO\u00a1P\u00a3Q\u00a5R\u00a7S\u00a9T\u00ab")
        buf.write(u"U\u00adV\u00afW\u00b1X\u00b3Y\u00b5Z\3\2\5\5\2\13\f\17")
        buf.write(u'\17""\4\2C\\c|\3\2\62;\2\u03cd\2\3\3\2\2\2\2\5\3\2')
        buf.write(u"\2\2\2\7\3\2\2\2\2\t\3\2\2\2\2\13\3\2\2\2\2\r\3\2\2\2")
        buf.write(u"\2\17\3\2\2\2\2\21\3\2\2\2\2\23\3\2\2\2\2\25\3\2\2\2")
        buf.write(u"\2\27\3\2\2\2\2\31\3\2\2\2\2\33\3\2\2\2\2\35\3\2\2\2")
        buf.write(u"\2\37\3\2\2\2\2!\3\2\2\2\2#\3\2\2\2\2%\3\2\2\2\2'\3")
        buf.write(u"\2\2\2\2)\3\2\2\2\2+\3\2\2\2\2-\3\2\2\2\2/\3\2\2\2\2")
        buf.write(u"\61\3\2\2\2\2\63\3\2\2\2\2\65\3\2\2\2\2\67\3\2\2\2\2")
        buf.write(u"9\3\2\2\2\2;\3\2\2\2\2=\3\2\2\2\2?\3\2\2\2\2A\3\2\2\2")
        buf.write(u"\2C\3\2\2\2\2E\3\2\2\2\2G\3\2\2\2\2I\3\2\2\2\2K\3\2\2")
        buf.write(u"\2\2M\3\2\2\2\2O\3\2\2\2\2Q\3\2\2\2\2S\3\2\2\2\2U\3\2")
        buf.write(u"\2\2\2W\3\2\2\2\2Y\3\2\2\2\2[\3\2\2\2\2]\3\2\2\2\2_\3")
        buf.write(u"\2\2\2\2a\3\2\2\2\2c\3\2\2\2\2e\3\2\2\2\2g\3\2\2\2\2")
        buf.write(u"i\3\2\2\2\2k\3\2\2\2\2m\3\2\2\2\2o\3\2\2\2\2q\3\2\2\2")
        buf.write(u"\2s\3\2\2\2\2u\3\2\2\2\2w\3\2\2\2\2y\3\2\2\2\2{\3\2\2")
        buf.write(u"\2\2}\3\2\2\2\2\177\3\2\2\2\2\u0081\3\2\2\2\2\u0083\3")
        buf.write(u"\2\2\2\2\u0085\3\2\2\2\2\u0087\3\2\2\2\2\u0089\3\2\2")
        buf.write(u"\2\2\u008b\3\2\2\2\2\u008d\3\2\2\2\2\u008f\3\2\2\2\2")
        buf.write(u"\u0091\3\2\2\2\2\u0093\3\2\2\2\2\u0097\3\2\2\2\2\u0099")
        buf.write(u"\3\2\2\2\2\u009d\3\2\2\2\2\u009f\3\2\2\2\2\u00a1\3\2")
        buf.write(u"\2\2\2\u00a3\3\2\2\2\2\u00a5\3\2\2\2\2\u00a7\3\2\2\2")
        buf.write(u"\2\u00a9\3\2\2\2\2\u00ab\3\2\2\2\2\u00ad\3\2\2\2\2\u00af")
        buf.write(u"\3\2\2\2\2\u00b1\3\2\2\2\2\u00b3\3\2\2\2\2\u00b5\3\2")
        buf.write(u"\2\2\3\u00b7\3\2\2\2\5\u00ba\3\2\2\2\7\u00cc\3\2\2\2")
        buf.write(u"\t\u00db\3\2\2\2\13\u00ec\3\2\2\2\r\u00f0\3\2\2\2\17")
        buf.write(u"\u00f8\3\2\2\2\21\u0110\3\2\2\2\23\u0114\3\2\2\2\25\u0123")
        buf.write(u"\3\2\2\2\27\u0134\3\2\2\2\31\u013c\3\2\2\2\33\u018a\3")
        buf.write(u"\2\2\2\35\u018e\3\2\2\2\37\u0190\3\2\2\2!\u0192\3\2\2")
        buf.write(u"\2#\u0194\3\2\2\2%\u0196\3\2\2\2'\u0198\3\2\2\2)\u019a")
        buf.write(u"\3\2\2\2+\u019c\3\2\2\2-\u019e\3\2\2\2/\u01a1\3\2\2\2")
        buf.write(u"\61\u01a4\3\2\2\2\63\u01a6\3\2\2\2\65\u01a8\3\2\2\2\67")
        buf.write(u"\u01aa\3\2\2\29\u01b2\3\2\2\2;\u01b9\3\2\2\2=\u01c1\3")
        buf.write(u"\2\2\2?\u01c9\3\2\2\2A\u0205\3\2\2\2C\u0207\3\2\2\2E")
        buf.write(u"\u020c\3\2\2\2G\u0211\3\2\2\2I\u0217\3\2\2\2K\u021c\3")
        buf.write(u"\2\2\2M\u0221\3\2\2\2O\u0225\3\2\2\2Q\u022a\3\2\2\2S")
        buf.write(u"\u022f\3\2\2\2U\u0234\3\2\2\2W\u0239\3\2\2\2Y\u023e\3")
        buf.write(u"\2\2\2[\u0243\3\2\2\2]\u024b\3\2\2\2_\u0253\3\2\2\2a")
        buf.write(u"\u025b\3\2\2\2c\u0263\3\2\2\2e\u026b\3\2\2\2g\u0273\3")
        buf.write(u"\2\2\2i\u0279\3\2\2\2k\u027f\3\2\2\2m\u0285\3\2\2\2o")
        buf.write(u"\u028d\3\2\2\2q\u0295\3\2\2\2s\u029d\3\2\2\2u\u02a5\3")
        buf.write(u"\2\2\2w\u02ad\3\2\2\2y\u02b4\3\2\2\2{\u02bb\3\2\2\2}")
        buf.write(u"\u02c1\3\2\2\2\177\u02cb\3\2\2\2\u0081\u02d2\3\2\2\2")
        buf.write(u"\u0083\u02d8\3\2\2\2\u0085\u02dd\3\2\2\2\u0087\u02e3")
        buf.write(u"\3\2\2\2\u0089\u02ea\3\2\2\2\u008b\u02f2\3\2\2\2\u008d")
        buf.write(u"\u02fa\3\2\2\2\u008f\u0302\3\2\2\2\u0091\u0304\3\2\2")
        buf.write(u"\2\u0093\u0306\3\2\2\2\u0095\u0308\3\2\2\2\u0097\u030a")
        buf.write(u"\3\2\2\2\u0099\u031a\3\2\2\2\u009b\u031c\3\2\2\2\u009d")
        buf.write(u"\u0343\3\2\2\2\u009f\u0359\3\2\2\2\u00a1\u035b\3\2\2")
        buf.write(u"\2\u00a3\u0360\3\2\2\2\u00a5\u036b\3\2\2\2\u00a7\u036d")
        buf.write(u"\3\2\2\2\u00a9\u0373\3\2\2\2\u00ab\u037d\3\2\2\2\u00ad")
        buf.write(u"\u0388\3\2\2\2\u00af\u038a\3\2\2\2\u00b1\u0390\3\2\2")
        buf.write(u"\2\u00b3\u039a\3\2\2\2\u00b5\u039c\3\2\2\2\u00b7\u00b8")
        buf.write(u"\7.\2\2\u00b8\4\3\2\2\2\u00b9\u00bb\t\2\2\2\u00ba\u00b9")
        buf.write(u"\3\2\2\2\u00bb\u00bc\3\2\2\2\u00bc\u00ba\3\2\2\2\u00bc")
        buf.write(u"\u00bd\3\2\2\2\u00bd\u00be\3\2\2\2\u00be\u00bf\b\3\2")
        buf.write(u"\2\u00bf\6\3\2\2\2\u00c0\u00c1\7^\2\2\u00c1\u00cd\7.")
        buf.write(u"\2\2\u00c2\u00c3\7^\2\2\u00c3\u00c4\7v\2\2\u00c4\u00c5")
        buf.write(u"\7j\2\2\u00c5\u00c6\7k\2\2\u00c6\u00c7\7p\2\2\u00c7\u00c8")
        buf.write(u"\7u\2\2\u00c8\u00c9\7r\2\2\u00c9\u00ca\7c\2\2\u00ca\u00cb")
        buf.write(u"\7e\2\2\u00cb\u00cd\7g\2\2\u00cc\u00c0\3\2\2\2\u00cc")
        buf.write(u"\u00c2\3\2\2\2\u00cd\u00ce\3\2\2\2\u00ce\u00cf\b\4\2")
        buf.write(u"\2\u00cf\b\3\2\2\2\u00d0\u00d1\7^\2\2\u00d1\u00dc\7<")
        buf.write(u"\2\2\u00d2\u00d3\7^\2\2\u00d3\u00d4\7o\2\2\u00d4\u00d5")
        buf.write(u"\7g\2\2\u00d5\u00d6\7f\2\2\u00d6\u00d7\7u\2\2\u00d7\u00d8")
        buf.write(u"\7r\2\2\u00d8\u00d9\7c\2\2\u00d9\u00da\7e\2\2\u00da\u00dc")
        buf.write(u"\7g\2\2\u00db\u00d0\3\2\2\2\u00db\u00d2\3\2\2\2\u00dc")
        buf.write(u"\u00dd\3\2\2\2\u00dd\u00de\b\5\2\2\u00de\n\3\2\2\2\u00df")
        buf.write(u"\u00e0\7^\2\2\u00e0\u00ed\7=\2\2\u00e1\u00e2\7^\2\2\u00e2")
        buf.write(u"\u00e3\7v\2\2\u00e3\u00e4\7j\2\2\u00e4\u00e5\7k\2\2\u00e5")
        buf.write(u"\u00e6\7e\2\2\u00e6\u00e7\7m\2\2\u00e7\u00e8\7u\2\2\u00e8")
        buf.write(u"\u00e9\7r\2\2\u00e9\u00ea\7c\2\2\u00ea\u00eb\7e\2\2\u00eb")
        buf.write(u"\u00ed\7g\2\2\u00ec\u00df\3\2\2\2\u00ec\u00e1\3\2\2\2")
        buf.write(u"\u00ed\u00ee\3\2\2\2\u00ee\u00ef\b\6\2\2\u00ef\f\3\2")
        buf.write(u"\2\2\u00f0\u00f1\7^\2\2\u00f1\u00f2\7s\2\2\u00f2\u00f3")
        buf.write(u"\7w\2\2\u00f3\u00f4\7c\2\2\u00f4\u00f5\7f\2\2\u00f5\u00f6")
        buf.write(u"\3\2\2\2\u00f6\u00f7\b\7\2\2\u00f7\16\3\2\2\2\u00f8\u00f9")
        buf.write(u"\7^\2\2\u00f9\u00fa\7s\2\2\u00fa\u00fb\7s\2\2\u00fb\u00fc")
        buf.write(u"\7w\2\2\u00fc\u00fd\7c\2\2\u00fd\u00fe\7f\2\2\u00fe\u00ff")
        buf.write(u"\3\2\2\2\u00ff\u0100\b\b\2\2\u0100\20\3\2\2\2\u0101\u0102")
        buf.write(u"\7^\2\2\u0102\u0111\7#\2\2\u0103\u0104\7^\2\2\u0104\u0105")
        buf.write(u"\7p\2\2\u0105\u0106\7g\2\2\u0106\u0107\7i\2\2\u0107\u0108")
        buf.write(u"\7v\2\2\u0108\u0109\7j\2\2\u0109\u010a\7k\2\2\u010a\u010b")
        buf.write(u"\7p\2\2\u010b\u010c\7u\2\2\u010c\u010d\7r\2\2\u010d\u010e")
        buf.write(u"\7c\2\2\u010e\u010f\7e\2\2\u010f\u0111\7g\2\2\u0110\u0101")
        buf.write(u"\3\2\2\2\u0110\u0103\3\2\2\2\u0111\u0112\3\2\2\2\u0112")
        buf.write(u"\u0113\b\t\2\2\u0113\22\3\2\2\2\u0114\u0115\7^\2\2\u0115")
        buf.write(u"\u0116\7p\2\2\u0116\u0117\7g\2\2\u0117\u0118\7i\2\2\u0118")
        buf.write(u"\u0119\7o\2\2\u0119\u011a\7g\2\2\u011a\u011b\7f\2\2\u011b")
        buf.write(u"\u011c\7u\2\2\u011c\u011d\7r\2\2\u011d\u011e\7c\2\2\u011e")
        buf.write(u"\u011f\7e\2\2\u011f\u0120\7g\2\2\u0120\u0121\3\2\2\2")
        buf.write(u"\u0121\u0122\b\n\2\2\u0122\24\3\2\2\2\u0123\u0124\7^")
        buf.write(u"\2\2\u0124\u0125\7p\2\2\u0125\u0126\7g\2\2\u0126\u0127")
        buf.write(u"\7i\2\2\u0127\u0128\7v\2\2\u0128\u0129\7j\2\2\u0129\u012a")
        buf.write(u"\7k\2\2\u012a\u012b\7e\2\2\u012b\u012c\7m\2\2\u012c\u012d")
        buf.write(u"\7u\2\2\u012d\u012e\7r\2\2\u012e\u012f\7c\2\2\u012f\u0130")
        buf.write(u"\7e\2\2\u0130\u0131\7g\2\2\u0131\u0132\3\2\2\2\u0132")
        buf.write(u"\u0133\b\13\2\2\u0133\26\3\2\2\2\u0134\u0135\7^\2\2\u0135")
        buf.write(u"\u0136\7n\2\2\u0136\u0137\7g\2\2\u0137\u0138\7h\2\2\u0138")
        buf.write(u"\u0139\7v\2\2\u0139\u013a\3\2\2\2\u013a\u013b\b\f\2\2")
        buf.write(u"\u013b\30\3\2\2\2\u013c\u013d\7^\2\2\u013d\u013e\7t\2")
        buf.write(u"\2\u013e\u013f\7k\2\2\u013f\u0140\7i\2\2\u0140\u0141")
        buf.write(u"\7j\2\2\u0141\u0142\7v\2\2\u0142\u0143\3\2\2\2\u0143")
        buf.write(u"\u0144\b\r\2\2\u0144\32\3\2\2\2\u0145\u0146\7^\2\2\u0146")
        buf.write(u"\u0147\7x\2\2\u0147\u0148\7t\2\2\u0148\u0149\7w\2\2\u0149")
        buf.write(u"\u014a\7n\2\2\u014a\u018b\7g\2\2\u014b\u014c\7^\2\2\u014c")
        buf.write(u"\u014d\7x\2\2\u014d\u014e\7e\2\2\u014e\u014f\7g\2\2\u014f")
        buf.write(u"\u0150\7p\2\2\u0150\u0151\7v\2\2\u0151\u0152\7g\2\2\u0152")
        buf.write(u"\u018b\7t\2\2\u0153\u0154\7^\2\2\u0154\u0155\7x\2\2\u0155")
        buf.write(u"\u0156\7d\2\2\u0156\u0157\7q\2\2\u0157\u018b\7z\2\2\u0158")
        buf.write(u"\u0159\7^\2\2\u0159\u015a\7x\2\2\u015a\u015b\7u\2\2\u015b")
        buf.write(u"\u015c\7m\2\2\u015c\u015d\7k\2\2\u015d\u018b\7r\2\2\u015e")
        buf.write(u"\u015f\7^\2\2\u015f\u0160\7x\2\2\u0160\u0161\7u\2\2\u0161")
        buf.write(u"\u0162\7r\2\2\u0162\u0163\7c\2\2\u0163\u0164\7e\2\2\u0164")
        buf.write(u"\u018b\7g\2\2\u0165\u0166\7^\2\2\u0166\u0167\7j\2\2\u0167")
        buf.write(u"\u0168\7h\2\2\u0168\u0169\7k\2\2\u0169\u018b\7n\2\2\u016a")
        buf.write(u"\u016b\7^\2\2\u016b\u018b\7,\2\2\u016c\u016d\7^\2\2\u016d")
        buf.write(u"\u018b\7/\2\2\u016e\u016f\7^\2\2\u016f\u018b\7\60\2\2")
        buf.write(u"\u0170\u0171\7^\2\2\u0171\u018b\7\61\2\2\u0172\u0173")
        buf.write(u"\7^\2\2\u0173\u018b\7$\2\2\u0174\u0175\7^\2\2\u0175\u018b")
        buf.write(u"\7*\2\2\u0176\u0177\7^\2\2\u0177\u018b\7?\2\2\u0178\u0179")
        buf.write(u"\7^\2\2\u0179\u017a\7d\2\2\u017a\u017b\7k\2\2\u017b\u018b")
        buf.write(u"\7i\2\2\u017c\u017d\7^\2\2\u017d\u017e\7d\2\2\u017e\u017f")
        buf.write(u"\7k\2\2\u017f\u0180\7i\2\2\u0180\u018b\7i\2\2\u0181\u0182")
        buf.write(u"\7^\2\2\u0182\u0183\7D\2\2\u0183\u0184\7k\2\2\u0184\u018b")
        buf.write(u"\7i\2\2\u0185\u0186\7^\2\2\u0186\u0187\7D\2\2\u0187\u0188")
        buf.write(u"\7k\2\2\u0188\u0189\7i\2\2\u0189\u018b\7i\2\2\u018a\u0145")
        buf.write(u"\3\2\2\2\u018a\u014b\3\2\2\2\u018a\u0153\3\2\2\2\u018a")
        buf.write(u"\u0158\3\2\2\2\u018a\u015e\3\2\2\2\u018a\u0165\3\2\2")
        buf.write(u"\2\u018a\u016a\3\2\2\2\u018a\u016c\3\2\2\2\u018a\u016e")
        buf.write(u"\3\2\2\2\u018a\u0170\3\2\2\2\u018a\u0172\3\2\2\2\u018a")
        buf.write(u"\u0174\3\2\2\2\u018a\u0176\3\2\2\2\u018a\u0178\3\2\2")
        buf.write(u"\2\u018a\u017c\3\2\2\2\u018a\u0181\3\2\2\2\u018a\u0185")
        buf.write(u"\3\2\2\2\u018b\u018c\3\2\2\2\u018c\u018d\b\16\2\2\u018d")
        buf.write(u"\34\3\2\2\2\u018e\u018f\7-\2\2\u018f\36\3\2\2\2\u0190")
        buf.write(u"\u0191\7/\2\2\u0191 \3\2\2\2\u0192\u0193\7,\2\2\u0193")
        buf.write(u'"\3\2\2\2\u0194\u0195\7\61\2\2\u0195$\3\2\2\2\u0196')
        buf.write(u"\u0197\7*\2\2\u0197&\3\2\2\2\u0198\u0199\7+\2\2\u0199")
        buf.write(u"(\3\2\2\2\u019a\u019b\7}\2\2\u019b*\3\2\2\2\u019c\u019d")
        buf.write(u"\7\177\2\2\u019d,\3\2\2\2\u019e\u019f\7^\2\2\u019f\u01a0")
        buf.write(u"\7}\2\2\u01a0.\3\2\2\2\u01a1\u01a2\7^\2\2\u01a2\u01a3")
        buf.write(u"\7\177\2\2\u01a3\60\3\2\2\2\u01a4\u01a5\7]\2\2\u01a5")
        buf.write(u"\62\3\2\2\2\u01a6\u01a7\7_\2\2\u01a7\64\3\2\2\2\u01a8")
        buf.write(u"\u01a9\7~\2\2\u01a9\66\3\2\2\2\u01aa\u01ab\7^\2\2\u01ab")
        buf.write(u"\u01ac\7t\2\2\u01ac\u01ad\7k\2\2\u01ad\u01ae\7i\2\2\u01ae")
        buf.write(u"\u01af\7j\2\2\u01af\u01b0\7v\2\2\u01b0\u01b1\7~\2\2\u01b1")
        buf.write(u"8\3\2\2\2\u01b2\u01b3\7^\2\2\u01b3\u01b4\7n\2\2\u01b4")
        buf.write(u"\u01b5\7g\2\2\u01b5\u01b6\7h\2\2\u01b6\u01b7\7v\2\2\u01b7")
        buf.write(u"\u01b8\7~\2\2\u01b8:\3\2\2\2\u01b9\u01ba\7^\2\2\u01ba")
        buf.write(u"\u01bb\7n\2\2\u01bb\u01bc\7c\2\2\u01bc\u01bd\7p\2\2\u01bd")
        buf.write(u"\u01be\7i\2\2\u01be\u01bf\7n\2\2\u01bf\u01c0\7g\2\2\u01c0")
        buf.write(u"<\3\2\2\2\u01c1\u01c2\7^\2\2\u01c2\u01c3\7t\2\2\u01c3")
        buf.write(u"\u01c4\7c\2\2\u01c4\u01c5\7p\2\2\u01c5\u01c6\7i\2\2\u01c6")
        buf.write(u"\u01c7\7n\2\2\u01c7\u01c8\7g\2\2\u01c8>\3\2\2\2\u01c9")
        buf.write(u"\u01ca\7^\2\2\u01ca\u01cb\7n\2\2\u01cb\u01cc\7k\2\2\u01cc")
        buf.write(u"\u01cd\7o\2\2\u01cd@\3\2\2\2\u01ce\u01cf\7^\2\2\u01cf")
        buf.write(u"\u01d0\7v\2\2\u01d0\u0206\7q\2\2\u01d1\u01d2\7^\2\2\u01d2")
        buf.write(u"\u01d3\7t\2\2\u01d3\u01d4\7k\2\2\u01d4\u01d5\7i\2\2\u01d5")
        buf.write(u"\u01d6\7j\2\2\u01d6\u01d7\7v\2\2\u01d7\u01d8\7c\2\2\u01d8")
        buf.write(u"\u01d9\7t\2\2\u01d9\u01da\7t\2\2\u01da\u01db\7q\2\2\u01db")
        buf.write(u"\u0206\7y\2\2\u01dc\u01dd\7^\2\2\u01dd\u01de\7T\2\2\u01de")
        buf.write(u"\u01df\7k\2\2\u01df\u01e0\7i\2\2\u01e0\u01e1\7j\2\2\u01e1")
        buf.write(u"\u01e2\7v\2\2\u01e2\u01e3\7c\2\2\u01e3\u01e4\7t\2\2\u01e4")
        buf.write(u"\u01e5\7t\2\2\u01e5\u01e6\7q\2\2\u01e6\u0206\7y\2\2\u01e7")
        buf.write(u"\u01e8\7^\2\2\u01e8\u01e9\7n\2\2\u01e9\u01ea\7q\2\2\u01ea")
        buf.write(u"\u01eb\7p\2\2\u01eb\u01ec\7i\2\2\u01ec\u01ed\7t\2\2\u01ed")
        buf.write(u"\u01ee\7k\2\2\u01ee\u01ef\7i\2\2\u01ef\u01f0\7j\2\2\u01f0")
        buf.write(u"\u01f1\7v\2\2\u01f1\u01f2\7c\2\2\u01f2\u01f3\7t\2\2\u01f3")
        buf.write(u"\u01f4\7t\2\2\u01f4\u01f5\7q\2\2\u01f5\u0206\7y\2\2\u01f6")
        buf.write(u"\u01f7\7^\2\2\u01f7\u01f8\7N\2\2\u01f8\u01f9\7q\2\2\u01f9")
        buf.write(u"\u01fa\7p\2\2\u01fa\u01fb\7i\2\2\u01fb\u01fc\7t\2\2\u01fc")
        buf.write(u"\u01fd\7k\2\2\u01fd\u01fe\7i\2\2\u01fe\u01ff\7j\2\2\u01ff")
        buf.write(u"\u0200\7v\2\2\u0200\u0201\7c\2\2\u0201\u0202\7t\2\2\u0202")
        buf.write(u"\u0203\7t\2\2\u0203\u0204\7q\2\2\u0204\u0206\7y\2\2\u0205")
        buf.write(u"\u01ce\3\2\2\2\u0205\u01d1\3\2\2\2\u0205\u01dc\3\2\2")
        buf.write(u"\2\u0205\u01e7\3\2\2\2\u0205\u01f6\3\2\2\2\u0206B\3\2")
        buf.write(u"\2\2\u0207\u0208\7^\2\2\u0208\u0209\7k\2\2\u0209\u020a")
        buf.write(u"\7p\2\2\u020a\u020b\7v\2\2\u020bD\3\2\2\2\u020c\u020d")
        buf.write(u"\7^\2\2\u020d\u020e\7u\2\2\u020e\u020f\7w\2\2\u020f\u0210")
        buf.write(u"\7o\2\2\u0210F\3\2\2\2\u0211\u0212\7^\2\2\u0212\u0213")
        buf.write(u"\7r\2\2\u0213\u0214\7t\2\2\u0214\u0215\7q\2\2\u0215\u0216")
        buf.write(u"\7f\2\2\u0216H\3\2\2\2\u0217\u0218\7^\2\2\u0218\u0219")
        buf.write(u"\7g\2\2\u0219\u021a\7z\2\2\u021a\u021b\7r\2\2\u021bJ")
        buf.write(u"\3\2\2\2\u021c\u021d\7^\2\2\u021d\u021e\7n\2\2\u021e")
        buf.write(u"\u021f\7q\2\2\u021f\u0220\7i\2\2\u0220L\3\2\2\2\u0221")
        buf.write(u"\u0222\7^\2\2\u0222\u0223\7n\2\2\u0223\u0224\7p\2\2\u0224")
        buf.write(u"N\3\2\2\2\u0225\u0226\7^\2\2\u0226\u0227\7u\2\2\u0227")
        buf.write(u"\u0228\7k\2\2\u0228\u0229\7p\2\2\u0229P\3\2\2\2\u022a")
        buf.write(u"\u022b\7^\2\2\u022b\u022c\7e\2\2\u022c\u022d\7q\2\2\u022d")
        buf.write(u"\u022e\7u\2\2\u022eR\3\2\2\2\u022f\u0230\7^\2\2\u0230")
        buf.write(u"\u0231\7v\2\2\u0231\u0232\7c\2\2\u0232\u0233\7p\2\2\u0233")
        buf.write(u"T\3\2\2\2\u0234\u0235\7^\2\2\u0235\u0236\7e\2\2\u0236")
        buf.write(u"\u0237\7u\2\2\u0237\u0238\7e\2\2\u0238V\3\2\2\2\u0239")
        buf.write(u"\u023a\7^\2\2\u023a\u023b\7u\2\2\u023b\u023c\7g\2\2\u023c")
        buf.write(u"\u023d\7e\2\2\u023dX\3\2\2\2\u023e\u023f\7^\2\2\u023f")
        buf.write(u"\u0240\7e\2\2\u0240\u0241\7q\2\2\u0241\u0242\7v\2\2\u0242")
        buf.write(u"Z\3\2\2\2\u0243\u0244\7^\2\2\u0244\u0245\7c\2\2\u0245")
        buf.write(u"\u0246\7t\2\2\u0246\u0247\7e\2\2\u0247\u0248\7u\2\2\u0248")
        buf.write(u"\u0249\7k\2\2\u0249\u024a\7p\2\2\u024a\\\3\2\2\2\u024b")
        buf.write(u"\u024c\7^\2\2\u024c\u024d\7c\2\2\u024d\u024e\7t\2\2\u024e")
        buf.write(u"\u024f\7e\2\2\u024f\u0250\7e\2\2\u0250\u0251\7q\2\2\u0251")
        buf.write(u"\u0252\7u\2\2\u0252^\3\2\2\2\u0253\u0254\7^\2\2\u0254")
        buf.write(u"\u0255\7c\2\2\u0255\u0256\7t\2\2\u0256\u0257\7e\2\2\u0257")
        buf.write(u"\u0258\7v\2\2\u0258\u0259\7c\2\2\u0259\u025a\7p\2\2\u025a")
        buf.write(u"`\3\2\2\2\u025b\u025c\7^\2\2\u025c\u025d\7c\2\2\u025d")
        buf.write(u"\u025e\7t\2\2\u025e\u025f\7e\2\2\u025f\u0260\7e\2\2\u0260")
        buf.write(u"\u0261\7u\2\2\u0261\u0262\7e\2\2\u0262b\3\2\2\2\u0263")
        buf.write(u"\u0264\7^\2\2\u0264\u0265\7c\2\2\u0265\u0266\7t\2\2\u0266")
        buf.write(u"\u0267\7e\2\2\u0267\u0268\7u\2\2\u0268\u0269\7g\2\2\u0269")
        buf.write(u"\u026a\7e\2\2\u026ad\3\2\2\2\u026b\u026c\7^\2\2\u026c")
        buf.write(u"\u026d\7c\2\2\u026d\u026e\7t\2\2\u026e\u026f\7e\2\2\u026f")
        buf.write(u"\u0270\7e\2\2\u0270\u0271\7q\2\2\u0271\u0272\7v\2\2\u0272")
        buf.write(u"f\3\2\2\2\u0273\u0274\7^\2\2\u0274\u0275\7u\2\2\u0275")
        buf.write(u"\u0276\7k\2\2\u0276\u0277\7p\2\2\u0277\u0278\7j\2\2\u0278")
        buf.write(u"h\3\2\2\2\u0279\u027a\7^\2\2\u027a\u027b\7e\2\2\u027b")
        buf.write(u"\u027c\7q\2\2\u027c\u027d\7u\2\2\u027d\u027e\7j\2\2\u027e")
        buf.write(u"j\3\2\2\2\u027f\u0280\7^\2\2\u0280\u0281\7v\2\2\u0281")
        buf.write(u"\u0282\7c\2\2\u0282\u0283\7p\2\2\u0283\u0284\7j\2\2\u0284")
        buf.write(u"l\3\2\2\2\u0285\u0286\7^\2\2\u0286\u0287\7c\2\2\u0287")
        buf.write(u"\u0288\7t\2\2\u0288\u0289\7u\2\2\u0289\u028a\7k\2\2\u028a")
        buf.write(u"\u028b\7p\2\2\u028b\u028c\7j\2\2\u028cn\3\2\2\2\u028d")
        buf.write(u"\u028e\7^\2\2\u028e\u028f\7c\2\2\u028f\u0290\7t\2\2\u0290")
        buf.write(u"\u0291\7e\2\2\u0291\u0292\7q\2\2\u0292\u0293\7u\2\2\u0293")
        buf.write(u"\u0294\7j\2\2\u0294p\3\2\2\2\u0295\u0296\7^\2\2\u0296")
        buf.write(u"\u0297\7c\2\2\u0297\u0298\7t\2\2\u0298\u0299\7v\2\2\u0299")
        buf.write(u"\u029a\7c\2\2\u029a\u029b\7p\2\2\u029b\u029c\7j\2\2\u029c")
        buf.write(u"r\3\2\2\2\u029d\u029e\7^\2\2\u029e\u029f\7n\2\2\u029f")
        buf.write(u"\u02a0\7h\2\2\u02a0\u02a1\7n\2\2\u02a1\u02a2\7q\2\2\u02a2")
        buf.write(u"\u02a3\7q\2\2\u02a3\u02a4\7t\2\2\u02a4t\3\2\2\2\u02a5")
        buf.write(u"\u02a6\7^\2\2\u02a6\u02a7\7t\2\2\u02a7\u02a8\7h\2\2\u02a8")
        buf.write(u"\u02a9\7n\2\2\u02a9\u02aa\7q\2\2\u02aa\u02ab\7q\2\2\u02ab")
        buf.write(u"\u02ac\7t\2\2\u02acv\3\2\2\2\u02ad\u02ae\7^\2\2\u02ae")
        buf.write(u"\u02af\7n\2\2\u02af\u02b0\7e\2\2\u02b0\u02b1\7g\2\2\u02b1")
        buf.write(u"\u02b2\7k\2\2\u02b2\u02b3\7n\2\2\u02b3x\3\2\2\2\u02b4")
        buf.write(u"\u02b5\7^\2\2\u02b5\u02b6\7t\2\2\u02b6\u02b7\7e\2\2\u02b7")
        buf.write(u"\u02b8\7g\2\2\u02b8\u02b9\7k\2\2\u02b9\u02ba\7n\2\2\u02ba")
        buf.write(u"z\3\2\2\2\u02bb\u02bc\7^\2\2\u02bc\u02bd\7u\2\2\u02bd")
        buf.write(u"\u02be\7s\2\2\u02be\u02bf\7t\2\2\u02bf\u02c0\7v\2\2\u02c0")
        buf.write(u"|\3\2\2\2\u02c1\u02c2\7^\2\2\u02c2\u02c3\7q\2\2\u02c3")
        buf.write(u"\u02c4\7x\2\2\u02c4\u02c5\7g\2\2\u02c5\u02c6\7t\2\2\u02c6")
        buf.write(u"\u02c7\7n\2\2\u02c7\u02c8\7k\2\2\u02c8\u02c9\7p\2\2\u02c9")
        buf.write(u"\u02ca\7g\2\2\u02ca~\3\2\2\2\u02cb\u02cc\7^\2\2\u02cc")
        buf.write(u"\u02cd\7v\2\2\u02cd\u02ce\7k\2\2\u02ce\u02cf\7o\2\2\u02cf")
        buf.write(u"\u02d0\7g\2\2\u02d0\u02d1\7u\2\2\u02d1\u0080\3\2\2\2")
        buf.write(u"\u02d2\u02d3\7^\2\2\u02d3\u02d4\7e\2\2\u02d4\u02d5\7")
        buf.write(u"f\2\2\u02d5\u02d6\7q\2\2\u02d6\u02d7\7v\2\2\u02d7\u0082")
        buf.write(u"\3\2\2\2\u02d8\u02d9\7^\2\2\u02d9\u02da\7f\2\2\u02da")
        buf.write(u"\u02db\7k\2\2\u02db\u02dc\7x\2\2\u02dc\u0084\3\2\2\2")
        buf.write(u"\u02dd\u02de\7^\2\2\u02de\u02df\7h\2\2\u02df\u02e0\7")
        buf.write(u"t\2\2\u02e0\u02e1\7c\2\2\u02e1\u02e2\7e\2\2\u02e2\u0086")
        buf.write(u"\3\2\2\2\u02e3\u02e4\7^\2\2\u02e4\u02e5\7d\2\2\u02e5")
        buf.write(u"\u02e6\7k\2\2\u02e6\u02e7\7p\2\2\u02e7\u02e8\7q\2\2\u02e8")
        buf.write(u"\u02e9\7o\2\2\u02e9\u0088\3\2\2\2\u02ea\u02eb\7^\2\2")
        buf.write(u"\u02eb\u02ec\7f\2\2\u02ec\u02ed\7d\2\2\u02ed\u02ee\7")
        buf.write(u"k\2\2\u02ee\u02ef\7p\2\2\u02ef\u02f0\7q\2\2\u02f0\u02f1")
        buf.write(u"\7o\2\2\u02f1\u008a\3\2\2\2\u02f2\u02f3\7^\2\2\u02f3")
        buf.write(u"\u02f4\7v\2\2\u02f4\u02f5\7d\2\2\u02f5\u02f6\7k\2\2\u02f6")
        buf.write(u"\u02f7\7p\2\2\u02f7\u02f8\7q\2\2\u02f8\u02f9\7o\2\2\u02f9")
        buf.write(u"\u008c\3\2\2\2\u02fa\u02fb\7^\2\2\u02fb\u02fc\7o\2\2")
        buf.write(u"\u02fc\u02fd\7c\2\2\u02fd\u02fe\7v\2\2\u02fe\u02ff\7")
        buf.write(u"j\2\2\u02ff\u0300\7k\2\2\u0300\u0301\7v\2\2\u0301\u008e")
        buf.write(u"\3\2\2\2\u0302\u0303\7a\2\2\u0303\u0090\3\2\2\2\u0304")
        buf.write(u"\u0305\7`\2\2\u0305\u0092\3\2\2\2\u0306\u0307\7<\2\2")
        buf.write(u"\u0307\u0094\3\2\2\2\u0308\u0309\t\2\2\2\u0309\u0096")
        buf.write(u"\3\2\2\2\u030a\u030e\7f\2\2\u030b\u030d\5\u0095K\2\u030c")
        buf.write(u"\u030b\3\2\2\2\u030d\u0310\3\2\2\2\u030e\u030f\3\2\2")
        buf.write(u"\2\u030e\u030c\3\2\2\2\u030f\u0318\3\2\2\2\u0310\u030e")
        buf.write(u"\3\2\2\2\u0311\u0319\t\3\2\2\u0312\u0314\7^\2\2\u0313")
        buf.write(u"\u0315\t\3\2\2\u0314\u0313\3\2\2\2\u0315\u0316\3\2\2")
        buf.write(u"\2\u0316\u0314\3\2\2\2\u0316\u0317\3\2\2\2\u0317\u0319")
        buf.write(u"\3\2\2\2\u0318\u0311\3\2\2\2\u0318\u0312\3\2\2\2\u0319")
        buf.write(u"\u0098\3\2\2\2\u031a\u031b\t\3\2\2\u031b\u009a\3\2\2")
        buf.write(u"\2\u031c\u031d\t\4\2\2\u031d\u009c\3\2\2\2\u031e\u0320")
        buf.write(u"\5\u009bN\2\u031f\u031e\3\2\2\2\u0320\u0321\3\2\2\2\u0321")
        buf.write(u"\u031f\3\2\2\2\u0321\u0322\3\2\2\2\u0322\u032a\3\2\2")
        buf.write(u"\2\u0323\u0324\7.\2\2\u0324\u0325\5\u009bN\2\u0325\u0326")
        buf.write(u"\5\u009bN\2\u0326\u0327\5\u009bN\2\u0327\u0329\3\2\2")
        buf.write(u"\2\u0328\u0323\3\2\2\2\u0329\u032c\3\2\2\2\u032a\u0328")
        buf.write(u"\3\2\2\2\u032a\u032b\3\2\2\2\u032b\u0344\3\2\2\2\u032c")
        buf.write(u"\u032a\3\2\2\2\u032d\u032f\5\u009bN\2\u032e\u032d\3\2")
        buf.write(u"\2\2\u032f\u0332\3\2\2\2\u0330\u032e\3\2\2\2\u0330\u0331")
        buf.write(u"\3\2\2\2\u0331\u033a\3\2\2\2\u0332\u0330\3\2\2\2\u0333")
        buf.write(u"\u0334\7.\2\2\u0334\u0335\5\u009bN\2\u0335\u0336\5\u009b")
        buf.write(u"N\2\u0336\u0337\5\u009bN\2\u0337\u0339\3\2\2\2\u0338")
        buf.write(u"\u0333\3\2\2\2\u0339\u033c\3\2\2\2\u033a\u0338\3\2\2")
        buf.write(u"\2\u033a\u033b\3\2\2\2\u033b\u033d\3\2\2\2\u033c\u033a")
        buf.write(u"\3\2\2\2\u033d\u033f\7\60\2\2\u033e\u0340\5\u009bN\2")
        buf.write(u"\u033f\u033e\3\2\2\2\u0340\u0341\3\2\2\2\u0341\u033f")
        buf.write(u"\3\2\2\2\u0341\u0342\3\2\2\2\u0342\u0344\3\2\2\2\u0343")
        buf.write(u"\u031f\3\2\2\2\u0343\u0330\3\2\2\2\u0344\u009e\3\2\2")
        buf.write(u"\2\u0345\u0349\7(\2\2\u0346\u0348\5\u0095K\2\u0347\u0346")
        buf.write(u"\3\2\2\2\u0348\u034b\3\2\2\2\u0349\u034a\3\2\2\2\u0349")
        buf.write(u"\u0347\3\2\2\2\u034a\u034d\3\2\2\2\u034b\u0349\3\2\2")
        buf.write(u"\2\u034c\u0345\3\2\2\2\u034c\u034d\3\2\2\2\u034d\u034e")
        buf.write(u"\3\2\2\2\u034e\u035a\7?\2\2\u034f\u0357\7?\2\2\u0350")
        buf.write(u"\u0352\5\u0095K\2\u0351\u0350\3\2\2\2\u0352\u0355\3\2")
        buf.write(u"\2\2\u0353\u0354\3\2\2\2\u0353\u0351\3\2\2\2\u0354\u0356")
        buf.write(u"\3\2\2\2\u0355\u0353\3\2\2\2\u0356\u0358\7(\2\2\u0357")
        buf.write(u"\u0353\3\2\2\2\u0357\u0358\3\2\2\2\u0358\u035a\3\2\2")
        buf.write(u"\2\u0359\u034c\3\2\2\2\u0359\u034f\3\2\2\2\u035a\u00a0")
        buf.write(u"\3\2\2\2\u035b\u035c\7^\2\2\u035c\u035d\7p\2\2\u035d")
        buf.write(u"\u035e\7g\2\2\u035e\u035f\7s\2\2\u035f\u00a2\3\2\2\2")
        buf.write(u"\u0360\u0361\7>\2\2\u0361\u00a4\3\2\2\2\u0362\u0363\7")
        buf.write(u"^\2\2\u0363\u0364\7n\2\2\u0364\u0365\7g\2\2\u0365\u036c")
        buf.write(u"\7s\2\2\u0366\u0367\7^\2\2\u0367\u0368\7n\2\2\u0368\u036c")
        buf.write(u"\7g\2\2\u0369\u036c\5\u00a7T\2\u036a\u036c\5\u00a9U\2")
        buf.write(u"\u036b\u0362\3\2\2\2\u036b\u0366\3\2\2\2\u036b\u0369")
        buf.write(u"\3\2\2\2\u036b\u036a\3\2\2\2\u036c\u00a6\3\2\2\2\u036d")
        buf.write(u"\u036e\7^\2\2\u036e\u036f\7n\2\2\u036f\u0370\7g\2\2\u0370")
        buf.write(u"\u0371\7s\2\2\u0371\u0372\7s\2\2\u0372\u00a8\3\2\2\2")
        buf.write(u"\u0373\u0374\7^\2\2\u0374\u0375\7n\2\2\u0375\u0376\7")
        buf.write(u"g\2\2\u0376\u0377\7s\2\2\u0377\u0378\7u\2\2\u0378\u0379")
        buf.write(u"\7n\2\2\u0379\u037a\7c\2\2\u037a\u037b\7p\2\2\u037b\u037c")
        buf.write(u"\7v\2\2\u037c\u00aa\3\2\2\2\u037d\u037e\7@\2\2\u037e")
        buf.write(u"\u00ac\3\2\2\2\u037f\u0380\7^\2\2\u0380\u0381\7i\2\2")
        buf.write(u"\u0381\u0382\7g\2\2\u0382\u0389\7s\2\2\u0383\u0384\7")
        buf.write(u"^\2\2\u0384\u0385\7i\2\2\u0385\u0389\7g\2\2\u0386\u0389")
        buf.write(u"\5\u00afX\2\u0387\u0389\5\u00b1Y\2\u0388\u037f\3\2\2")
        buf.write(u"\2\u0388\u0383\3\2\2\2\u0388\u0386\3\2\2\2\u0388\u0387")
        buf.write(u"\3\2\2\2\u0389\u00ae\3\2\2\2\u038a\u038b\7^\2\2\u038b")
        buf.write(u"\u038c\7i\2\2\u038c\u038d\7g\2\2\u038d\u038e\7s\2\2\u038e")
        buf.write(u"\u038f\7s\2\2\u038f\u00b0\3\2\2\2\u0390\u0391\7^\2\2")
        buf.write(u"\u0391\u0392\7i\2\2\u0392\u0393\7g\2\2\u0393\u0394\7")
        buf.write(u"s\2\2\u0394\u0395\7u\2\2\u0395\u0396\7n\2\2\u0396\u0397")
        buf.write(u"\7c\2\2\u0397\u0398\7p\2\2\u0398\u0399\7v\2\2\u0399\u00b2")
        buf.write(u"\3\2\2\2\u039a\u039b\7#\2\2\u039b\u00b4\3\2\2\2\u039c")
        buf.write(u"\u039e\7^\2\2\u039d\u039f\t\3\2\2\u039e\u039d\3\2\2\2")
        buf.write(u"\u039f\u03a0\3\2\2\2\u03a0\u039e\3\2\2\2\u03a0\u03a1")
        buf.write(u"\3\2\2\2\u03a1\u00b6\3\2\2\2\33\2\u00bc\u00cc\u00db\u00ec")
        buf.write(u"\u0110\u018a\u0205\u030e\u0316\u0318\u0321\u032a\u0330")
        buf.write(u"\u033a\u0341\u0343\u0349\u034c\u0353\u0357\u0359\u036b")
        buf.write(u"\u0388\u03a0\3\b\2\2")
        return buf.getvalue()


class LaTeXLexer(Lexer):

    atn = ATNDeserializer().deserialize(serializedATN())

    decisionsToDFA = [DFA(ds, i) for i, ds in enumerate(atn.decisionToState)]

    T__0 = 1
    WS = 2
    THINSPACE = 3
    MEDSPACE = 4
    THICKSPACE = 5
    QUAD = 6
    QQUAD = 7
    NEGTHINSPACE = 8
    NEGMEDSPACE = 9
    NEGTHICKSPACE = 10
    CMD_LEFT = 11
    CMD_RIGHT = 12
    IGNORE = 13
    ADD = 14
    SUB = 15
    MUL = 16
    DIV = 17
    L_PAREN = 18
    R_PAREN = 19
    L_BRACE = 20
    R_BRACE = 21
    L_BRACE_LITERAL = 22
    R_BRACE_LITERAL = 23
    L_BRACKET = 24
    R_BRACKET = 25
    BAR = 26
    R_BAR = 27
    L_BAR = 28
    L_ANGLE = 29
    R_ANGLE = 30
    FUNC_LIM = 31
    LIM_APPROACH_SYM = 32
    FUNC_INT = 33
    FUNC_SUM = 34
    FUNC_PROD = 35
    FUNC_EXP = 36
    FUNC_LOG = 37
    FUNC_LN = 38
    FUNC_SIN = 39
    FUNC_COS = 40
    FUNC_TAN = 41
    FUNC_CSC = 42
    FUNC_SEC = 43
    FUNC_COT = 44
    FUNC_ARCSIN = 45
    FUNC_ARCCOS = 46
    FUNC_ARCTAN = 47
    FUNC_ARCCSC = 48
    FUNC_ARCSEC = 49
    FUNC_ARCCOT = 50
    FUNC_SINH = 51
    FUNC_COSH = 52
    FUNC_TANH = 53
    FUNC_ARSINH = 54
    FUNC_ARCOSH = 55
    FUNC_ARTANH = 56
    L_FLOOR = 57
    R_FLOOR = 58
    L_CEIL = 59
    R_CEIL = 60
    FUNC_SQRT = 61
    FUNC_OVERLINE = 62
    CMD_TIMES = 63
    CMD_CDOT = 64
    CMD_DIV = 65
    CMD_FRAC = 66
    CMD_BINOM = 67
    CMD_DBINOM = 68
    CMD_TBINOM = 69
    CMD_MATHIT = 70
    UNDERSCORE = 71
    CARET = 72
    COLON = 73
    DIFFERENTIAL = 74
    LETTER = 75
    NUMBER = 76
    EQUAL = 77
    NEQ = 78
    LT = 79
    LTE = 80
    LTE_Q = 81
    LTE_S = 82
    GT = 83
    GTE = 84
    GTE_Q = 85
    GTE_S = 86
    BANG = 87
    SYMBOL = 88

    channelNames = [u"DEFAULT_TOKEN_CHANNEL", u"HIDDEN"]

    modeNames = [u"DEFAULT_MODE"]

    literalNames = [
        u"<INVALID>",
        u"','",
        u"'\\quad'",
        u"'\\qquad'",
        u"'\\negmedspace'",
        u"'\\negthickspace'",
        u"'\\left'",
        u"'\\right'",
        u"'+'",
        u"'-'",
        u"'*'",
        u"'/'",
        u"'('",
        u"')'",
        u"'{'",
        u"'}'",
        u"'\\{'",
        u"'\\}'",
        u"'['",
        u"']'",
        u"'|'",
        u"'\\right|'",
        u"'\\left|'",
        u"'\\langle'",
        u"'\\rangle'",
        u"'\\lim'",
        u"'\\int'",
        u"'\\sum'",
        u"'\\prod'",
        u"'\\exp'",
        u"'\\log'",
        u"'\\ln'",
        u"'\\sin'",
        u"'\\cos'",
        u"'\\tan'",
        u"'\\csc'",
        u"'\\sec'",
        u"'\\cot'",
        u"'\\arcsin'",
        u"'\\arccos'",
        u"'\\arctan'",
        u"'\\arccsc'",
        u"'\\arcsec'",
        u"'\\arccot'",
        u"'\\sinh'",
        u"'\\cosh'",
        u"'\\tanh'",
        u"'\\arsinh'",
        u"'\\arcosh'",
        u"'\\artanh'",
        u"'\\lfloor'",
        u"'\\rfloor'",
        u"'\\lceil'",
        u"'\\rceil'",
        u"'\\sqrt'",
        u"'\\overline'",
        u"'\\times'",
        u"'\\cdot'",
        u"'\\div'",
        u"'\\frac'",
        u"'\\binom'",
        u"'\\dbinom'",
        u"'\\tbinom'",
        u"'\\mathit'",
        u"'_'",
        u"'^'",
        u"':'",
        u"'\\neq'",
        u"'<'",
        u"'\\leqq'",
        u"'\\leqslant'",
        u"'>'",
        u"'\\geqq'",
        u"'\\geqslant'",
        u"'!'",
    ]

    symbolicNames = [
        u"<INVALID>",
        u"WS",
        u"THINSPACE",
        u"MEDSPACE",
        u"THICKSPACE",
        u"QUAD",
        u"QQUAD",
        u"NEGTHINSPACE",
        u"NEGMEDSPACE",
        u"NEGTHICKSPACE",
        u"CMD_LEFT",
        u"CMD_RIGHT",
        u"IGNORE",
        u"ADD",
        u"SUB",
        u"MUL",
        u"DIV",
        u"L_PAREN",
        u"R_PAREN",
        u"L_BRACE",
        u"R_BRACE",
        u"L_BRACE_LITERAL",
        u"R_BRACE_LITERAL",
        u"L_BRACKET",
        u"R_BRACKET",
        u"BAR",
        u"R_BAR",
        u"L_BAR",
        u"L_ANGLE",
        u"R_ANGLE",
        u"FUNC_LIM",
        u"LIM_APPROACH_SYM",
        u"FUNC_INT",
        u"FUNC_SUM",
        u"FUNC_PROD",
        u"FUNC_EXP",
        u"FUNC_LOG",
        u"FUNC_LN",
        u"FUNC_SIN",
        u"FUNC_COS",
        u"FUNC_TAN",
        u"FUNC_CSC",
        u"FUNC_SEC",
        u"FUNC_COT",
        u"FUNC_ARCSIN",
        u"FUNC_ARCCOS",
        u"FUNC_ARCTAN",
        u"FUNC_ARCCSC",
        u"FUNC_ARCSEC",
        u"FUNC_ARCCOT",
        u"FUNC_SINH",
        u"FUNC_COSH",
        u"FUNC_TANH",
        u"FUNC_ARSINH",
        u"FUNC_ARCOSH",
        u"FUNC_ARTANH",
        u"L_FLOOR",
        u"R_FLOOR",
        u"L_CEIL",
        u"R_CEIL",
        u"FUNC_SQRT",
        u"FUNC_OVERLINE",
        u"CMD_TIMES",
        u"CMD_CDOT",
        u"CMD_DIV",
        u"CMD_FRAC",
        u"CMD_BINOM",
        u"CMD_DBINOM",
        u"CMD_TBINOM",
        u"CMD_MATHIT",
        u"UNDERSCORE",
        u"CARET",
        u"COLON",
        u"DIFFERENTIAL",
        u"LETTER",
        u"NUMBER",
        u"EQUAL",
        u"NEQ",
        u"LT",
        u"LTE",
        u"LTE_Q",
        u"LTE_S",
        u"GT",
        u"GTE",
        u"GTE_Q",
        u"GTE_S",
        u"BANG",
        u"SYMBOL",
    ]

    ruleNames = [
        u"T__0",
        u"WS",
        u"THINSPACE",
        u"MEDSPACE",
        u"THICKSPACE",
        u"QUAD",
        u"QQUAD",
        u"NEGTHINSPACE",
        u"NEGMEDSPACE",
        u"NEGTHICKSPACE",
        u"CMD_LEFT",
        u"CMD_RIGHT",
        u"IGNORE",
        u"ADD",
        u"SUB",
        u"MUL",
        u"DIV",
        u"L_PAREN",
        u"R_PAREN",
        u"L_BRACE",
        u"R_BRACE",
        u"L_BRACE_LITERAL",
        u"R_BRACE_LITERAL",
        u"L_BRACKET",
        u"R_BRACKET",
        u"BAR",
        u"R_BAR",
        u"L_BAR",
        u"L_ANGLE",
        u"R_ANGLE",
        u"FUNC_LIM",
        u"LIM_APPROACH_SYM",
        u"FUNC_INT",
        u"FUNC_SUM",
        u"FUNC_PROD",
        u"FUNC_EXP",
        u"FUNC_LOG",
        u"FUNC_LN",
        u"FUNC_SIN",
        u"FUNC_COS",
        u"FUNC_TAN",
        u"FUNC_CSC",
        u"FUNC_SEC",
        u"FUNC_COT",
        u"FUNC_ARCSIN",
        u"FUNC_ARCCOS",
        u"FUNC_ARCTAN",
        u"FUNC_ARCCSC",
        u"FUNC_ARCSEC",
        u"FUNC_ARCCOT",
        u"FUNC_SINH",
        u"FUNC_COSH",
        u"FUNC_TANH",
        u"FUNC_ARSINH",
        u"FUNC_ARCOSH",
        u"FUNC_ARTANH",
        u"L_FLOOR",
        u"R_FLOOR",
        u"L_CEIL",
        u"R_CEIL",
        u"FUNC_SQRT",
        u"FUNC_OVERLINE",
        u"CMD_TIMES",
        u"CMD_CDOT",
        u"CMD_DIV",
        u"CMD_FRAC",
        u"CMD_BINOM",
        u"CMD_DBINOM",
        u"CMD_TBINOM",
        u"CMD_MATHIT",
        u"UNDERSCORE",
        u"CARET",
        u"COLON",
        u"WS_CHAR",
        u"DIFFERENTIAL",
        u"LETTER",
        u"DIGIT",
        u"NUMBER",
        u"EQUAL",
        u"NEQ",
        u"LT",
        u"LTE",
        u"LTE_Q",
        u"LTE_S",
        u"GT",
        u"GTE",
        u"GTE_Q",
        u"GTE_S",
        u"BANG",
        u"SYMBOL",
    ]

    grammarFileName = u"LaTeX.g4"

    def __init__(self, input=None, output=sys.stdout):
        super(LaTeXLexer, self).__init__(input, output=output)
        self.checkVersion("4.7.2")
        self._interp = LexerATNSimulator(
            self, self.atn, self.decisionsToDFA, PredictionContextCache()
        )
        self._actions = None
        self._predicates = None
