name: examples

on:
  push:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: "py${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: qed
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install .

      - name: Run the examples
        shell: bash -l {0}
        run: |
          cd docs && python examples.py

      - uses: actions/upload-artifact@v2
        with:
          name: examples-for-${{ github.sha }}
          path: docs/examples

      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
