name: tests

on:
  push:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: "py${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: qed
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install .

      - name: Run the unit tests
        shell: bash -l {0}
        run: python -m pytest -v tests --junitxml=junit/test-results.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: junit/test-*.xml
          comment_on_pr: false
